### ISSUE TITLE
菜单栏按钮显示错误

### ISSUE THREAD

**Issue by mindcont** [tufu9441/maupassant-hexo#103]
如下所示，求解？
![hexo](https://cloud.githubusercontent.com/assets/13744152/15072764/add218fe-13c7-11e6-951a-352ebdfd317a.png)

**Comment by tufu9441** [comment]
你Hexo根目录下或主题目录下`_config.yml`中archives的路径有没设置对的地方吧。

**Comment by mindcont** [comment]
Hexo根目录下
> Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


主题目录下:
>menu:
  -- page: 首页
    directory: 
    icon: fa-home
  -- page: 归档
    directory: archives/
    icon: fa-archive
  -- page: 关于
    directory: about/
    icon: fa-user
  --page: 历史
    directory: history/
    icon: fa-history
  -- page: 订阅
    directory: atom.xml
    icon: fa-rss

点击可以正常跳转，但菜单按钮显示错误。
请查看 [微记元](http://blog.mindcont.com)

**Comment by tufu9441** [comment]
首页的directory要设置成"`.`"

**Comment by mindcont** [comment]
谢谢，你完美的解决了我的问题

**Comment by zealseeker** [comment]
@tufu9441 你好，我参数设置正确，不过遇到如下问题，由于从wordpress迁移过来，所以保留传统文章的url是/archives/:title  这样会导致在文章内容中会出现上述问题。能不能限制archives/只在根目录或者pages目录时是active的，而其他情况是inacitve的？
