### ISSUE TITLE
如何更改字体

### ISSUE THREAD

**Issue by ghuiii** [tufu9441/maupassant-hexo#108]
想更改一下Title的字体, 没找到配置项.谢谢!

**Comment by tufu9441** [comment]
style.scss里面自己找font-family。

Best regards,
Haoming Wei
On 周三, 5月 11, 2016 at 23:16, ghui <notifications@github.com> wrote:
想更改一下Title的字体, 没找到配置项.谢谢!

**Comment by ghuiii** [comment]
关了吧
