### ISSUE TITLE
多说的分享功能能否去掉？

### ISSUE THREAD

**Issue by yangcaimu** [tufu9441/maupassant-hexo#109]
本身模板已经自带分享了，添加完多说评论后，评论框上又再加上了分享，去多说的后台管理查看了，没找到关闭的菜单，请问还有其他的方式关闭多说的分享功能？

**Comment by tufu9441** [comment]
你可以在主题配置中关闭自带的分享功能。

**Comment by yangcaimu** [comment]
恩，这个清楚，个人感觉多说的分享太丑了，想去掉

**Comment by tufu9441** [comment]
`layout/post.jade`第36-50行删掉就行了。
