### ISSUE TITLE
如何在首页菜单自定义一个带评论的留言页面？

### ISSUE THREAD

**Issue by ArtinHuang** [tufu9441/maupassant-hexo#11]
如题。

**Comment by v123582** [comment]
你可以開一個 page 作為留言頁，接著到 /theme/layout/ 開一個 layout ，直接嵌入留言板的 javascript 進去，最後再到 /theme/_config.yml 中的 meau 加上該 page 的網址。

嵌入留言板的 javascript 可以參考「多說」或「Disqus」

**Comment by tufu9441** [comment]
@v123582 说得很对，感谢解答。

**Comment by ArtinHuang** [comment]
@v123582 感谢，已经实现功能。
