### ISSUE TITLE
mac上使用报错ERROR Process failed: layout/archive.jade TypeError: Cannot read property 'compile' of undefined... ...

### ISSUE THREAD

**Issue by djstava** [tufu9441/maupassant-hexo#114]
hexo server启动服务时报错ERROR Process failed: layout/archive.jade
TypeError: Cannot read property 'compile' of undefined

ERROR Process failed: layout/base.jade
TypeError: Cannot read property 'compile' of undefined

ERROR Process failed: layout/index.jade
TypeError: Cannot read property 'compile' of undefined

**Comment by tufu9441** [comment]
See #84

**Comment by djstava** [comment]
重装hero-renderer-jade和hero-renderer-sass后，运行正常，谢谢，请关闭这个issue。
