### ISSUE TITLE
可否加入pjax

### ISSUE THREAD

**Issue by caisiduo** [tufu9441/maupassant-hexo#116]
加入pjax可以大幅度提升记载速度和访问者的体验

**Comment by tufu9441** [comment]
抱歉对这个东西还不了解，而且貌似还没有哪个Hexo主题有添加这个的先例吧……

**Comment by caisiduo** [comment]
我记得官方主题站是有个pjax来着

**Comment by tufu9441** [comment]
是哪个能否告诉我，我去学习一下。

**Comment by caisiduo** [comment]
carbon

**Comment by tufu9441** [comment]
看了一下已然超出了我能力范围😂……等待好心的大神提交PR吧。

**Comment by caisiduo** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f602.png)
