### ISSUE TITLE
开启不蒜子统计之后，并不显示统计数据

### ISSUE THREAD

**Issue by ZhaoKaiQiang** [tufu9441/maupassant-hexo#118]

**Comment by ZhaoKaiQiang** [comment]
blog地址  kaizige.vip 已开启不蒜子

**Comment by tufu9441** [comment]
我看到你的博客里显示是正常的啊：

![qq 20160612131639](https://cloud.githubusercontent.com/assets/6790361/15989137/ecd8b180-309f-11e6-89fd-6eb06d994beb.jpg)

**Comment by ZhaoKaiQiang** [comment]
哦哦，这个是统计的文章浏览量啊，没有全站点的总访问量数据吗

**Comment by tufu9441** [comment]
没有。需要的话自己添加吧。

**Comment by ZhaoKaiQiang** [comment]
好的
