### ISSUE TITLE
新加的这个timeline，建议做成Hexo的Script

### ISSUE THREAD

**Issue by ChanningSun** [tufu9441/maupassant-hexo#119]
因为现在的timeline添加的方式感觉不太合理，还需要在config里加东西。

理想的方式我想应该是写hexo的Script

**Comment by tufu9441** [comment]
然而我并不会写什么Script……

**Comment by v123582** [comment]
我覺得可以改成 layout/timeline.jade 可以讀 markdown 的資料就可以了

**Comment by tufu9441** [comment]
其实我觉得在`_config.yml`中完成配置挺方便的，这个是跟[TKL](https://github.com/SuperKieran/TKL)这个主题学来的。

**Comment by v123582** [comment]
差別就是說這樣只能有一個 timeline ，不能增加第二頁以上的 timeline

**Comment by tufu9441** [comment]
@v123582 哦哦，原来如此，这个还真没有考虑到。不过其实需要弄多个Timeline的情况也不多见吧。

**Comment by v123582** [comment]
@tufu9441 是的，一般來說只會有一個 timeline，主要是彈性問題吧
可以看有沒有人有這個需求，再讓有需求的人自己貢獻吧XDDD

@ChanningSun 如果你有需要的話，可以改改看，在貢獻給其他人！

**Comment by qiqingfu** [comment]
timeline 在哪个页面设置呀
