### ISSUE TITLE
关于mathjax

### ISSUE THREAD

**Issue by cfdtlee** [tufu9441/maupassant-hexo#12]
很喜欢这个简洁的主题，请问这个主题能支持mathjax吗？

**Comment by tufu9441** [comment]
个人目前还没有这方面的需求，你如果能够添加上这个功能的话欢迎提交pull request。

On 周日, 11月 15, 2015 at 02:18, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
很喜欢这个简洁的主题，��请问这个主题能支持mathjax吗？

**Comment by tufu9441** [comment]
@cfdtlee 使用[hexo-math](https://github.com/akfish/hexo-math)这个插件可以完美地解决mathjax显示的问题，并且不需要对主题做出任何修改。

**Comment by cfdtlee** [comment]
好的，我试试，谢谢啦

**Comment by yezhejack** [comment]
我也遇到这个问题，我安装了hexo-math，但是无法使用，切换回原始的主题，对应的公式就可以解析了。是不是主题的哪个地方还需要设置？
