### ISSUE TITLE
在移动模式现实边栏菜单

### ISSUE THREAD

**Issue by justinchuby** [tufu9441/maupassant-hexo#124]
希望能增加一个在手机大小的屏幕显示的汉堡菜单，包括搜索框、标签和分类等等。现在搜索框在小屏幕好像是不显示的？

**Comment by tufu9441** [comment]
目前该模板的响应式设计在移动设备上默认会隐藏侧边栏，个人还没有能力实现你所述的功能……

**Comment by justinchuby** [comment]
我觉得可以做一个折中的方案，就是在移动模式下可选将搜索栏放在页面底部，就像某些wordpress网站一样？

**Comment by tufu9441** [comment]
见过这种，能做的话早做了。
