### ISSUE TITLE
Code Block 行号显示错误

### ISSUE THREAD

**Issue by justinchuby** [tufu9441/maupassant-hexo#133]
在有些情况下代码块的行号会显示不正常。
例如在[https://www.haomwei.com/technology/how-to-install-hexo-on-mac.html](https://www.haomwei.com/technology/how-to-install-hexo-on-mac.html)页面，的

> 直接用nvm install <version>指令安装官网上建议的版本：

那里，行号就被滚动条遮住了显示不出来

MacOS El Capitan, Safari和chrome都一样。

**Comment by justinchuby** [comment]
A proposed fix is modifying the line height. As in https://github.com/justinchuby/maupassant-hexo/commit/5c25fc7701b045dff5ddc988e18814da36772878.

**Comment by tufu9441** [comment]
这应该是Mac系统设置的问题，按照下图的方式设置应该就不会存在这个问题：

![01:05:18.jpg](http://i.imgur.com/HJVLtuY.jpg)

**Comment by justinchuby** [comment]
Windows系统下的的chrome和edge也有这样的问题。我觉得修复代码比较合适。
