### ISSUE TITLE
Jade has been renamed to pug, please install the latest version of pug instead of jade

### ISSUE THREAD

**Issue by mckobe23** [tufu9441/maupassant-hexo#136]
package 'jade' depricated

**Comment by tufu9441** [comment]
This theme just needs to install [hexo-renderer-jade](https://github.com/hexojs/hexo-renderer-jade)

**Comment by tufu9441** [comment]
Yes, the same problem has been found, see https://github.com/hexojs/hexo-renderer-jade/issues/7
