### ISSUE TITLE
不算子的代码添加到哪里呢？

### ISSUE THREAD

**Issue by maojinyuan** [tufu9441/maupassant-hexo#139]
我想问一下，不算子的代码加到哪里呢？刚接触，在原主题中我是放在footer.ejs，但是你这个文件是jade文件，放进去试了一下，发现没有起效啊。

**Comment by maojinyuan** [comment]
楼主，能不能帮忙回答一下啊？我想要的是整个页面的点击量，不是单篇文章的。顺便问一下，你这个主题可以添加tag的吗？

**Comment by tufu9441** [comment]
放在footer.jade，跟ejs的不一样要按照jade语法来写。
