### ISSUE TITLE
category tags concatenated without spaces on posts page

### ISSUE THREAD

**Issue by mugshepherd** [tufu9441/maupassant-hexo#14]
Hi - 
i was having an issue with your theme where multiple categories assigned to a post were being concatenated without spacing in between them on the posts page.  

![image](https://cloud.githubusercontent.com/assets/7784700/11509530/a0e2fe70-986f-11e5-9480-3b26df2028cc.png)

It may be a "hacky" fix, but I inserted a `" "` in posts.jade, line 13 `a(href=url_for(category.path))= " " + category.name` to produce the necessary spacing.  

![image](https://cloud.githubusercontent.com/assets/7784700/11509509/89c36e78-986f-11e5-835a-de848968bb8e.png)

Wanted to give you a heads up.  Thanks for the excellent theme!

**Comment by tufu9441** [comment]
@mugshepherd Many thanks for your kind remind, and I have fixed this bug now.
