### ISSUE TITLE
新手上路。但是更新主题之后，页面感觉是乱码，好乱。

### ISSUE THREAD

**Issue by csyuking1989** [tufu9441/maupassant-hexo#141]
1. 我是按照教程，一步一步操作的。
2. 但是 更新主题之后，发现页面好乱。页面地址：csyuking1989.github.io  
3. 可以帮我看一下吗？万分感谢

**Comment by tufu9441** [comment]
css没有加载。看了一下你css目录下的文件目前是style.scss，而html代码里需要载入的是style.css。可能是你hexo-renderer-sass没有安好，换源重新安装试试。本地测试有问题没？

**Comment by coder-gao** [comment]
我也遇到相同的问题。解决办法是找到style.scss复制代码，利用编译工具  http://www.sassmeister.com/ 手动编译成css代码替换。
