### ISSUE TITLE
文章标题比较长时，切换上一篇、下一篇文章显示错乱

### ISSUE THREAD

**Issue by aimer1124** [tufu9441/maupassant-hexo#146]
文章底部的上一篇、下一篇文章被换行

效果参考：[http://aimer1124.github.io/2016/05/09/Book-%E5%88%AB%E7%AC%91%EF%BC%8C%E8%BF%99%E6%98%AF%E5%A4%A7%E6%B8%85%E6%AD%A3%E5%8F%B2/](http://aimer1124.github.io/2016/05/09/Book-%E5%88%AB%E7%AC%91%EF%BC%8C%E8%BF%99%E6%98%AF%E5%A4%A7%E6%B8%85%E6%AD%A3%E5%8F%B2/)

**Comment by tufu9441** [comment]
这是因为你的文章标题太长了，有限的宽度内排列不下自然会换行。

**Comment by aimer1124** [comment]
@tufu9441 能否优化下样式显示，在标题过长的时候，超出固定长度之后，剩余的显示...。

**Comment by cxgreat2014** [comment]
这个我试过了，最终效果还不如换行，最简单的计数，若是标题长度小于n字输出全部，大于n字就输出前n字加省略号，但是那样截断看起来更不好看
