### ISSUE TITLE
disqus shortname添加了但是unable to load

### ISSUE THREAD

**Issue by leonfrank** [tufu9441/maupassant-hexo#147]
我在theme下面的_config.yml里添加了disqus的shortname 仍然显示unable to load 怎么解决

**Comment by JustinZhou** [comment]
同问，加入多说shortname之后没有生效。

**Comment by tufu9441** [comment]
@leonfrank disqus是因为国内被墙了，打不开正常。
@JustinZhou 看你的多说是正常的啊。

**Comment by JustinZhou** [comment]
恩，现在好了。之前是因为加入shortname之后没有删除原来的comments。
duoshuo: shortname~~## Your duoshuo_shortname, e.g. username~~
