### ISSUE TITLE
英文出错

### ISSUE THREAD

**Issue by gzpgzpgzp** [tufu9441/maupassant-hexo#148]
![image](https://cloud.githubusercontent.com/assets/12186221/17726648/ea41d648-6486-11e6-86af-53061e3c1b08.png)

有时候是正常的  这是我哪里没有配置好吗

![image](https://cloud.githubusercontent.com/assets/12186221/17726687/2a998d76-6487-11e6-8109-35529e50526c.png)
但实际是
![image](https://cloud.githubusercontent.com/assets/12186221/17726701/3d52e908-6487-11e6-8f50-57e215b8bf9b.png)

**Comment by tufu9441** [comment]
语言没设置对，可能设成了德语。

**Comment by gzpgzpgzp** [comment]
ok了  谢谢我没加zh-cn

**Comment by WaveLi123** [comment]
谢谢作者了~

**Comment by ysymi** [comment]
@gzponline 请问你第一个截图里 配色是什么？
