### ISSUE TITLE
关于加入fork on github

### ISSUE THREAD

**Issue by imkratos** [tufu9441/maupassant-hexo#15]
楼主，我把fork的代码加在了base.jade中，发现这个编译的时候会自动给Img标签，套上一层a标签，目前没有找到在哪编译进去的，您知道吗。

**Comment by tufu9441** [comment]
是fancybox的效果，如果不需要启用fancybox，加上rel=nofancybox属性即可。

On 周三, 12月 2, 2015 at 18:40, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
楼主，我把fork的代码加在了base.jade中，发现这个编译的时候会自动给Img标签，套上一层a标签，目前没有找到在哪编译进去的，您知道吗。

**Comment by imkratos** [comment]
恩，我看给我发的邮件里是：
是fancybox的效果，如果不需要启用fancybox，加上rel=nofancybox属性即可。
然后根据你的提示找到了源码，其实是class本来想来说一下，结果发现你改了，哈哈。

**Comment by tufu9441** [comment]
嗯，昨天手机回复得不太准确。

**Comment by tufu9441** [comment]
@imkratos 我看到你的博客侧边栏搜索框显示有点问题（Windows平台下Chrome浏览器），应该是一个主题的BUG（其实主要是Hexo自带的google搜索的问题），我已经修复了现在。

**Comment by imkratos** [comment]
@tufu9441 恩，好的，多谢。
