### ISSUE TITLE
clean deploy报错提示operation not permitted,

### ISSUE THREAD

**Issue by gzpgzpgzp** [tufu9441/maupassant-hexo#151]
我想换一个icon，换完就报错，请问是icon的问题吗 ，我想要怎么解决，之前一直正常使用
![image](https://cloud.githubusercontent.com/assets/12186221/17926196/9e4bdf6c-6a22-11e6-9635-89f4be6935e6.png)

**Comment by tufu9441** [comment]
看不出是哪的问题，你确定换的图标是fontawesome里包含的且名称正确？

**Comment by gzpgzpgzp** [comment]
fontawesome在哪里   我是直接替换的source的favicon.ico

**Comment by tufu9441** [comment]
哦哦，你说的是favicon啊。直接替换就行了，看报错是你Hexo环境的问题，跟主题无关。

**Comment by gzpgzpgzp** [comment]
ok 谢谢了
