### ISSUE TITLE
能够添加menu的categories，显示正确的分类

### ISSUE THREAD

**Issue by windyyong** [tufu9441/maupassant-hexo#153]
我用hexo new page categories 生成了分类，
## 在categories的index.md文件下改为：

title: categories
date: 2016-08-27 15:39:08
type: "categories"
## comments: false

修改总配置文件_config.yml文件下的
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories

修改主题下面的_config.yml，但是
menu:
- page: categories
  directory: categories/
  icon: fa-home

然后点击menu上面的categories，只是作为正常的空白文章显示，并没有分类，
目前已经有了分类test，请问是否有增加分类的方法

**Comment by tufu9441** [comment]
目前主题并不支持新建显示全部分类或者标签的页面，没有写相关的页面模板和CSS。

**Comment by tufu9441** [comment]
#232
