### ISSUE TITLE
百度收录认证

### ISSUE THREAD

**Issue by smileLuckBoy** [tufu9441/maupassant-hexo#154]
您好，我在做百度认证网站时候，把百度认证的html文件放置在source目录下，在执行hexo g后，发现public目录下的这个html文件被加了好多其它的内容。最终导致百度认证失败。博主之前有遇到这个问题么？

**Comment by jarways** [comment]
是的，我也遇到这种情况，现在我的做法是每次在“hexo g”之后手动把“baidu_verify_x.html”文件拷贝到public目录下，然后再deploy的。比较麻烦

**Comment by smileLuckBoy** [comment]
查看hexo的源码，发现可以通过这样的途径解决：
找到这个文件：/node_modules/hexo/lib/hexo/render.js
修改其中的方法：isRenderable ，增加判断如果是baidu_verify（这个是百度认证文件文件名截取部分）认证文件，如果是的话，就不进行render
Render.prototype.isRenderable = function(path) {
  if (path.indexOf("baidu_verify") >= 0)
    return false;
  return this.renderer.isRenderable(path);
};

**Comment by tufu9441** [comment]
我个人并不使用百度的这个服务。你说的解决方法应该可以，不过我觉得@jarways 的土办法更直接，LOL

**Comment by hiberabyss** [comment]
可以编辑对应的 `baidu_verify_yourid.html` 文件，加入禁止 layout 的 front-matter，例如：

```
---
layout: false
sitemap: false
---
Original Content
```
