### ISSUE TITLE
请问在安装 jade的时候出现这个问题怎么解决呢?

### ISSUE THREAD

**Issue by Mulliken** [tufu9441/maupassant-hexo#155]
$ npm install hexo-renderer-jade --save
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
hexo-site@0.0.0 G:\Mulliken\Hexo
`-- hexo-renderer-jade@0.3.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
![image](https://cloud.githubusercontent.com/assets/19218605/18033152/fcc89782-6d4d-11e6-9159-4fab3703b0a0.png)

最后效果是这样的, 您看看哪里出了问题?

**Comment by tufu9441** [comment]
See #136
