### ISSUE TITLE
请问, 在最近评论中打开对应文章时跳转到了"yoursite.com", 这种情况应该怎么修改?

### ISSUE THREAD

**Issue by Mulliken** [tufu9441/maupassant-hexo#157]
打开文章链接, 发现是 yoursite.com/xxxxxxxxxxx
请问修改哪个文件可以改正这个网址呢?

**Comment by tufu9441** [comment]
disqus后台。

**Comment by coder-gao** [comment]
在Hexo配置文件_config.yml中修改 url 节点

**Comment by Mulliken** [comment]
_config.yml中的 url 已经设置为自己的网址了. 在多说中的网址也都是我自己的网址.  请问这是怎么回事呀?

**Comment by coder-gao** [comment]
这就尴尬了，重新编译下试试

**Comment by Mulliken** [comment]
我明白了, 谢谢你们~, 我是在多说中弄错了.

**Comment by txgyy** [comment]
大兄弟  我 也遇到了这个问题  你是怎么解决的啊
