### ISSUE TITLE
想问下您的博客中关于、留言、历史的模块的写法？

### ISSUE THREAD

**Issue by WaveLi123** [tufu9441/maupassant-hexo#158]
是个新手，感觉写的很好，方便的话麻烦分享下，谢谢了！（看到有历史板块的分享，不过不知道是要放在该主题下的还是hexo下的sourse目录啊？两个都试了下，前者乱码，后者显示效果和您的博客不一样）

**Comment by tufu9441** [comment]
主题的中英文文档中都已写明了页面和timeline的建立方法。

**Comment by WaveLi123** [comment]
嗯，我看过那个了，想问下您具体的页面设计内容? 方便的话，可否将您自己设计的博客源码分享下，想照着学习下，麻烦了！

**Comment by tufu9441** [comment]
我没有什么特殊的设计，都是主题原版的效果。

**Comment by WaveLi123** [comment]
嗯，知道了，谢谢你！
