### ISSUE TITLE
disqus和分享，fancybox失效

### ISSUE THREAD

**Issue by cconecode** [tufu9441/maupassant-hexo#159]
启用了disqus评论，但文章下面的分享按钮和标签失效了，fancybox设置为true，并不起作用，是否还需进行其他的设置？

**Comment by cconecode** [comment]
以及如何在文章标题下面显示时间和categories和评论？（不是博客首页），望告知，谢谢！

**Comment by tufu9441** [comment]
感觉像是你主题没有正确安装，文章页里都没有侧边栏。

**Comment by cconecode** [comment]
我在文章页里面采取了layout: single-column，所以只有单栏页面，去除了侧边栏

**Comment by tufu9441** [comment]
既然你用的是页面的模板，默认就没有标题下的meta部分。其它的功能也没有post模板齐全。

**Comment by cconecode** [comment]
那我试试将layout改成:post试一下

**Comment by cconecode** [comment]
问题解决了，十分感谢~
