### ISSUE TITLE
markdown 引用> 的标示不起作用，都变成逗号了

### ISSUE THREAD

**Issue by tonnyone** [tufu9441/maupassant-hexo#16]
markdown 引用> 的标示不起作用，都变成逗号了

**Comment by tufu9441** [comment]
这不是主题的问题，我的所有日志都显示正常，其它用户也是。例如：
https://www.haomwei.com/emotion/twenty-six.html
https://www.haomwei.com/emotion/Station-by-LiJian.html
http://v123582.github.io/2015/10/25/用-hexo-建立一個自己的部落格/

**Comment by tonnyone** [comment]
谢谢，我再看一下

**Comment by tonnyone** [comment]
https://www.haomwei.com/emotion/Station-by-LiJian.html

**Comment by tonnyone** [comment]
这个博客也是这个问题

**Comment by tonnyone** [comment]
这个是专门针对引用这个标示，做的效果吗？

**Comment by tufu9441** [comment]
这不就是我的博客么？引用的样式就是这样的啊。
![ScreenCapture at Fri Dec 4 19:18:19 CST 2015.png](https://ooo.0o0.ooo/2015/12/04/56617711c61aa.png)

**Comment by tonnyone** [comment]
对，就是以为告别还会再见这句前边的那个双引号，这个是针对引用专门做的效果吗？

**Comment by tonnyone** [comment]
![Uploading 搜狗截图20151204191823.png…](这个地方)

**Comment by tufu9441** [comment]
是啊，这个样式有这么丑或者难以辨认么……

**Comment by tonnyone** [comment]
哦，好的，我以为我这里bug了，谢谢了！

**Comment by luhaoaimama1** [comment]
我也是这个问题 好蛋疼
