### ISSUE TITLE
添加多说，文章下方出来的是分享不是评论

### ISSUE THREAD

**Issue by zhangjiahuan8888** [tufu9441/maupassant-hexo#160]
效果就是这样的，随便点一个进去   zhangjiahuan.cn
换别的主题是正常的，但实在不想用别的主题。。
求解

**Comment by tufu9441** [comment]
disqus和多说的shortname在主题配置里输入得不对，把后面的注释内容都带上了。

**Comment by zhangjiahuan8888** [comment]
多谢 评论搞定了。但是现在点击分享得到的网址点进去页面地址有误

**Comment by tufu9441** [comment]
你自己的站点URL没写完整。
