### ISSUE TITLE
不蒜子统计这个在配置文件中开启true后，怎么在前端显示？

### ISSUE THREAD

**Issue by chuhemiao** [tufu9441/maupassant-hexo#162]
1. 没有找到像关的设置在那里，求助。。。

ps：现在用的还是我之前的那种方法，引入不蒜子js，然后调用的。

**Comment by aimer1124** [comment]
只需要开启配制文件就可以，其它任何也不用做。
`_config.yml`中的配制
```
busuanzi: true
```
具体的效果是在文章页面，
![image](https://cloud.githubusercontent.com/assets/5865980/18154833/ab9448c6-703a-11e6-8e78-7c283ee92bfb.png)

[http://aimer1124.github.io/2016/08/31/Tool-%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5%E4%B9%8BJMeter/](http://aimer1124.github.io/2016/08/31/Tool-%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5%E4%B9%8BJMeter/)

**Comment by chuhemiao** [comment]
@aimer1124 嗯，貌似这个是统计单个文章的，之前还真没注意到，刚才突然发现就闪了一下然后就没了，是不是因为图标加载不出来的问题？。我那个加的是整站的统计

**Comment by tufu9441** [comment]
有时候显示不出来是不蒜子那边服务器的问题。

**Comment by chuhemiao** [comment]
@tufu9441 晓得了，请问下时间线那个是怎么调用的？

**Comment by tufu9441** [comment]
主题配置里有写。

**Comment by chuhemiao** [comment]
@tufu9441 我是在配置里面加了，但是前端页面并没有显示，然后我又加了个目录里面放index.md还是不出时间轴，只有上面一个分类，点开后没内容，所以问下index.md是要加什么内容？

**Comment by tufu9441** [comment]
```markdown
---
title: 历史
layout: timeline
comments: false
---
```

**Comment by chuhemiao** [comment]
@tufu9441 感谢
