### ISSUE TITLE
发布到github后，样式乱来，本地调试页面是正常显示的

### ISSUE THREAD

**Issue by WaterZhang** [tufu9441/maupassant-hexo#163]
网站: zhangzemiao.com
发布后，样式是乱的。本地调试，页面是正常显示的。
这是什么问题引起的?

**Comment by WaterZhang** [comment]
我使用的win 10系统。

**Comment by WaterZhang** [comment]
办公使用的是win7，重新deploy到github。样式是ok的，这个是不是系统兼容问题？

**Comment by tufu9441** [comment]
有可能，有时候`hexo-renderer-sass`没有安装好就不会把`style.scss`编译成`style.css`。

**Comment by WaterZhang** [comment]
今天下班回去试一下，重新安装hexo-renderer-sass看看，谢谢。

**Comment by YLee9527** [comment]
是不是放在github仓的一个文件夹里面了，放在根目录不会出现样式混乱的情况

**Comment by tufu9441** [comment]
@YLee9527 跟这个应该没什么关系。

**Comment by WaterZhang** [comment]
重新安装了hexo-renderer-sass，试了一下，成功了，谢谢。
