### ISSUE TITLE
页面宽度问题咨询

### ISSUE THREAD

**Issue by RustFisher** [tufu9441/maupassant-hexo#166]
使用系统：Win7 ，  Win10   
浏览器：Firefox ， Edge

你好，
        对于大屏幕显示器来说，页面居中显示在浏览器，两边留白了很大一片。
        我想问能否让页面宽一些，不要那么大片的空白。请问这个宽度能否自定义？改变浏览器宽度发现，应该是限定了最大宽度。我能自定义这个最大宽度吗？

谢谢！

**Comment by tufu9441** [comment]
可以，在style.scss中修改body_container的max-width即可。

**Comment by RustFisher** [comment]
OK  非常感谢
