### ISSUE TITLE
页面加载顺序问题

### ISSUE THREAD

**Issue by JayceCao** [tufu9441/maupassant-hexo#167]
我的博客使用的是disqus评论系统，并且开启了友情链接插件。我发现disqus的js脚本是放在友情链接div的前面的！希望能调整一下顺序。

**Comment by tufu9441** [comment]
disqus的代码不像多说一样在最后加载一段就可以，只要是需要用到的时候就会调用特定的脚本，例如在显示最近评论、评论数量时。

**Comment by RustFisher** [comment]
好的，谢谢

**Comment by JayceCao** [comment]
就不能放在整个页面最后么，不然会影响剩余部分页面的加载啊。
