### ISSUE TITLE
关于这个主体下的代码高亮显示

### ISSUE THREAD

**Issue by lynchlee** [tufu9441/maupassant-hexo#17]
这个主体换上以后, 代码高亮问题不太好. 北京是黑色的. 而且每种语言显示的都一样. 这个有解决方案么?

**Comment by tufu9441** [comment]
现在是浅色背景的代码高亮。

On 周六, 12月 5, 2015 at 20:26, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
这个主体换上以后, 代码高亮问题不太好. 北京是黑色的. 而且每种语言显示的都一样. 这个有解决方案么?

**Comment by tufu9441** [comment]
现在是浅色背景的代码高亮主题，是从[NexT主题](https://github.com/iissnan/hexo-theme-next)移植过来的，配色是它的Normal风格。

**Comment by lynchlee** [comment]
有升级计划么? 比如说代码高亮才有github风格?

**Comment by tufu9441** [comment]
目前就这一个主题。没明白你说的是什么意思？

**Comment by lynchlee** [comment]
就是这个代码高亮这块儿改造一些, 代码高亮风格改成github上显示代码这样.

**Comment by tufu9441** [comment]
我也发现目前好像有点问题，打算完善一下，只是目前还没找到好的办法，因为是直接从别处搬过来的CSS，可能不太兼容。

**Comment by lynchlee** [comment]
恩. 我对css不太熟悉. 倒是自己试着改过一点, 但是效果很不理想. 工作一忙, 就没时间弄了.  +_+

**Comment by tufu9441** [comment]
我又仔细对照了一下，目前的效果应该是完全重现[NexT主题中](https://github.com/iissnan/hexo-theme-next/blob/28d0283e36d56b4d37839aca4633ab3537ffa83d/source/css/_common/_vendor/highlight/highlight.styl)的[normal风格](https://github.com/iissnan/hexo-theme-next/blob/d6d011e1f00a7fcd50f6bc087fe95066bcc45e38/source/css/_common/_vendor/highlight/theme.styl)的，也就是通常所说的[tomorrow-theme](https://github.com/chriskempson/tomorrow-theme)，并且绝大多数主题的highlight部分都是这么写的，要实现不同的样式只是配色的问题，但是对于不同语言的识别应该是Hexo的问题，跟主题无关。

**Comment by lynchlee** [comment]
OK. 多谢. 配色的问题我调调. 还有一个请教的就是 比如说我写的markdown是这个样子

  ```java
  $ git clone git@github.com:OpenTSDB/opentsdb.git
  $ cd opentsdb
  ```
然后编译出来以后html是这个样子
<figure class="highlight java">
<table>
  <tr>
<td class="code">
 <pre>
<span class="line">$ git clone git
 <span class="annotation">@github</span>.com:OpenTSDB/opentsdb.git</span>
<span class="line">$ cd opentsdb</span>
 </pre>
</td>
  </tr>
</table>
</figure>
显示是这样子:

                            $ git clone git
                              @github.com:OpenTSDB/opentsdb.git
                            $ cd opentsdb


能我看下这个问题是为什么么?


-------------------------------------
Email : Lynch.lee9527@gmail.com
WeChat : Lynch221

2015-12-06 15:52 GMT+08:00 tufu9441 <notifications@github.com>:

**Comment by tufu9441** [comment]
你不用写明java，在hexo的_config.yml中设置auto_detect就可以了，例如：
```
highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace:
```

**Comment by lynchlee** [comment]
还是有个问题. 解析成
<pre>
<code>$ git clone git@github
  <span class="class">.com</span>:OpenTSDB/opentsdb
  <span class="class">.git</span>
  $ cd opentsdb
</code>
</pre>
这样子了.

**Comment by tufu9441** [comment]
我本地测试了一下没问题啊，如图所示：

![ScreenCapture at Sun Dec 6 17:06:19 CST 2015.png](https://ooo.0o0.ooo/2015/12/06/5663fb11f3bfe.png)

我的Markdown是这么写的：

![ScreenCapture at Sun Dec 6 17:08:07 CST 2015.png](https://ooo.0o0.ooo/2015/12/06/5663fb522e0c9.png)

**Comment by lynchlee** [comment]
我这边还是不行. 会不会和我的node版本有关?

**Comment by lynchlee** [comment]
在hexo admin下编辑和预览都没啥问题, 发布访问就不行了.

**Comment by tufu9441** [comment]
我也不知道了。我的Hexo版本是3.1.1。

On 周日, 12月 6, 2015 at 17:13, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
我这边还是不行. 会不会和我的node版本有关?

—
Reply to this email directly or view it on GitHub
[https://github.com/tufu9441/maupassant-hexo/issues/17#issuecomment-162290342] .[https://github.com/notifications/beacon/AGec2W438U7X2dGRXJr1lCzdH_AENKXVks5pM_O0gaJpZM4Gvao4.gif]

**Comment by tufu9441** [comment]
hexo-admin不调用主题配置的，跟它没关系。你自己改过主题的代码没？改过的话很可能是某些地方改坏了。你试一下最新的版本。

**Comment by lynchlee** [comment]
恩 倒是没改过主题. 之前用过一些别的主题, 然后切过来的, 可能是环境问题吧.  我重新把跟目录init后重新配了主题, 现在正常了. 多谢~~
