### ISSUE TITLE
百度统计怎样获取跟踪ID

### ISSUE THREAD

**Issue by oec2003** [tufu9441/maupassant-hexo#170]
在百度统计中添加了网站，只看到了代码获取，没有找到跟踪ID，请问跟踪ID怎么获取？

谢谢！

**Comment by oec2003** [comment]
找到跟踪ID，就是获取到代码后面的id，如下图红框部分
![](http://oec2003.qiniudn.com/Snip20160915_27.png)

**Comment by senjoeson** [comment]
我怎么感觉设置了百度ID也是无效的？ 一直提示没有检查出集成上去了？
