### ISSUE TITLE
侧边栏跑下面去了

### ISSUE THREAD

**Issue by Rememberli** [tufu9441/maupassant-hexo#176]
排版错误，侧边栏跑下面去了，不知道什么问题。

nodejs 6.7.0
hexo 3.2.2

**Comment by tufu9441** [comment]
问题是否依然存在？按理说只有当`_config.yml`中的`widgets_on_small_screens`这一项设置为`true`时，并且在小屏幕设备上侧边栏才会显示在下面。有可能是你的css没有加载正确。

**Comment by Rememberli** [comment]
我又试了一下，ie11 可以， firefox 45.4 chromium 52 chrome 55 都不行，打开隐私窗口(全部扩展禁用)也不行, firefox 试了安全启动不行，全部挂全局翻墙，widgets_on_small_screens 设成on,off ，都试了还不行哇。

**Comment by tufu9441** [comment]
这么神奇？本地测试情况如何？或者你重新clone一下主题试试。

**Comment by cxgreat2014** [comment]
的确如此，我在修改模板index.jade的取预览逻辑时也遇到这个问题，54.0.2840.99 m (64-bit)

**Comment by Rememberli** [comment]
clone主题状况一样，本地开hexo server 就正常，好奇怪。

**Comment by tufu9441** [comment]
@Rememberli 你的博客部署在哪里，会不会是从服务器端载入CSS的话会出错？你用Chrome的控制台看看。

**Comment by Rememberli** [comment]
@tufu9441 

咳，明白了，我的nginx 的CSP规则阻止了加载服务端css。

> Refused to load the stylesheet 'https://cdn.bootcss.com/pure/0.6.0/pure-min.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'".

**Comment by tufu9441** [comment]
好吧……

**Comment by Rememberli** [comment]
就是这个规则，注释掉就好了。我查一下要怎么修改一下才不影响

`add_header Content-Security-Policy "default-src 'self';script-src 'self' 'unsafe-inline' 'unsafe-eval' https://a.disquscdn.com;img-src 'self' data: https://www.google-analytics.com;style-src 'self' 'unsafe-inline';frame-src https://disqus.com";`

**Comment by troychn** [comment]
首页我分了页，第一页，侧边栏跑下面去了，第二页，侧边栏就显示正常了，其它页面也显示正常，就是第一页，不正常，我在本地测试的这种情况
@tufu9441 @cxgreat2014   有没有啥解决办法。
