### ISSUE TITLE
开启评论后，样式错乱

### ISSUE THREAD

**Issue by mymang** [tufu9441/maupassant-hexo#178]
将duoshuo功能开启，ID设置好后依次执行

> hexo clean
> hexo g
> hexo s
> 结果评论的样式没有出现，连带分享功能都显示异常了。把duoshuo看关闭后，重新清除再生成，样式又是正常的。

**Comment by raidyue** [comment]
我也遇到了同样的问题

**Comment by mymang** [comment]
一个不知道是不是正确的解决方案，反正现在就是能用了。
`duoshuo: ## Your duoshuo_shortname, e.g. username`
这里的值，我没有改成了true，而不是用户名，用户名在多说的官网那边配置了一下。现在我的配置是
`duoshuo: true`

**Comment by tufu9441** [comment]
应该填的是shortname，不是用户名。

**Comment by gourdbaby** [comment]
解决办法：将你shortname填到duoshuo:  注意：不可以是中文
