### ISSUE TITLE
Turn off abstract/description mode

### ISSUE THREAD

**Issue by daiyitastic** [tufu9441/maupassant-hexo#183]
I'd like to be able to show the full text of posts on the root page rather than summaries. Is there a good way to do this aside from inserting `<!--more-->` at the end of each post?

**Comment by tufu9441** [comment]
I am sorry that  the theme will auto excerpt the post to generate an abstract in the index for aesthetic considerations, so there is not a good way to disable this function if you want to show the full text.

**Comment by daiyitastic** [comment]
mind if I throw in a PR with a config option to show full text?

**Comment by tufu9441** [comment]
Of course welcome
