### ISSUE TITLE
你好，请教下文章摘要的问题

### ISSUE THREAD

**Issue by lijunnancc** [tufu9441/maupassant-hexo#184]
文章摘要默认第一段。能告诉我代码哪里找吗?我想修改成每篇文章相同。谢谢！

**Comment by tufu9441** [comment]
layout/index.jade

**Comment by tufu9441** [comment]
另外你可以通过填写`front-matter`中的`description`字段，或者插入`<!--more-->`来实现每篇文章摘要内容的控制。
