### ISSUE TITLE
刚pull了个requests，看下可以通过吗？

### ISSUE THREAD

**Issue by cxgreat2014** [tufu9441/maupassant-hexo#186]
以及。。为啥那里还有好几个好久之前的requests没处理？

**Comment by tufu9441** [comment]
因为之前那几个pr添加的功能我认为比较个性化，不够普适，或者不太适合这个简洁的模板，所以没有合并。
On 周日, 11月 13, 2016 at 11:34, cxgreat2014 <notifications@github.com> wrote:
以及。。为啥那里还有好几个好久之前的requests没处理？

**Comment by tufu9441** [comment]
Merged.
