### ISSUE TITLE
不想生成摘要，如何去除。

### ISSUE THREAD

**Issue by solverpeng** [tufu9441/maupassant-hexo#188]
@tufu9441 tufu，您好，我不想生成摘要，如何去除呢？谢谢

**Comment by tufu9441** [comment]
意思是想直接显示全文？那把<!--more>标记插入到文末。

**Comment by solverpeng** [comment]
不是，我只想显示标题。不想要摘要。 @tufu9441

**Comment by tufu9441** [comment]
那就将<!--more>标记插入到文章开头吧……

**Comment by maxioptty** [comment]
> 那就将<!--more>标记插入到文章开头吧……

我刚刚试过了，没用，还是显示全文。。
