### ISSUE TITLE
多说和disqus 能否改成点击再加载？

### ISSUE THREAD

**Issue by Remonli** [tufu9441/maupassant-hexo#189]
disqus最近越发慢了，是不是可以考虑改成异步加载？

多说有文档在这：
http://dev.duoshuo.com/docs/50b344447f32d30066000147

有位仁兄甚至异步了两个评论系统
http://dlyang.me/two-comment-plugins/

**Comment by tufu9441** [comment]
Disqus在部分地区被墙了所以慢。如果个人需要，可自行修改。
