### ISSUE TITLE
如何支持InstantClick

### ISSUE THREAD

**Issue by ijustyce** [tufu9441/maupassant-hexo#190]
我添加了InstantClick支持，在after_footer.jade的末尾加入：
`script(type='text/javascript', src=url_for(theme.js) + '/instantclick.min.js' + '?v=' + theme.version, data-no-instant)
script(data-no-instant).
  InstantClick.init();`
可是发现多说不工作了。

**Comment by tufu9441** [comment]
以前了解过InstantClick，个人认为对于这种本来就很简单的模板速度提升并不明显，反而徒增JS累赘，所以没考虑弄过。给你找了一篇文章：http://munen.cc/tech/InstantClick.html
