### ISSUE TITLE
分享功能有问题

### ISSUE THREAD

**Issue by gzponline** [tufu9441/maupassant-hexo#191]
![image](https://cloud.githubusercontent.com/assets/12186221/20270129/cfeed630-aac0-11e6-900b-b6b27d708c77.png)
为什么会绑定在这个网址上  是我配置的问题吗 怎么修改成当前文章的网址

**Comment by tufu9441** [comment]
你自己配置的问题。

On 周一, 11月 14, 2016 at 23:20, 外城士心月月鸟 <notifications@github.com> wrote:
[https://cloud.githubusercontent.com/assets/12186221/20270129/cfeed630-aac0-11e6-900b-b6b27d708c77.png]
为什么会绑定在这个网址上 是我配置的问题吗

**Comment by tufu9441** [comment]
#157
