### ISSUE TITLE
WARN  No layout: index.html

### ISSUE THREAD

**Issue by liangpu597** [tufu9441/maupassant-hexo#194]
您好，我clone了您的模板，安装好后。什么也没改。
直接:hexo clean hexo g 
hexo server 时出现：WARN  No layout: index.html
打开http://localhost:4000/ 也是空白。
请问，这是什么情况？
谢谢！

**Comment by tufu9441** [comment]
可能是`hexo-renderer-jade`或者`hexo-renderer-sass`这两个依赖的插件没有装好。换源重新安装试试。

**Comment by liangpu597** [comment]
上面两个已经成功安装了。

2016-11-25 10:58 GMT+08:00 tufu9441 <notifications@github.com>:

**Comment by tufu9441** [comment]
有可能是安装不完全。那只能重新安装Hexo试试了……

**Comment by liangpu597** [comment]
是这样的，我先前一个主题运行正常。上面连个插件已经安装了。
我想应该不是那个原因吧。

2016-11-25 11:04 GMT+08:00 tufu9441 <notifications@github.com>:

**Comment by tufu9441** [comment]
那我也不知道什么原因了，先前没有类似的案例……

**Comment by liangpu597** [comment]
哦，好吧。谢谢了哈！

2016-11-25 11:07 GMT+08:00 tufu9441 <notifications@github.com>:

**Comment by webfrontzhifei** [comment]
在配置文件中theme指定为maupassant-hexo，注意不是maupassant

**Comment by tufu9441** [comment]
就是取决于你的主题文件夹在theme文件夹下的名字存的是什么。

On 周三, 11月 30, 2016 at 00:46, webfrontzhifei <notifications@github.com> wrote:
在配置文件中theme指定为maupassant-hexo，注意不是maupassant

**Comment by anson2416** [comment]
我也遇到这样的问题。

**Comment by anson2416** [comment]
我也遇到这样的问题。建议添加说明在主页。
