### ISSUE TITLE
不能使用啊！

### ISSUE THREAD

**Issue by zhaoweiwang** [tufu9441/maupassant-hexo#2]
![qq 20151025192721](https://cloud.githubusercontent.com/assets/4099495/10715338/811816b8-7b4e-11e5-914c-99df1a5dbd70.png)

**Comment by zhaoweiwang** [comment]
path 没有定义？

**Comment by tufu9441** [comment]
@zhaoweiwang 那个路径是rss的，安装一下hexo-generator-feed插件并在hexo的config里配置一下RSS地址：
![screencapture at sun oct 25 19 30 32 cst 2015](https://cloud.githubusercontent.com/assets/6790361/10715348/ea4cdbd2-7b4e-11e5-9a55-343e439c4fa4.png)

**Comment by zhaoweiwang** [comment]
刚才直接把rss去掉了，简单粗暴。刚好一直以来觉得RSS用的人少，一直都不会加这个，显得累赘。
话说仓主，这个主题我以前在wordpress用的，弄成github pages麻烦吗

**Comment by tufu9441** [comment]
@zhaoweiwang 我也不好说，你先了解一下Hexo怎么用吧。

**Comment by zhaoweiwang** [comment]
我的问题是这主题原本不是Wordpress下的吗，难不成你把源码就直接拿过来就能使了....肯定需要重构吧

**Comment by zhaoweiwang** [comment]
刚换上了，不过看得出来还有很多不足之处。github能私信吗，可以的话，加个QQ，方便反馈给你

**Comment by tufu9441** [comment]
@zhaoweiwang 那肯定不是啊，不是我最先迁过来的，先是原作者[Cho](https://github.com/pagecho)自己做了基于jade的[Farbox](https://github.com/pagecho/Maupassant-farbox/)的版本，然后[icylogic](https://github.com/icylogic/maupassant-hexo)最先移植到了hexo，我在icylogic版本的基础上做了完善。

**Comment by micookie** [comment]
楼主免费发了一个馒头，路人甲拿了一个，吃完噎着了。。回去骂楼主。。。

馒头不好可以提出意见，何必……

**Comment by zhaoweiwang** [comment]
@micookie 你哪只眼睛看到骂楼主了。而且我说过馒头不好了吗？

**Comment by tufu9441** [comment]
@micookie 哈哈，要不要这么犀利，不过我没能耐心跟人解释文档确实是我的不好。

**Comment by zhaoweiwang** [comment]
@tufu9441 一事说一事而已。这个模板还是很讨喜。：）
