### ISSUE TITLE
Gists are not properly rendered

### ISSUE THREAD

**Issue by okelet** [tufu9441/maupassant-hexo#20]
How it looks right now:

![seleccion_002](https://cloud.githubusercontent.com/assets/108803/11696401/566fff00-9eb4-11e5-9d3f-3b31a4731375.png)

And how it should look:

https://gist.github.com/gojun077/cd7eb3587b1dd803dc29#file-brainworkshop_updatelabel-pyw

**Comment by tufu9441** [comment]
I have fixed it, and you can have a try.

**Comment by okelet** [comment]
Thanks, gists show fine now, but normal code blocks don't use fixed width fonts:

![seleccion_002](https://cloud.githubusercontent.com/assets/108803/11724079/2c7883f2-9f72-11e5-9b08-d1117d8cd1dd.png)

**Comment by tufu9441** [comment]
Sorry I cannot understand what do you mean by fixed width fonts? Is it syntax
highlighting style?

On 周五, 12月 11, 2015 at 02:14, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
Thanks, gists show fine now, but normal code blocks don't use fixed width fonts:

seleccion_002
[https://cloud.githubusercontent.com/assets/108803/11724079/2c7883f2-9f72-11e5-9b08-d1117d8cd1dd.png]
[https://cloud.githubusercontent.com/assets/108803/11724079/2c7883f2-9f72-11e5-9b08-d1117d8cd1dd.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/tufu9441/maupassant-hexo/issues/20#issuecomment-163706814] .[https://github.com/notifications/beacon/AGec2WUsKPpJQrAnewL9cLmuLSIguC-Kks5pObiUgaJpZM4GyJk3.gif]

**Comment by okelet** [comment]
Hi, yes, I mean syntax highlighting. In these blocks, the font should be someone like Courier (fixed width, like in the terminal). Mind the difference with the font with in these 2 code blocks:

[https://cloud.githubusercontent.com/assets/108803/11724079/2c7883f2-9f72-11e5-9b08-d1117d8cd1dd.png]

https://gist.github.com/gojun077/cd7eb3587b1dd803dc29#file-brainworkshop_updatelabel-pyw

**Comment by tufu9441** [comment]
I have no idea why it looks like this, I just imported the syntax highlighting styles from [tranquilpeak-hexo-theme](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme), note that the font-family in it is Menlo. You can check a post in my blog to view the effect of code blocks [here](https://www.haomwei.com/technology/fork-me-on-github.html), and I think it looks normal.
