### ISSUE TITLE
google-site-verification 被赋值

### ISSUE THREAD

**Issue by zrt** [tufu9441/maupassant-hexo#201]
base-without-sidebar.jade
里有
meta(name='google-site-verification' content='6GTeiOhqimfTtuUIQtS8CqdXJzM4lPPMeXjbvNAsm5w')

[https://github.com/tufu9441/maupassant-hexo/blob/master/layout/base-without-sidebar.jade#L25](https://github.com/tufu9441/maupassant-hexo/blob/master/layout/base-without-sidebar.jade#L25)

**Comment by tufu9441** [comment]
忘了更新，已修复。
