### ISSUE TITLE
在markdown的引用（quote）中添加代码块显示不正常

### ISSUE THREAD

**Issue by skywalker0507** [tufu9441/maupassant-hexo#205]
你好，我在markdown的引用（quote）中添加代码块，结果生成的结果显示不正常。
相关代码如下：
``` markdown
> The lisp snippets for installing el-get download the full el-get installer via https, eg the "lazy installer":
>
> ```lisp
>  (url-retrieve
>   "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el"
>   (lambda (s)
>     (goto-char (point-max))
>     (eval-print-last-sexp)))
> ```
>
> but Emacs doesn't support https out of the box on Windows. As mentioned here, the needed dlls can be retrieved from http://sourceforge.net/projects/ezwinports/files/.
>
>  Extract the dlls in bin from gnutls-3.0.9-w32-bin.zip into Emacs' bin/
>
>  but not the .exe files, otherwise you might hit emacs bug 15905.
>
>  You will need to restart Emacs so it can notice the new dlls.
>
```
markdown渲染的结果如下

> The lisp snippets for installing el-get download the full el-get installer via https, eg the "lazy installer":
>
> ```lisp
>  (url-retrieve
>   "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el"
>   (lambda (s)
>     (goto-char (point-max))
>     (eval-print-last-sexp)))
> ```
>
> but Emacs doesn't support https out of the box on Windows. As mentioned here, the needed dlls can be retrieved from http://sourceforge.net/projects/ezwinports/files/.
>
>  Extract the dlls in bin from gnutls-3.0.9-w32-bin.zip into Emacs' bin/
>
>  but not the .exe files, otherwise you might hit emacs bug 15905.
>
>  You will need to restart Emacs so it can notice the new dlls.
>

但是生成页面后显示不正常

**Comment by tufu9441** [comment]
怎么个不正常法？提供一下截图。

**Comment by skywalker0507** [comment]
![p](https://cloud.githubusercontent.com/assets/9379578/21445105/ee1d9a5e-c8ef-11e6-9ce3-4ea77fe15158.png)
如图所示，代码块和下面的文字在一个引用块中，但是这里被分割成了两部分；引用块里的的代码块中显示了引用符号。

**Comment by tufu9441** [comment]
我自己测试了一下，你把代码块结尾的3个反引号跟下面一行but emacs之间的那一行空行删掉就正常了。或者，你可以使用Hexo官网上给出的另一种插入代码块的语法，见：https://hexo.io/zh-cn/docs/tag-plugins.html#样例-1

也就是使用`{% codeblock %}`和`{% endcodeblock %}`来包围代码块。

这应该不是主题的问题。
