### ISSUE TITLE
Render速度非常慢

### ISSUE THREAD

**Issue by zklhp** [tufu9441/maupassant-hexo#211]
在我这里大约4页/秒。之前用的主题都不是这种速度。请问，可能的原因为何，如何诊断？

谢谢。

`hexo g --debug`的部分输出如下：

> 15:20:57.781 DEBUG Rendering page: baidu_verify_QGlyQmchVi.html
15:20:58.107 DEBUG Rendering page: googlebb0ad4f15a051526.html
15:20:58.410 DEBUG Rendering page: emacs-w64/index.html
15:20:58.707 DEBUG Rendering page: emacs-beginner-guide/index.html
15:20:58.997 DEBUG Rendering page: essentials-of-academic-writing/index.html
15:20:59.288 DEBUG Rendering page: pua/index.html
15:20:59.581 DEBUG Rendering post: 2016/12/31/Happy-New-Year/index.html
15:20:59.874 DEBUG Rendering post: 2016/12/30/True-guru/index.html
15:21:00.168 DEBUG Rendering post: 2016/12/22/Solving-SCF-creep-in-QM-calculation-of-metal-complexes-and-the-efficacy-of-itopride-hydrochloride/index.html
15:21:00.463 DEBUG Rendering post: 2016/12/14/How-to-clear-the-sewer/index.html
15:21:00.755 DEBUG Rendering post: 2016/12/04/No-more-arbitrary-names/index.html
15:21:01.045 DEBUG Rendering post: 2016/12/04/I-am-a-Mi-fan/index.html
15:21:01.334 DEBUG Rendering post: 2016/12/01/nodejs-anywhere/index.html
15:21:01.629 DEBUG Rendering post: 2016/11/21/Remove-download-restrict-in-Baidu-Pan/index.html
15:21:01.922 DEBUG Rendering post: 2016/11/09/Story-on-US-election/index.html
15:21:02.213 DEBUG Rendering post: 2016/11/06/Grammarly-review/index.html

`npm list --depth=0`输出如下：
> hexo-site@0.0.0 c:\msys64\home\Kel\repo\hexo-blog
+-- hexo@3.2.2
+-- hexo-deployer-rsync@0.1.2
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.0
+-- hexo-generator-search@1.0.3
+-- hexo-generator-seo-friendly-sitemap@0.0.20
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-jade@0.3.0
+-- hexo-renderer-markdown-it@3.4.1
+-- hexo-renderer-sass@0.2.0
+-- hexo-server@0.2.0
+-- markdown-it-abbr@1.0.4
+-- markdown-it-checkbox@1.1.0
+-- markdown-it-footnote@3.0.1
+-- markdown-it-ins@2.0.0
+-- markdown-it-sub@1.0.0
`-- markdown-it-sup@1.0.0

`hexo version`输出如下：
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 6.3.9600 win32 x64
http_parser: 2.7.0
node: 7.3.0
v8: 5.4.500.45
uv: 1.10.1
zlib: 1.2.8
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2j
icu: 58.1
unicode: 9.0
cldr: 30.0.2
tz: 2016g

**Comment by tufu9441** [comment]
这个我以前有一段时间好像也遇到过，后来更新了Hexo之后不知不觉就消失了。不知道是不是你的某个插件影响了渲染速度？

**Comment by zklhp** [comment]
谢谢您的回复:cry:我今天折腾一天了，感觉都要放弃了，找到了原因：https://github.com/hexojs/hexo/issues/1769

参考里面的解决方案，注释掉`_config.yml`里`widgets:`中的`- tag`，速度就恢复正常了。

**Comment by zklhp** [comment]
我修改了一下代码：https://github.com/tufu9441/maupassant-hexo/pull/213

再次感谢您带给我们优秀的主题。祝您新年愉快:joy:
