### ISSUE TITLE
能否增加首页中文章之间的间隔标记？

### ISSUE THREAD

**Issue by Mlearn** [tufu9441/maupassant-hexo#212]
有办法增加首页中的文章列表之间的间隔标记吗？比如说一条横线，或者设置标题的颜色或者背景。
因为，有时候一篇文章中的第一段中如果含有章节标题，在首页预览中的文章标题与章节标题的辨识度比较低。

**Comment by tufu9441** [comment]
个人认为加上一条横线后的显示效果并不美观，对于你说的这种特殊情况，可以通过自己设置文章摘要的显示内容来避免，即文章`front-matter`中的`description`字段。

**Comment by formath** [comment]
我也觉得文章间加个虚化的分隔符会更清晰一点
