### ISSUE TITLE
html的代码高亮显示问题

### ISSUE THREAD

**Issue by lupanpan** [tufu9441/maupassant-hexo#215]
html的代码显示没有高亮

我写的是这样的

```HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <header>
    <nav></nav>
  </header>
  <main>
    <aside></aside>
    <article>
      <section></section>
      <section></section>
      <section></section>
    </article>
  </main>
  <footer></footer>
</body>
</html>
```

显示的是下边这种，没有高亮
<img width="754" alt="2017-02-05 11 06 34" src="https://cloud.githubusercontent.com/assets/17155291/22623364/4ae4b766-eb93-11e6-9614-59e07ebd9b24.png">

我在配置中也修改了这部分了
highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace:

**Comment by tufu9441** [comment]
插入html代码的时候，在代码块之前插入“```xml”，而不是html，或者只留3个反引号让它自动判断。
