### ISSUE TITLE
self_search 无法正确执行

### ISSUE THREAD

**Issue by noparkinghere** [tufu9441/maupassant-hexo#217]
self_search 调用成功了，且能够显示搜索结果，但打开的链接不对，会跳转到 http://ww38.yoursite.com/2017/01/25/2017/xx 网址，难道这个服务需要付费才能使用？！

**Comment by tufu9441** [comment]
Hexo根目录下的_config.yml中的url是否已经设置成了自己的网址？默认就是yourtsite.com

**Comment by noparkinghere** [comment]
好的谢谢了，发现了问题了，大概是我后来重建了项目，原来的内容忘记改了，以为在主题中，用grep搜了好几次没搜到。
