### ISSUE TITLE
关于多说的评论问题

### ISSUE THREAD

**Issue by CevinJohnny77** [tufu9441/maupassant-hexo#218]
你好：
	
	关于Hexo主题中的文章留言问题：

	1、在主题的_config文件中已经开启了多——duoshuo: cevinjohnny## Your duoshuo_shortname, e.g. username
	可是为什么显示的确实这样呢？
        · 分享到：
        · 微博
        · QQ空间
        · 腾讯视频
	且在front-matter中设置comments: true或comments: false来进行开启或关闭并没有效果呢...
	是不是引擎comments引擎不太对呢？

**Comment by SeisPider** [comment]
可能是您的多说账号没有在多说网站上登陆造成的。

**Comment by CevinJohnny77** [comment]
多说账号是登录了的，还在其他blog上面用多说账号留言来着，应该不是这个问题...

**Comment by tufu9441** [comment]
一般出现这个情况都是连接不上多说的服务器导致的：
![](http://i.imgur.com/nvNcWoP.jpg)

**Comment by wpcapaper** [comment]
你在##前面少打了个空格的样子
