### ISSUE TITLE
我仿照大大的代码在侧边栏插件搞了个背景音乐

### ISSUE THREAD

**Issue by yfshare** [tufu9441/maupassant-hexo#219]
今天我Hexo+GitHub+maupassant正式上线啦，欢迎大家来访，里面有我这几天折腾搭建Hexo的文档，已经分享
地址：[www.yfshare.vip](http://www.yfshare.vip)

这是我参考大大的代码搞的一个背景音乐功能，教程在[这里](http://www.yfshare.vip/2017/02/16/Hexo-maupassant主题音乐小工具/)，因为我完全不会JS脚本，所以只能搞到这里了

现在还有几点不足：  
- 打开文档或点下一页后，音乐又开始重新播放了  
- 手机访问也会播放背景音乐，不能智能识别  

请原谅我，我完全不懂代码，无力解决，求大大帮忙

请允许我小小的做个广告，嘿嘿，推广下我[博客](http://www.yfshare.vip)

**Comment by xiedeliang** [comment]
你好，我这边引用这个样式的时候 渲染出来以后样式都乱了 能给我指教一下么 ？

**Comment by yfshare** [comment]
我有写教程的，教程地址：[Hexo-maupassant主题音乐小工具](http://www.yfshare.vip/2017/02/16/Hexo-maupassant主题音乐小工具/)
