### ISSUE TITLE
请问maupassant打赏功能怎么弄？

### ISSUE THREAD

**Issue by yfshare** [tufu9441/maupassant-hexo#220]
请问maupassant打赏功能怎么弄？

按照这个我没做出来https://qifuguang.me/2016/08/14/如何为博客增加打赏功能/

**Comment by tufu9441** [comment]
个人并不喜欢给主题添加这些无关紧要的功能。你可以照着这个PR自己改：https://github.com/tufu9441/maupassant-hexo/pull/144

**Comment by yfshare** [comment]
@tufu9441 唉。我按照这个没整出来，不晓得哪出问题了。我不懂代码，照搬要么hexo g报错，要么没效果
