### ISSUE TITLE
安装hexo-renderer-sass最终解决方案，望能pull requests，到wiki中

### ISSUE THREAD

**Issue by bequt** [tufu9441/maupassant-hexo#225]
hexo-renderer-sass 应该是不依赖python、ruby的，测试机子为全新windows server 2008服务器，网络估计是电信，若您有联通或移动也望能测试一下，只需要添加进cnpm和修改npm就可以实现。
### 安装好node.js 和 git-scm 在里面敲打下面代码回车就可以了
- ```npm install -g cnpm --registry=https://registry.npm.taobao.org```  目的是改用cnpm来安装软件
- ```npm config set registry https://registry.npm.taobao.org```  目的是直接改npm为淘宝的npm，也为防止某些依赖直接用npm来安装，导致无法顺利安装完成。

#### 最后在安装各种hexo插件时候，请直接使用 ```cnpm``` 命令
最后希望作者能够在此项目上添加上wiki，非常感谢作者分享这款主题，thanks

**Comment by tufu9441** [comment]
感谢您的经验分享！

**Comment by wpcapaper** [comment]
感谢大大的经验分享 帮助很大

**Comment by Droid43** [comment]
下载失败的话有个终极解决办法，直接打开链接https://github.com/sass/node-sass/releases/download/v4.5.0/darwin-x64-48_binding.node，把文件下载到本地
新建文件夹v4.5.0（不同版本应该不一样）
如：Users/Downloads/v4.5.0/darwin-x64-48_binding.node
然后执行
npm install node-sass --save-dev --sass-binary-site=file:///Users/Downloads --registry=https://registry.npm.taobao.org

**Comment by spkingr** [comment]
太感谢了！！@bequt
$ npm install --save hexo-renderer-scss 完美安装解决！

**Comment by dingchaofa** [comment]
npm install --save hexo-renderer-scss  不要镜像，开代理

**Comment by Nocturner** [comment]
@Droid43 谢谢，终于安装成功了，

**Comment by nonlau** [comment]
安装后，cnpm: command not found

**Comment by yin-n** [comment]
解决的终极办法 确实直接是下载到本地！
https://github.com/knksmith57/hexo-renderer-sass
把上面这个下载到本地再把hexo-render-sass拷贝到 node-modules文件下即可
