### ISSUE TITLE
请问你关于页面中内容的图标是如何载入fontawesome图标的?

### ISSUE THREAD

**Issue by bequt** [tufu9441/maupassant-hexo#227]
我翻你们的评论 虽然找到了你所说的那个解决方案的链接 但是文章已经删掉了 我现在完全没头绪 因为主要学习后端 前端知识太少了 希望能得到您的解答 谢谢

**Comment by tufu9441** [comment]
就按照fontawesome官网给出的调用格式即可：
![](https://dn-haomwei.qbox.me/images/124624.jpg)

**Comment by luffyke** [comment]
我的写法和效果：http://kexitang.me/about/
\---
output: 
  html_document: 
  css: https://use.fontawesome.com/releases/v5.0.2/css/all.css
  self_contained: no
\---
\## 关于我
\- <i class="fa fa-user-circle" aria-hidden="true"></i> NickName: luffyke
\- <i class="fa fa-github" aria-hidden="true"></i> Github: [luffyke](https://github.com/luffyke)
\- <i class="fa fa-weibo" aria-hidden="true"></i> Weibo: [luffyke](https://weibo.com/luffyke/home?topnav=1&wvr=5)
\- <i class="fa fa-twitter" aria-hidden="true"></i> Twitter: [beyondx_kxt](https://twitter.com/beyondx_kxt)
