### ISSUE TITLE
po 你的博客中归档页面是如何做到不分页的

### ISSUE THREAD

**Issue by Loyea** [tufu9441/maupassant-hexo#230]
如题

**Comment by funye** [comment]
layout文件夹下面的 archive.jade文件内容中底下的include _partial/paginator.jade 删掉试试，具体我没试过

**Comment by Loyea** [comment]
@funye  我试了，这个只是去掉了底下的页面按钮

**Comment by tufu9441** [comment]
根目录配置文件中archive_generator的per_page设置为0：
![](https://dn-haomwei.qbox.me/images/124315.jpg)

**Comment by Loyea** [comment]
@tufu9441 不胜感激！
