### ISSUE TITLE
在layout里面新创建一个.jade文件的问题

### ISSUE THREAD

**Issue by funye** [tufu9441/maupassant-hexo#232]
请问下，在layout里面创建一个页面之后，我在页面中使用page.posts或者page.categories 时候得到都是undefined，这个怎么处理下 ？ 想问问我怎么自己定义自己的layout ,然后和已经存在的layout一样使用page里面的一些变量

**Comment by tufu9441** [comment]
因为目前主题里并没有创建分类或者标签的页面layout。

**Comment by NathanJiang** [comment]
可以增加layout.jade，然后针对各个页面添加不同的layout入口。你可以参考我写的版本layout文件夹内的文件。

**Comment by NathanJiang** [comment]
hexo会首先读取layout.jade寻找渲染模板。所以可以增加layout.jade，然后针对各个页面添加不同的layout入口。你可以参考我写的版本layout文件夹内的文件。
@funye
