### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by vsxen** [tufu9441/maupassant-hexo#235]
1. post-title设置为 h1   (landscape 的就是这样)，或者说明一下在哪里设置？
2. tag 显示数目
3. 文章页面右半部分改为目录（single-column 貌似只是取消了右边不是很和谐 ）
4.会强制渲染.html文件
如果没时间的话，就回复一下第一个吧

**Comment by ysymi** [comment]
@vsxen

**Comment by vsxen** [comment]
@ysymi 谢谢

**Comment by tufu9441** [comment]
1、我自己试了一下，好像把那个line 13的h2改成h1以后没看出有什么变化啊？但我还是改过来了……
2、tags的数目自己简单改一下就能弄出来，个人觉得不美观，就没有搞；
3、这个目前还不会……
4、最好不要直接在source目录下放html页面吧，可以generate以后放在public目录。

**Comment by vsxen** [comment]
改完之后 审查元素出来的是h1 （但是好像真的没区别）
谢谢了 我自己折腾一下吧
