### ISSUE TITLE
使用百度搜索搜不到东西

### ISSUE THREAD

**Issue by 828768** [tufu9441/maupassant-hexo#236]
config.url中设置的[http://sobaigu.com](http://sobaigu.com),主题设置百度搜索为true时，搜不出任何东西，google没这问题，百度认为传进来的http非法，config.url中去掉协议就可以搜出来，但其他地方引用同样把协议去掉了，百度搜索这个地方是不是可以处理下？

**Comment by 828768** [comment]
多说自裁了，终于可以把多说下掉了，老大换网易云跟帖吧

**Comment by tufu9441** [comment]
已经添加了。

**Comment by tufu9441** [comment]
百度搜索的问题，我还不知道怎么能让它自己把前面的协议去掉，一个比较笨的办法是你在自己的`search.jade`中百度搜索的地方把`#{config.url}`换成你的域名……
