### ISSUE TITLE
新建一个index.html文件如何关闭评论

### ISSUE THREAD

**Issue by Defender20** [tufu9441/maupassant-hexo#237]
- 请问除了在帮助文档提供的.md中提到的关闭评论（comments:false）与布局（layout:single-colume）外，在html中如何做到同样的效果？
- 如果要在menu列表中添加新的page应该怎么做？
- 是否能够在搜索框做到对博客文章进行搜索？

**Comment by Defender20** [comment]
1.我想第一个问题可以先建立一个index.md(comments:false,layout:single-colume)的文件夹,生成html后再public里复制过来（此方法未经验证）

**Comment by tufu9441** [comment]
第二个问题在README部分也介绍了，建立包含`index.md`的相应文件夹，并在`_config.yml`中仿照已有页面格式添加。没看懂第三个问题什么意思。
