### ISSUE TITLE
主题安装渲染问题

### ISSUE THREAD

**Issue by pengyuan1990** [tufu9441/maupassant-hexo#238]
window 10
hexo 3
cnpm install hexo-renderer-jade --save
cnpm install hexo-renderer-sass --save
hexo server 本地测试，在渲染主题的时候报错了
Unhandled rejection TypeError: E:\test\themes\maupassant\layout\_partial\after_footer.jade:53
    51|      var path = '#{config.root}' + search_path;
    52|      searchFunc(path, 'local-search-input', 'local-search-result');
  > 53|
    54| if theme.google_analytics
    55|   script.
    56|     (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){

**Comment by tufu9441** [comment]
是 #202 中描述的问题么？
