### ISSUE TITLE
关于单栏页面

### ISSUE THREAD

**Issue by memory7734** [tufu9441/maupassant-hexo#240]
设置单栏页面的时候，在front-matter里面设置了layout: single-column，可是右边原来的搜索分类标签等功能所在的地方虽然不会显示了，但是左边的部分依旧只能占据左边部分，而不是在整个页面居中的位置

![issues](https://cloud.githubusercontent.com/assets/13341119/24151866/ecb01888-0e84-11e7-8827-676f417bc48c.jpg)

**Comment by tufu9441** [comment]
是的，目前单栏模式的策略就是仅仅隐藏侧边栏。

**Comment by tufu9441** [comment]
现在应该修复了。
