### ISSUE TITLE
关于多说停止服务

### ISSUE THREAD

**Issue by SpinyTech** [tufu9441/maupassant-hexo#242]
多说将在2017-6-1停止服务，请问关于多说这块可不可以增加一个替换方案，比如搜狐畅言或者友言。最近Disqus总是被墙，使用Disqus的话，面向国内用户的文章可能会刷不出评论。看了您的comments.jade和recent_comments.jade，但是我JS水平实在有限，没办法进行修改。

**Comment by tufu9441** [comment]
昨天已经添加友言了。

**Comment by SpinyTech** [comment]
实在不好意思，没有看代码就麻烦您。
