### ISSUE TITLE
使用Disqus，右侧栏”最近评论“无法显示。

### ISSUE THREAD

**Issue by shengdie** [tufu9441/maupassant-hexo#247]
多说要关了，刚转到Disqus，但是发现右侧栏的`最近评论`无法正常显示，希望能解决一下。

---

顺便说一下，主页显示的文章评论数也不正常，如果几篇文章都没有评论的话，有的显示`0 Comments`，有的什么都不显示。

**Comment by shengdie** [comment]
好像是因为disqus收集最近平论时间很长，隔了一天显示出了。

**Comment by canghaiwuhen** [comment]
需要翻墙
