### ISSUE TITLE
能否在toc中加一个选项控制目录数字是否显示?

### ISSUE THREAD

**Issue by Arvin-He** [tufu9441/maupassant-hexo#250]
我在文章的front-matter中加了toc: true选项后,生成的目录自带了目录数字序号,
而我写文章时喜欢自己在目录前加上数字序号,
这样自动生成目录数字序号和我自己写的目录数字序号重复了,
请问你能否做一个toc的选项,支持生成的目录数字序号可以不显示?
就像next主题那样:
toc:
  enable: true
  \# Automatically add list number to toc. 不自动显示目录数字序号
  number: false

**Comment by tufu9441** [comment]
已更新。

**Comment by Arvin-He** [comment]
Thanks a lot!
