### ISSUE TITLE
图片对齐问题

### ISSUE THREAD

**Issue by canghaiwuhen** [tufu9441/maupassant-hexo#252]
之前老版本的图片都是靠左对齐，更新之后，图片都变成居中对齐了，这个应该在哪调整？

**Comment by tufu9441** [comment]
故意调整成居中的，难道居中不好看吗？在style.scss中可以改

**Comment by canghaiwuhen** [comment]
不好啊，本来可以在文字中间插小图片的，居中后就不行了，比如这一页http://www.white-alone.com/GNURadio%E6%95%99%E7%A8%8B_1/

**Comment by canghaiwuhen** [comment]
能单独调整图片的么？改了半天没搞定。。。囧

**Comment by zerocc2017** [comment]
同觉得居中不好哈哈哈
