### ISSUE TITLE
云跟帖代码放到after_foot.jade里打开首页会有错误

### ISSUE THREAD

**Issue by 828768** [tufu9441/maupassant-hexo#253]
首页并没有云跟帖评论，打开首页的时候云跟帖的代码会报错，虽然不影响使用，还是要集成到comments里才好。
[Hexo博客集成云跟帖评论系统](http://sobaigu.com/hexo-comments-with-yungentie.html)

**Comment by tufu9441** [comment]
知道了，有空我去改过来，多谢！

**Comment by tufu9441** [comment]
Fixed
