### ISSUE TITLE
更新之后，出现首页样式错乱

### ISSUE THREAD

**Issue by thiswan** [tufu9441/maupassant-hexo#256]
首页布局出现错位现象，首页的右侧工具栏( 页面中的sidebar 元素)掉到了页面的最底部显示。正常的显示应该是在下图中标红的地方，其他页面的右侧工具栏显示是正常的。
首页显示错位效果如图：
![首页错乱](https://pub.int64ago.org/icqsukp.png)

**Comment by tufu9441** [comment]
是 #223 中描述的这种情况吗？你首页有几篇文章？
