### ISSUE TITLE
能否添加一个文件修改日期功能

### ISSUE THREAD

**Issue by 51lucky** [tufu9441/maupassant-hexo#257]
在文章标题下面文章生成日期旁边添加一个文章修改日期呢

**Comment by tufu9441** [comment]
我觉得影响美观，想加的话可以自己修改。

**Comment by 51lucky** [comment]
能否告诉我改那里呢？改那个文件

2017-04-14 16:14 GMT+08:00 tufu9441 <notifications@github.com>:

**Comment by 51lucky** [comment]
.post-meta= page.date.format('ll')
      span.updated= page.updated.format('ll')
      if page.categories.length > 0
        span= ' | '
        span.category
          for category in page.categories.toArray()
            a(href=url_for(category.path))= category.name

怎样判断updated这个是否有值呢？
1. 我抄写下面的  if page.updated.length > 0 没有效果
2，如果这样写if(updated != null || typeof updated != "undefined" || updated != ""
|| trim(updated) != "")
        span= ' | '
        span.updated= page.updated.format('ll')
那些文章没有updated的，会显示当前的日期

这点应该怎么修改呢？不好意识，不回js

**Comment by tufu9441** [comment]
抱歉这方面我也不太了解……

**Comment by 51lucky** [comment]
好吧，不过还是谢谢你

2017-04-14 18:14 GMT+08:00 tufu9441 <notifications@github.com>:
