### ISSUE TITLE
如何是maupassant的背景变成nest特效背景

### ISSUE THREAD

**Issue by zi-done** [tufu9441/maupassant-hexo#258]
nest特效背景的代码有，然后不知道怎么添加

**Comment by InvalidCode** [comment]
你可以选择在`layout/footer.jade`内添加`script(type="text/javascript",color="7,196,239",opacity='0.5',zIndex="-2",count="50",src="//cdn.bootcss.com/canvas-nest.js/1.0.1/canvas-nest.min.js")`，已经提交PR[#310](https://github.com/tufu9441/maupassant-hexo/pull/310)

**Comment by tufu9441** [comment]
已添加。
