### ISSUE TITLE
Make maupassant great again

### ISSUE THREAD

**Issue by DonQvixote** [tufu9441/maupassant-hexo#264]
### 移动设备优化
* 在主题配置文件`_config.yml`加入`make_maupassant_great_again`设置  
```
make_maupassant_great_again: true ## Set to true to use better experience on mobile devices.
```
* 移除顶部导航栏，取而代之的是右下角的`toggle_menu`  
在移动设备屏幕下，导航栏显示多个导航的时候会显得拥挤，样式也不好看，而且切换必须返回顶部，我便考虑响应式菜单的方式进行页面导航。最初考虑参考`ghost`平台上[ghostium](http://ghostium.oswaldoacauan.com)主题那种汉堡菜单，后又觉得与`maupassant`主题风格不符，于是作罢。由于本身在做iOS开发，所以最终参考客户端设计，在右下角加入悬定按钮弹出菜单。  
![顶部导航](http://ook6n3gr5.bkt.clouddn.com/top.jpg)  
![悬定按钮](http://ook6n3gr5.bkt.clouddn.com/floating_button.PNG) 
![弹出菜单](http://ook6n3gr5.bkt.clouddn.com/toggle-menu.PNG)
* post页面不显示顶部信息，使得每篇博客更加独立

### Disqus优化
Disqus在国内不是访问不稳定，就是直接被墙，所以加载经常超时。参考主题[material](https://github.com/viosey/hexo-theme-material)处理机制，利用ajax判定访问Disqus(实际上是https://disqus.com/favicon.ico) 是否超时，从而选择是直接加载Disqus评论，还是显示加载评论按钮。
![Disqus加载按钮](http://ook6n3gr5.bkt.clouddn.com/disqus_button.PNG)
*Read More*:可以利用[Disqus API](https://disqus.com/api/docs/)开发proxy加载模式,相关链接:
* https://gist.github.com/neoFelhz/d2e3de6e9b1c9cecf04d811f0994e6c4
* http://blog.fooleap.org/use-disqus-correctly.html
* https://blog.nfz.moe/archives/how-to-show-disqus-comment-in-gfw.html

### 分享优化
分享博客文章到微信生成二维码时会在浏览器打开新标签显示二维码，体验不佳，所以我将其改成就在按钮下面显示二维码
![微信分享二维码](http://ook6n3gr5.bkt.clouddn.com/wechat-qrcode.png)

### Google Analytics优化
为了便于Google抓取，将analytics.js的引用改到head标签下

### 引用改动
变回`Markdown`默认的引用风格

### 其他
部分FontAwesome图标如文章时间、标签、阅读次数等修改
部分文本如阅读和footer等修改
部分按钮css修改

由于很多是个人修改，所以并未提交PR，不知道各位觉得是否有可取之处，欢迎大家留言评论或到[我的fork](https://github.com/DonQvixote/maupassant-hexo)上交流

**Comment by tufu9441** [comment]
我觉得你这些优化都挺不错的，感谢您的贡献！欢迎提交PR，我可以根据实际情况尽量merge～
