### ISSUE TITLE
文章标题宋体字渲染

### ISSUE THREAD

**Issue by royrs** [tufu9441/maupassant-hexo#267]
有的时候打开blog，标题有概率不被渲染，显示如下图：

![biaoti]( http://7xq0c3.com1.z0.glb.clouddn.com/%E6%8D%95%E8%8E%B7.PNG )

不过还是要请教博主，是怎么把这个宋体字在win下面渲染好看哒。

**Comment by tufu9441** [comment]
我的标题使用的是思源宋体，具体方法见
https://sspai.com/post/38705

**Comment by zouyifeng** [comment]
请问生成博客的方式，都是通过.md文件生成吗？生成后的标题字体格式有些出入，如图
![image](https://cloud.githubusercontent.com/assets/22537660/26271162/daba3e54-3d34-11e7-8886-b178a656f11e.png)
是否有其他地方需要配置了？谢谢~

**Comment by tufu9441** [comment]
@zouyifeng 是的，都是通过md文件。字体渲染与系统、浏览器和本地字体有关，你这个显示是正常的，大部分显示效果就是这样。
