### ISSUE TITLE
运行命令出错

### ISSUE THREAD

**Issue by xiaoyouPrince** [tufu9441/maupassant-hexo#270]
今天安装主题的时候，运行 npm install hexo-renderer-sass --save 命令出错了,如下：

----------
In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:8:10: fatal error: 'sass/context.h' file not found
#include <sass/context.h>
         ^
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/quxiaoyou/blog/node_modules/node-gyp/lib/build.js:285:23)

----------

我尝试直接本地服务器运行一下，什么也展示不出来，终端报错如下

------
➜  blog hexo server
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
WARN  No layout: index.html
WARN  No layout: index.html
------

应该是在安装什么的时候里面文件找不到了，希望博主查一查，解决一下。

**Comment by tufu9441** [comment]
你看一下 #225 能否有帮助。

**Comment by plainnany** [comment]
我也遇到了这个问题，而且用的是淘宝镜像下载的，还是不行

**Comment by tufu9441** [comment]
那试试不要用镜像，挂代理。

**Comment by plainnany** [comment]
嗯，试过了，是可以的，不过要下载hexo-renderer-scss这个文件。

发自我的 iPhone

在 2017年5月19日，19:14，tufu9441 <notifications@github.com<mailto:notifications@github.com>> 写道：


那试试不要用镜像，挂代理。
