### ISSUE TITLE
如何增加评论板块

### ISSUE THREAD

**Issue by peiyaoli** [tufu9441/maupassant-hexo#271]
Hi, 我很喜欢你的主题，并用于我的博客中。
我现在想增加评论板块。我在 ~/themes/maupassant/_config.yaml中增加了友言的账号，然后post中设置了comments: true。但是没有显示评论，请问这是为什么呢？我该加些其他的东西么

**Comment by peiyaoli** [comment]
@tufu9441 希望您能给与帮助

**Comment by tufu9441** [comment]
我又更新了一下，现在已经跟友言后台要求的代码完全一致了，但还是显示不出来友言评论框的原因是友言服务器上的一个脚本挂了，用浏览器检查一下就可以看到。
![](http://i.imgur.com/njqjbpO.jpg)
