### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by liwangmin** [tufu9441/maupassant-hexo#272]
`extends base - var current_title = page.title || tag.name || category.name || site.title block title if config.subtitle title= config.title + ' | ' + config.subtitle else title= config.title block content for post in page.posts.toArray() .post h1.post-title include _partial/helpers a(href=url_for(post.path)) +title(post) .post-meta= post.date.format(config.date_format) if theme.duoshuo a.ds-thread-count(data-thread-key=post.path, href=url_for(post.path) + '#comments') if theme.disqus a.disqus-comment-count(data-disqus-identifier=post.path, href=url_for(post.path) + '#disqus_thread') if theme.gentie a.ds-thread-count(class='cloud-tie-join-count', href=url_for(post.path) + '#comments') span.join-count(lang='join-count' style='margin: 0 3px 0 1px;' data-url='#{config.url}#{url_for(post.path)}') 0 span= ' ' + __('Discuss') if post.description .post-content != post.description else if post.excerpt .post-content != post.excerpt else if post.content - var br = 0 - for (var i = 0; i < 5; ++i) { - br = post.content.indexOf('\n',br+1) if br<0 - break if br >150 - break - } if br < 0 .post-content != post.content else .post-content != post.content.substring(0, br) p(class='readmore') a(href=url_for(post.path))= __('Readmore') include _partial/paginator if theme.disqus script(id='dsq-count-scr', src='//#{theme.disqus}.disqus.com/count.js', async) if theme.gentie script. var yunModuleEnv = true; script(src='//img1.cache.netease.com/f2e/tie/yun/sdk/loader.js') script. var yunTieProductKey = '#{theme.gentie}'; Tie.loader('aHR0cHM6Ly9hcGkuZ2VudGllLjE2My5jb20vZXh0ZW5kL2xpc3Rfam9pbl9zY3JpcHQuaHRtbA==', true);` 请问什么原因

**Comment by JinghuiXiao** [comment]
我的也是，依赖的都装上了，还重试了几次。为什么还是报错

**Comment by tufu9441** [comment]
可能最近的更新出了bug？要不你们退回之前的版本试一试。

**Comment by hwyoung** [comment]
同样报错，如果是兼容性的问题，以后会修复吗？

**Comment by tufu9441** [comment]
我自己又测试了一下最新的代码，没有出现任何问题。我判断还是依赖没有安装正确，可以看一下 #225 。另外，现在jade改名为pug了，不知道hexo-renderer-jade的安装方法有没有变化，但是这个依赖我很长一段时间内都没有重新安装过，所以也不太清楚。

**Comment by tufu9441** [comment]
#5 #7 #66 这几个issues都是类似的问题，一直以来都有，不过也是个别现象，很奇怪。

**Comment by JinghuiXiao** [comment]
改名了，那我重新装hexo-renderer-pug？




发自网易邮箱大师


在2017年05月11日 16:01，tufu9441<notifications@github.com> 写道：

我自己又测试了一下最新的代码，没有出现任何问题。我判断还是依赖没有安装正确，可以看一下 #225 。另外，现在jade改名为pug了，不知道hexo-renderer-jade的安装方法有没有变化，但是这个依赖我很长一段时间内都没有重新安装过，所以也不太清楚。

**Comment by tufu9441** [comment]
我了解了一下，这几天hexo-renderer-jade更新了一个版本：https://www.npmjs.com/package/hexo-renderer-jade 好像是不再能渲染.jade格式的文件了，因此你们可以安装之前的版本试一试：
`npm install hexo-renderer-jade@0.3.0 --save`

**Comment by JinghuiXiao** [comment]
坑爹啊，这几天试了无数次，重装了系统，node ，各种插件




发自网易邮箱大师


在2017年05月11日 16:56，tufu9441<notifications@github.com> 写道：

我了解了一下，这几天hexo-renderer-jade更新了一个版本：https://www.npmjs.com/package/hexo-renderer-jade 好像是不再能渲染.jade格式的文件了，因此你们可以安装之前的版本试一试：
npm install hexo-renderer-jade@0.3.0 --save

**Comment by tufu9441** [comment]
如果这个方法管用的话反馈给我，我好更新一下教程。实在是不想把所有文件都改成什么最新的*.pug了。

**Comment by hwyoung** [comment]
`npm install hexo-renderer-jade@0.3.0 --save` 可以

**Comment by JinghuiXiao** [comment]
果然是这个原因。。谢谢。非常





发自网易邮箱大师
在2017年05月11日 21:38，hwyoung 写道：

npm install hexo-renderer-jade@0.3.0 --save 可以

**Comment by plainnany** [comment]
npm install hexo-renderer-jade@0.3.0 --save这个安装了可以，但是npm install hexo-renderer-sass --save
安装这个一直失败，用的是淘宝的镜像，一直不成功
