### ISSUE TITLE
文档的大坑啊

### ISSUE THREAD

**Issue by Lagranmoon** [tufu9441/maupassant-hexo#278]
博客上面写的是 npm install hexo-renderer-jade --save
以为是和readme一样就只看了博客
结果死活解析不出来，搜了一晚上才发现
readme里面写的是 npm install hexo-renderer-jade@0.3.0 --save
似乎是因为商标问题最新0.4.0版本改成了pug但是主题没有支持吧
`https://github.com/hexojs/hexo-renderer-jade`
提醒一些看教程和博客的后来者们

**Comment by tufu9441** [comment]
你说得对，博客上的中文文档也更新了。
