### ISSUE TITLE
安装主题后怎么没有disqus评论了？

### ISSUE THREAD

**Issue by theqwang** [tufu9441/maupassant-hexo#28]
您好，很喜欢这个主题！可是我安装以后怎么没有demo里的disqus评论了呢，求告知怎么添加disqus啊

**Comment by tufu9441** [comment]
正确填写disqus的shortname。

On 周二, 12月 22, 2015 at 16:32, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
您好，很喜欢minos这个主题！可是我安装以后怎么没有demo里的disqus评论了呢，求告知怎么添加disqus啊

**Comment by mckobe23** [comment]
之前用的jane主题，disqus没有问题，我也是安装后，配置没变，disqus没有了，shortname就是的用户名

**Comment by mckobe23** [comment]
我来再回复一遍吧，有2个地方需要修改
1.主题的_config.yml中

**Comment by mckobe23** [comment]
我来再回复一遍吧，有2个地方需要修改
1.主题的_config.yml中
disqus: youname (这里注意与后面井号的空格) ## Your disqus_shortname, e.g. username

2.站点的disqus_shortname: yourname

2个地方都要添加页面才能显示！
