### ISSUE TITLE
手机端显示格式出错

### ISSUE THREAD

**Issue by Joryun** [tufu9441/maupassant-hexo#280]
您好，我使用了这个主题并发表Markdown格式的文章时，对于“（）”这个符号pc端的显示并无问题，但手机端的显示格式是错乱的，请问该怎么解决呢？

**Comment by tufu9441** [comment]
我试着用手机访问了一下你的网站，并没有发现问题啊，能否有截图展示一下

**Comment by Joryun** [comment]
就像以下照片显示的这样，正常浏览情况就是这样的，但是点了阅读模式就可以对齐了，表示能否有解决方案呢？
![](https://cloud.githubusercontent.com/assets/16618630/26283707/8f63a432-3e5f-11e7-9f42-186f99c78922.png)

**Comment by tufu9441** [comment]
我看到了，但我暂时也不知道是什么原因，以及如何解决。

**Comment by Joryun** [comment]
好的 多谢解答 我有时间再自己琢磨琢磨 如若是有了解决方案 麻烦告知下哈 thanks~~

**Comment by CarlKing5019** [comment]
这个应该是对齐设定导致的问题. 正文中使用的对齐方式是
```
.post .post-content {
    text-align: justify;
    word-break: normal;
}
```
你给的几个例子中都有长单词, 加上长单词超出一整行, 所以在单词处断行了, 前一行长度不足一整行被拉伸到了一整行导致字符间距变大了.

解决办法, 修改或添加如下 css 代码.

```
.post .post-content {
    text-align: justify;
    word-break: break-all;
}
```
