### ISSUE TITLE
能否集成gitment评论系统

### ISSUE THREAD

**Issue by ichenkaihua** [tufu9441/maupassant-hexo#283]
多说即将关闭，希望能集成gitment评论
项目地址:https://github.com/imsun/gitment

**Comment by icyfish** [comment]
@ichenkaihua 可以参考这篇文章 [给Hexo博客添加Gitment评论系统](https://wf94.github.io/2017/04/14/Use-Gitment-In-Hexo/)

**Comment by InvalidCode** [comment]
gitment评论，提交了PR[#310](https://github.com/tufu9441/maupassant-hexo/pull/310)

**Comment by tufu9441** [comment]
Merged.
