### ISSUE TITLE
你好，文章阅读页面能否隐藏掉sidebar

### ISSUE THREAD

**Issue by jerry011235** [tufu9441/maupassant-hexo#284]
1.文章阅读页面能否隐藏掉`sidebar`（右侧分类标签等等），这样就可以把目录fixed在右侧了。
谢谢！
2.如何修改返回顶部的火箭图标为自定义的png图片（source/css/image/xx.png）？
ps：404页面自己已解决，请忽略。

**Comment by northleafup** [comment]
请问这个问题中的第一个是如何解决的呢，谢谢

**Comment by jerry011235** [comment]
@northleafup 你好，参见[这里](https://github.com/jerry011235/maupassant-hexo/commit/2b994e664e009559c97833d2245c64961a26033b)。

**Comment by northleafup** [comment]
@jerry011235 谢谢，我按这个改一下先。

**Comment by ideasmaze** [comment]
请问第2个问题是怎么解决的呢？谢谢！
