### ISSUE TITLE
在windows下安装hexo-renderer-sass出错

### ISSUE THREAD

**Issue by lobinga** [tufu9441/maupassant-hexo#29]
您好，我想尝试一下这个主题。在安装hexo-renderer-sass时出错，通过日志发现，是编译libsass时出错的，原因是不认识uint64_t和uint_fast32，只要包含头文件stdint.h就可以了，但是npm每次安装都会从新下载编译，没有修改的机会，您看有什么办法能解决这个问题。
我的环境是win10，VS2013。
谢谢！

**Comment by tufu9441** [comment]
不好意思，除了主题本身的功能，其它的问题我也不是很懂，看看有没有其他人能帮到你吧，抱歉。

On 周三, 12月 23, 2015 at 15:08, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:

您好，我想尝试一下这个主题。在安装hexo-renderer-sass时出错，通过日志发现，是编译libsass时出错的，原因是不认识uint64_t和uint_fast32，只要包含头文件stdinth就可以了，但是npm每次安装都会从新下载编译，没有修改的机会，您看有什么办法能解决这个问题。
我的环境是win10，VS2013。
谢谢！

**Comment by lobinga** [comment]
好，谢谢！

**Comment by alemonmk** [comment]
其實如果你的網路是「暢通」的話, npm 會下載已經編譯好的 libsass 而不需要 build, 參見 sass/node-sass@d4b8f6b 及 sass/node-sass@b8050ef。Get yourself a better internet ;)

**Comment by tufu9441** [comment]
既然如此，可以尝试一下淘宝的npm镜像。

**Comment by alemonmk** [comment]
根本就有啊 XDDD node-sass 居然還單獨列一條: http://npm.taobao.org/mirrors

**Comment by tufu9441** [comment]
翻到了之前在我博客下评论的一条内容，不知道对此问题有没有帮助（以下全为引用）：

我的系统是mac OSX10.11.1，

我在执行

```
npm install hexo-renderer-sass --save
```

的时候提示:

```
'sass/content.h' file not found，
```

如果忽略这个问题的话，执行hexo s 页面就会是这个样子：

![demo](https://a.disquscdn.com/uploads/mediaembed/images/2776/1155/original.jpg)

我的解决办法是：

```
brew install libsass
```

应该是系统却少sass的一些头文件吧。装上这个libsass之后就可以成功编译sass了。而后重新执行

```
npm install hexo-renderer-sass --save #成功，
```

但是执行hexo s 的时候可能报错：

```
➜ hexo_blog git:(master) ✗ hexo s

dyld: lazy symbol binding failed: Symbol not found: _libsass_version

Referenced from: /Users/reasonpun/project/github/hexo_blog/node_modules/node-sass/vendor/darwin-x64-47/binding.node

Expected in: flat namespace

dyld: Symbol not found: _libsass_version

Referenced from: /Users/reasonpun/project/github/hexo_blog/node_modules/node-sass/vendor/darwin-x64-47/binding.node

Expected in: flat namespace

[1] 7849 trace trap hexo s
```

如果是这样，可以试着 delete the node_modules folder and run npm install again。然后执行：
```
npm install node-sass
```
got it！
