### ISSUE TITLE
请问归档的分页如何去掉

### ISSUE THREAD

**Issue by msisliao** [tufu9441/maupassant-hexo#290]
希望可以像博主这样(https://www.haomwei.com/archives/)
显示归档（没有分页，直接按年份全部显示）
PS：我在根目录下_config.yml设置了分页条数是6 ， 可归档也按这个设置走了

**Comment by Hscpro** [comment]
#277 #30

**Comment by msisliao** [comment]
3q~~ 在网上找到的解决办法  已经去掉了~~~
