### ISSUE TITLE
some issue of disqus click

### ISSUE THREAD

**Issue by neoFelhz** [tufu9441/maupassant-hexo#291]
disqus 的 favicon 没有 `Access Control Allow Origin`，直接发起 XHR 会报错；
判断部分的 Ajax 请求可以通过 GET  `https://disqus.com/next/config.json` 实现；
也可以直接判断 `shortname.disqus.com/embed.js` 是否加载成功，Disqus 有相关的回调函数。

![](https://ooo.0o0.ooo/2017/06/11/593d56e75cd9c.png)
![](https://ooo.0o0.ooo/2017/06/11/593d577b00e95.png)

**Comment by tufu9441** [comment]
已按照您的建议修改。
