### ISSUE TITLE
网易云跟帖能否添加Sourceid

### ISSUE THREAD

**Issue by imliujun** [tufu9441/maupassant-hexo#292]
>为避免以下问题，强烈建议使用sourceid：
1、同一文章多个URL地址，每个页面显示不同的跟贴数据
2、文章URL变动导致跟贴数据错乱

网易云跟帖官方推荐，而我切换域名也遇到这个问题了，不知道能否添加 sourceid做为标识

**Comment by Hscpro** [comment]
sourceid的话这个要自己生成比较麻烦。云跟帖的话还是不推荐使用吧，上次我在云跟帖技术群听管理说这个项目暂停了。

**Comment by imliujun** [comment]
@Hscpro 那哪家评论系统比较稳定？

**Comment by Hscpro** [comment]
好像国内没几家评论系统了吧，畅言不恶心备案的话稳定性还是可以的。
我自己用的是自己搭建的ISSO评论系统

**Comment by imliujun** [comment]
@Hscpro 对于使用pages服务的博客，ISSO需要有自己的服务器。我博客已经备案了，还是使用畅言吧。谢谢啦

**Comment by Hscpro** [comment]
有openshift账号的话，也是可以搭建的

**Comment by imliujun** [comment]
![image](https://user-images.githubusercontent.com/9779970/27428760-9e3b9e9a-5775-11e7-9303-8fe820b5948f.png)

这个文章 ID 不知道是什么，应该可以当sourceid用吧

**Comment by Hscpro** [comment]
这个是只有`url`才有的变量吧

**Comment by Hscpro** [comment]
文章的`url`不应该经常变动的吧，这样对搜索引擎也不友好。
云跟帖是自动同步 HTTP/HTTPS 两个链接的评论数据的

**Comment by imliujun** [comment]
主要是多域名的情况下不同域名评论数据不一样

**Comment by imliujun** [comment]
其实我觉得用文章标题就可以了啊，文章标题一般发布后就不会变了

**Comment by imliujun** [comment]
https://github.com/hexojs/hexo/issues/1595 
楼主通过自定义模板，添加了一个时间戳来作为sourceid
照着他这种方式做也可以吧

**Comment by imliujun** [comment]
我使用畅言，并使用文章创建时间作为sourceid，已经解决了这个问题了。已提交PR #299
