### ISSUE TITLE
为什么我安装后就这样了？

### ISSUE THREAD

**Issue by Orangstudio** [tufu9441/maupassant-hexo#293]
![qq 20170615231604](https://user-images.githubusercontent.com/23445884/27188471-d33b0aea-5220-11e7-85dd-34d2666277c6.png)

**Comment by ploverpang** [comment]
同问。我通过hexo部署之后，也是同样的效果。

**Comment by Hscpro** [comment]
浏览器版本？浏览器报错信息？

**Comment by tufu9441** [comment]
应该是css没有正确载入。很有可能是hexo-renderer-sass没安装好。

**Comment by breky-zhao** [comment]
随便打开一篇文章，看是不是能打开。打不开，在打开文章的浏览器的地址栏中一点一点修改吧，直到能打开文章为止，文章打开，还是没有CSS样式的，这是路径设置不对，修改Hexo的_config.yml。如果直接能打开，那我就是不懂了。
