### ISSUE TITLE
配置文件中的Static files 的JS/CSS资源目录选项无效

### ISSUE THREAD

**Issue by Hscpro** [tufu9441/maupassant-hexo#296]
将主题配置文件设为
```
## Static files
js: static/js
css: static/css
```
输出
![20170621_181805](https://user-images.githubusercontent.com/13926044/27379522-1ff5b402-56ae-11e7-91ff-5a55fa7c0a09.jpg)

浏览器报错
 ![20170621_183000](https://user-images.githubusercontent.com/13926044/27379913-b7e89d78-56af-11e7-8e38-acd29aaff616.jpg)

实际更改了页面上的地址结构但是未更改HEXO输出的地址结构
还是说我理解错误，这个只是更改页面上的地址，还要靠后端重定向指定文件？

**Comment by Hscpro** [comment]
@tufu9441

**Comment by tufu9441** [comment]
这个如果不使用CDN的话就不要修改，使用CDN的话就改成CDN链接的前半部分。

**Comment by Hscpro** [comment]
没理解，就是说要加上域名？
这个选项实现的效果是什么

**Comment by tufu9441** [comment]
比如说我的js和css文件放在七牛云上了，那么我就可以把js的路径设置为：https://dn-xxx.qbox.me/js
