### ISSUE TITLE
如何修改字体，好几次都不成功

### ISSUE THREAD

**Issue by jetyu** [tufu9441/maupassant-hexo#297]
https://www.haomwei.com/
想修改成作者这样的title但是把style.scss改动之后，还是不成功。

html,
button,
input,
select,
textarea,
.MJXc-TeX-unknown-R,
.pure-g [class *="pure-u"] {
    /* Set your content font stack here: */
    font-family: "PingFangSC-Regular", Helvetica, "Helvetica Neue", "Segoe UI", "Hiragino Sans GB", "Source Han Sans CN", "Microsoft YaHei", "STHeiti", "WenQuanYi Micro Hei", sans-serif !important;
}

body {
    background-color: #FFF;
    color: #444;
    font-family: "TIBch", "Classic Grotesque W01", "Helvetica Neue", Arial, "Hiragino Sans GB", "STHeiti", "Microsoft YaHei", "WenQuanYi Micro Hei", SimSun, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 14px;
}

再就是
post-style那里
设置成
font: bold 25px/1.1 "Noto Serif CJK SC", "Source Han Serif SC", "Source Han Serif", source-han-serif-sc, '宋体', serif;

设置之后，发现也不对。。。。F12是这个class啊。。。

希望作者能把style.scss分享一下，谢谢了。

**Comment by tufu9441** [comment]
我的标题使用的是思源宋体，具体方法见
https://sspai.com/post/38705
