### ISSUE TITLE
如何加代码高亮？

### ISSUE THREAD

**Issue by zhaoweiwang** [tufu9441/maupassant-hexo#3]
RT

**Comment by tufu9441** [comment]
说明里写了，麻烦仔细阅读一下README再提问。

**Comment by zhaoweiwang** [comment]
并没有什么卵用。PS：既然这么嫌麻烦，就干脆不要混开源，另外这个也不是你的原作。无恶意。：）

**Comment by tufu9441** [comment]
如果按照那样设置了还不显示高亮的话，那我目前也不知道问题出在哪里了，测试样本太少，抱歉。

**Comment by v123582** [comment]
@tufu9441 ，我根據 Readme 設定是可以 work 的
要把 enable 改成 false?

**Comment by tufu9441** [comment]
@v123582 是的，目前是这样。不过我现在正在修改highlight的实现，打算将样式嵌入主题然后使用hexo自带的highlight功能，就不用自己加载js了。晚些时候会更新。

**Comment by tufu9441** [comment]
@v123582 更新了，跟hexo配置统一了，你可以看一下新的使用方法。
