### ISSUE TITLE
Facebook link preview not working

### ISSUE THREAD

**Issue by walterpinson** [tufu9441/maupassant-hexo#300]
Is this an issue with the theme or is there a Hexo plugin for Facebook that I should be using?  The [Facebook debugger](https://developers.facebook.com/tools/debug) yielded the following warnings for particular shared post of mine .

| WARNING | DESCRIPTION
| :--- | :---
| Inferred Property | The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.
| Inferred Property | The 'og:title' property should be explicitly provided, even if a value can be inferred from other tags.
| Inferred Property | The 'og:description' property should be explicitly provided, even if a value can be inferred from other tags.
Inferred Property | The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.
Share App ID Missing | The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.
Inferred Property | The 'og:image' property should be explicitly provided, even if a value can be inferred from other tags.

Note:  This is the blog post that pointed me in the direction of the Facebook debugger: http://www.marketingyourpurpose.com/facebook-link-preview-not-working/.

**Comment by tufu9441** [comment]
Do you mean that the Share button of the theme cannot work well?
