### ISSUE TITLE
关于 mathjax 的问题

### ISSUE THREAD

**Issue by lolipopshock** [tufu9441/maupassant-hexo#305]
tufu 你好，想问下，我在 hexo 目录的 `_config.yaml` 及文章中 `front-matter` 中均添加了 `mathjax: true`，然而 mathjax 只能识别单$符号包围的公式，却识别不了双$符号包围的公式，想问下这是 bug 还是有对应的解决方案的呢？

**Comment by tufu9441** [comment]
双$包围的块状公式应该没问题的啊

**Comment by rogerwwww** [comment]
我遇到了类似的问题，可能跟你原因不一样，供参考。
问题描述：部分公式正常显示，部分公式显示不正常
原因：markdown转换的时候，公式中的下划线被优先于“$”处理了，因此有些公式没有正常显示
解决方法：将所有公式中的下划线"_"前加斜杠，即改为"\_"。改完后，Typora中会显示不正常，但是发布后是正常的。

**Comment by SnailDove** [comment]
被数学公式整疯了，比如数学公式$\begin{pmatrix}a&*\\0&b\end{pmatrix}$这里面星号无法识别，又比如$\begin{pmatrix}a&b\\-c&b\\-d&e\end{pmatrix}$

**Comment by SnailDove** [comment]
被数学公式整疯了，比如数学公式:
1. $\begin{pmatrix}a&*\0&b\end{pmatrix}$ 这里面**星号无法识别**
2. 又比如$\begin{pmatrix}a&b\-c&b\-d&e\end{pmatrix}$ 这里面**负号无法识别**
3. 又比如$e^{{2k\pi\over 2}i}$这里面 **分母嵌套**报错，无法hexo generate，取代方法另一个分式表达：$e^{\frac{2k\pi}{2}i}$

**Comment by SnailDove** [comment]
为什么不在处理正文前 对 $公式$ 和 $$公式$$ 里面的内容不进行分析？求大神们解决

**Comment by tufu9441** [comment]
说实话我对Mathjax这块真的不懂，对此功能的支持也是之前合并了@ChenZhongPu 的Pull Request才添加进来的。

**Comment by LeeReindeer** [comment]
数学公式还是无法显示，已经在 site 的 _config.yaml 和文章中 front-matter 都添加了 mathjax: true。是不是需要安装`hexo-math`的，但是我在安装了`hexo-math`也不能显示。

![image](https://user-images.githubusercontent.com/22074258/50622590-4ff50e00-0f49-11e9-98d3-692136f64cf8.png)
---
![image](https://user-images.githubusercontent.com/22074258/50622597-584d4900-0f49-11e9-8d72-3e594e546070.png)

**Comment by LeeReindeer** [comment]
emmm，已解决，需要安装 `npm install hexo-math@^2.0.1 --save`，3.0 版本的 hexo math 已经变了。

**Comment by ChenZhongPu** [comment]
根本需要安装hexo-math。目前对数学公式的支持本质上是引入了一个js的库，让它去显示。

**Comment by LeeReindeer** [comment]
没安装 hexo math 之前都无法显示……不知道为啥（

On Jan 3, 2019 11:58, chenzhongpu <notifications@github.com> wrote:

根本需要安装hexo-math。目前对数学公式的支持本质上是引入了一个js的库，让它去显示。

**Comment by counter2015** [comment]
> emmm，已解决，需要安装 `npm install hexo-math@^2.0.1 --save`，3.0 版本的 hexo math 已经变了。

感谢，按照这个方法已解决。我遇到的问题是，本地`hexo s`正常显示公式，`hexo d`上传后github发邮件告诉我编译错误，但是又不告诉具体错误信息。
