### ISSUE TITLE
对MarkDown的支持有问题

### ISSUE THREAD

**Issue by songxk** [tufu9441/maupassant-hexo#306]
正常：
![image](https://user-images.githubusercontent.com/1507323/28296802-fae69358-6b9c-11e7-8cba-bfdf63ec38ea.png)

该主题下：
![image](https://user-images.githubusercontent.com/1507323/28296813-0b260c94-6b9d-11e7-8073-02ae8d72116d.png)

![image](https://user-images.githubusercontent.com/1507323/28296819-143142e0-6b9d-11e7-8274-01baf2b9a13e.png)

Chrome浏览器下 拉窄页面显示有问题
![image](https://user-images.githubusercontent.com/1507323/28296857-4e98a39c-6b9d-11e7-9564-328e58022a4f.png)

**Comment by tufu9441** [comment]
那不是对markdown的支持问题，是该主题特有的引用样式，如果不喜欢可以自己修改css。第二个问题可以在config.yml中设置在小屏下不显示边栏。

**Comment by DavidSheh** [comment]
@songxk 请问第一个问题你搞定了么？我也想要Markdown引用标签默认的渲染

**Comment by tufu9441** [comment]
@DavidSheh #234
