### ISSUE TITLE
建议加入对“来必力”评论的支持

### ISSUE THREAD

**Issue by 0NG** [tufu9441/maupassant-hexo#311]
友言由于不是https，不能在GitHub pages上用，后来我发现另一个叫“来必力”的，现在我自己改了代码在用。虽然是韩国的，但国内也可以使用，能否加入这个呢？

**Comment by tufu9441** [comment]
Merged.

**Comment by 0NG** [comment]
Thanks! 后来想到PR就可以了嘻嘻
