### ISSUE TITLE
请问能否为主题添加TOC功能，还是？？我自己也搞不懂

### ISSUE THREAD

**Issue by Lucien-Zhang** [tufu9441/maupassant-hexo#324]
我用Sublime TOC插件生成了一个TOC，在页面上预览的时候没有变成网上普遍那种居右上，且给出各个标题目录的超链接...

类似于这样

https://developer.android.com/guide/components/fundamentals.html

我在想，是主题没有写TOC插件，还是Hexo本身就没有Markdown这个扩展语法

不过我用本地服务器预览的时候有看到目录，只是没有超链接，没有居右上，也没有CSS......
所以我不是很确定是哪里的问题......

**Comment by dequn** [comment]
主题有TOC呀，也有标题链接的，所以...

**Comment by tufu9441** [comment]
对的，主题自带TOC功能，仔细阅读说明。
