### ISSUE TITLE
历史页在条目较少时条目会粘在一起

### ISSUE THREAD

**Issue by icgeass** [tufu9441/maupassant-hexo#325]
在历史数目较少时Past Now容易和相邻行的历史挨在一起，并且随着历史数目的减少，可以看出Past和相邻历史的距离与Now的不同
比如：https://www.6zeroq.com/history

**Comment by tufu9441** [comment]
我自己试了试确实会出现这种情况，当条目数在5个以上时，间隔才会比较明显。但是这部分功能是早先从其它主题移植过来的，我找了半天也没能找到在哪里可以修改Past和第一条内容之间的距离😂

**Comment by tufu9441** [comment]
Fixed by #529
