### ISSUE TITLE
Google Analytics不生效

### ISSUE THREAD

**Issue by xl0shk** [tufu9441/maupassant-hexo#326]
在主题的_config.yml中添加Google统计后，好像不生效
google_analytics: UA-1xxx

不知道是不是我使用的问题？

**Comment by soulomoon** [comment]
同问

**Comment by vsxen** [comment]
chrome F12 network 看看js有没有加载上

**Comment by YetAnotherCP** [comment]
Google Analytics不生效可能是hexo-inject插件在生成的<script>中添加html注释所导致的，可以尝试卸载这一插件。详情可见[https://suzhouxing.github.io/techive/2017/09/03/HexoMathSupport/](https://suzhouxing.github.io/techive/2017/09/03/HexoMathSupport/)（不过目前我卸载hexo-inject之后，hexo-math插件仍然可以工作。）

**Comment by silver6wings** [comment]
我这GA的代码没有被注释掉为啥也不行

**Comment by silver6wings** [comment]
确实需要npm remove hexo-inject
在<script></script>之间加了一个直接把GA的script弄挂了
