### ISSUE TITLE
请问如何将菜单的文字显示成中文呢？

### ISSUE THREAD

**Issue by weimingge14** [tufu9441/maupassant-hexo#327]
前提是我在 hexo 的根目录下的 _config.yml 文件中已经设置了 `language: zh-Hans`，可是我的页面是这样的。不知道如何定制成中文呢？谢谢。

![31d2f280-ccd1-41d8-99a6-b9187177e3ce](https://user-images.githubusercontent.com/7555554/31000535-d92874ce-a50e-11e7-87c6-035610d49d13.png)

**Comment by tufu9441** [comment]
zh-CN

**Comment by weimingge14** [comment]
原来是这样啊，是我粗心了，非常感谢！
