### ISSUE TITLE
阅读统计问题

### ISSUE THREAD

**Issue by zerocc2014** [tufu9441/maupassant-hexo#329]
只要以前文章有修改 重新hexo d，阅读统计数就清0了

**Comment by InvalidCode** [comment]
名字有改变是这样

**Comment by InvalidCode** [comment]
计数原来是一URL访问计算，如果URL改变就清零，如果MD文件名字改变，那么会导致生成的网页名字改变，使得不是原来URL。

**Comment by tufu9441** [comment]
http://ibruce.info/2015/04/04/busuanzi/#more

**Comment by zerocc2014** [comment]
文章名字没改变的，只是文章内容 以前写的做一些修改就清零了
