### ISSUE TITLE
config.feed.type undefined

### ISSUE THREAD

**Issue by etaf** [tufu9441/maupassant-hexo#33]
In file layout/base.jade line 8
> case config.feed.type

This line introduced such error: Cannot read property 'type' of undefined

I modify you code as follows and it works.
```
if config.feed
  case config.feed.type
    when "rss2"
      - var feed_type='application/rss+xml'
    when "atom"
    default
      - var feed_type='application/atom+xml'
```

Maybe you did not meet such problem, but considering the config.feed first may be better.

**Comment by tufu9441** [comment]
I didn't meet such problem indeed, and I don't know how to repeat it? @alemonmk

**Comment by alemonmk** [comment]
If hexo-generator-feed is enabled (i.e. listed under `plugins` in /_config.yml/) there should be a default config. I'm sorry that I over looked this.

**Comment by tufu9441** [comment]
But I tried not to load that plugin just now and no error was reported too...

On 周三, 12月 30, 2016 at 23:37, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
If hexo-generator-feed is enabled (i.e. listed under plugins in /_config.yml/) there should be a default config. I'm sorry that I over
looked this.

—
Reply to this email directly or view it on GitHub
[https://github.com/tufu9441/maupassant-hexo/issues/33#issuecomment-168020538] .[https://github.com/notifications/beacon/AGec2bQ7HZnQdwkGV1vwM-cJEntUYtlFks5pU_GkgaJpZM4G8yOf.gif]

**Comment by alemonmk** [comment]
Yeah, I can't disable the feed generator, it still somehow loads and generate feed ... that's why I ignored this feed-generator-missing scenario.

**Comment by tufu9441** [comment]
@alemonmk So should we add the `if config.feed` like he suggested?

**Comment by alemonmk** [comment]
It does nothing bad if we add it, why not go ahead?

**Comment by tufu9441** [comment]
OK.

On 周四, 12月 31, 2016 at 14:09, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
It does nothing bad if we add it, why not go ahead?

—
Reply to this email directly or view it on GitHub
[https://github.com/tufu9441/maupassant-hexo/issues/33#issuecomment-168130131] .[https://github.com/notifications/beacon/AGec2XaANc4ii3xUv4Vjvv2sgom1gYwsks5pVL4xgaJpZM4G8yOf.gif]
