### ISSUE TITLE
行内代码字体显示不正常

### ISSUE THREAD

**Issue by kloudmuka** [tufu9441/maupassant-hexo#332]
只有IE上能显示出是monospace字体，Chrome和Firefox上都认不出来，被替换成了系统默认的宋体，导致展示效果不佳。

**Comment by tufu9441** [comment]
这个应该是跟文章中其它文字一起变的，但目前还真不清楚怎么控制。

**Comment by YetAnotherCP** [comment]
在style.scss中增加
```
code {
    font-family: Menlo, Consolas, monospace !important;
}
```
似乎在FireFox、Chrome和IE中可行。

**Comment by tufu9441** [comment]
@YetAnotherCP 能否说一下具体是添加在了`style.scss`中的哪个位置？

**Comment by kloudmuka** [comment]
我是加在body之前，测试有效，感谢@YetAnotherCP提供的方法

**Comment by tufu9441** [comment]
多谢，已经添加上了。
