### ISSUE TITLE
page 页面的插入图片的显示问题：

### ISSUE THREAD

**Issue by zhuoshuai** [tufu9441/maupassant-hexo#334]
page 页面的插入图片的显示问题：
以生成的about页面为例
将图片资源放置在about文件中，
- about
    - index.md
    - image.jpg
    - index
        - image_1.jpg

使用
`
![](/images/image.jpg)
`
`
{% asset_img image1_1.jpg This is an image %}
`
只有第一种方法可以显示图片，第二种显示不了；

**Comment by tufu9441** [comment]
从来没有过第二种方法，但我觉得这不应该是模板的问题。

**Comment by zhuoshuai** [comment]
嗯， 应该是 Hexo 的问题。
