### ISSUE TITLE
Feature Request: support local config file

### ISSUE THREAD

**Issue by hiberabyss** [tufu9441/maupassant-hexo#338]
Currently, we edit `_config.yml` file directly to do customization. However, when merge the latest commits, conflicts will occur because of `_config.yml` changes.

Maybe local config file could be supported, the settings in it could override the default configuration file.

Thanks!

**Comment by tufu9441** [comment]
Sorry I still do not understand what the "local config file" means and how to realize it.

**Comment by Smlight** [comment]
@tufu9441 I think he means: 
When we do `git pull` in `themes/maupassant/` , without extra operations, the `_config.yml` in this (remote) repository would overwrite the local `_config.yml` .
