### ISSUE TITLE
不支持代码标记

### ISSUE THREAD

**Issue by lorichueng** [tufu9441/maupassant-hexo#34]
有计划支持吗？

**Comment by tufu9441** [comment]
请问你所说的代码标记指的是什么，是声明代码语言吗？

**Comment by lorichueng** [comment]
当缩进两次的时候，会把缩进后面的内容包起来，以区分正分和代码段。和代码语言无关

**Comment by tufu9441** [comment]
那不就是代码高亮么，那已经支持了啊，而且是Hexo自带的功能。代码前后分别用3个反引号包裹起来就行了，更多插入代码的方式，参见[docs](https://hexo.io/zh-cn/docs/tag-plugins.html#u4EE3_u7801_u5757)。
