### ISSUE TITLE
打赏设置与icon问题

### ISSUE THREAD

**Issue by Ezail3** [tufu9441/maupassant-hexo#342]
1、打赏如何做到不是每篇博客下面都显示，而是about里面显示，如作者博客一样

2、icon放到文档指定的目录下，不生效

求指导，谢谢！！！

**Comment by InvalidCode** [comment]
图片放置在 source/img 
如果你不想在博客下面显示，在about显示我是不建议的，所以我并没有写在哪里

**Comment by Ezail3** [comment]
先感谢大哥百忙中抽空回复我的问题，icon问题是我浏览器问题，换了360就可以了，donate只放到单独页面里面，这个文档里也有详细说明，一开始看的不认真。我再重新打开这个issue，防止有和我一样粗心的人，后续有问题再请教前辈，再次感谢！
