### ISSUE TITLE
http://localhost:4000/#{theme.links[i].url} 友情链接地址栏出现这个

### ISSUE THREAD

**Issue by shp87285604** [tufu9441/maupassant-hexo#346]
http://localhost:4000/#{theme.links[i].url} 地址栏出现了这个
下面是我写的_config.yml 目录里的links
links:
  - title: 屠夫9441的博客
    url: https://www.haomwei.com/technology/maupassant-hexo.html#主题安装
  - title: 云淡风轻
    url: https://ioliu.cn/
  - title: site-name3
    url: http://www.example3.com/
上面两个有网址的和下面原始例子的都不能正确获取到地址  
我用的hexo s 做的临时服务器  
hexo新手 希望能得到您的回复 非常感谢

**Comment by tufu9441** [comment]
可能更新pug后格式上面还有点bug，但我要过几天才能修复。

**Comment by tufu9441** [comment]
我看了一下并不会出现这种情况啊，你`hexo-renderer-pug`是否正确安装了？如果没问题的话，可以将`/layout/widget/links.pug`里的代码贴出来我看一下，并给出一个线上demo。

**Comment by shp87285604** [comment]
收到您的回复很高兴 按照您的提示 提供如下信息
下面是links.pug
.widget
  .widget-title
    i(class='fa fa-external-link')= ' ' + __('blogroll')
  - for (var i in theme.links)
    ul
    a(href='#{theme.links[i].url}' title='#{theme.links[i].title}' target='_blank') #{theme.links[i].title}

下面是依赖package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "^3.0.0",
    "hexo-generator-archive": "^0.1.0",
    "hexo-generator-category": "^0.1.0",
    "hexo-generator-feed": "^1.0.1",
    "hexo-generator-index": "^0.1.0",
    "hexo-generator-tag": "^0.1.0",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-pug": "^0.0.5",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-renderer-sass": "^0.1.2",
    "hexo-renderer-stylus": "^0.2.3",
    "hexo-server": "^0.1.2"
  }
}
不知道这个依赖能不能证明我的hexo-renderer-pug已经安装成功了？

**Comment by shp87285604** [comment]
![qq 2](https://user-images.githubusercontent.com/29415590/34468348-e4e2d1ec-ef41-11e7-8a64-5c6b43da4939.png)
![qq 3](https://user-images.githubusercontent.com/29415590/34468350-e839523a-ef41-11e7-8022-10ee4c122914.png)

**Comment by tufu9441** [comment]
你的代码已经不是最新版的了，更新一下试试。
```
.widget
  .widget-title
    i(class='fa fa-external-link')= ' ' + __('blogroll')
  - for (var i in theme.links)
    ul
    a(href=theme.links[i].url title=theme.links[i].title target='_blank') #{theme.links[i].title}
```
