### ISSUE TITLE
RSS 失败

### ISSUE THREAD

**Issue by SnailDove** [tufu9441/maupassant-hexo#349]
按照网上大家对这个主题添加rss成功经验，我模仿他们的操作流程是：
npm install hexo-generator-feed

主题配置文件没有修改

```
  - page: rss
    directory: atom.xml
    icon: fa-rss
```
博客根目录下的配置文件的url也已经修改
hexo clean hexo generate hexo deploy 不行
**有什么流程问题嘛大神们？**

如果在博客根目录的配置文件添加下面，也不行：

```
# Extensions
## Plugins: http://hexo.io/plugins/
#RSS订阅
Plugins:
- hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20
```

**Comment by tufu9441** [comment]
这种Issue提在https://github.com/hexojs/hexo-generator-feed 可好？

**Comment by SnailDove** [comment]
我只是想问你们也是这样操作嘛，然后结果如何？

**Comment by tufu9441** [comment]
结果完全正常。

**Comment by SnailDove** [comment]
最重要的是，我如何排除是主题本身问题还是feed这个插件的问题，你回复我才知道嘛，看你有点生气

**Comment by SnailDove** [comment]
因为有些插件你们内置了，有些又要自己安装，也就是有些东西只需要配置而有些东西需要从头配起来 我区分不了，很抱歉。如果能写的更详细一些或许我等小白更容易上手

**Comment by SnailDove** [comment]
**hexo 重头到尾安装 竟然rss可以了 amazing！！**
