### ISSUE TITLE
分享区有错误，

### ISSUE THREAD

**Issue by Petelin** [tufu9441/maupassant-hexo#35]
my first
2016-01-03 | 分类于 分类
aaa
#标签

分享到：
微博
QQ空间
腾讯微博
微信

页面大致是这样，最后那个分享到自动就出现了，而且鼠标移动到【分享到】 又会出现：
分享到：
微博
QQ空间
腾讯微博
微信
新浪微博
QQ空间
搜狐微博
人人网
网易微博
腾讯微博
开心网
豆瓣网
QQ
美丽说
蘑菇街
百度
淘宝
谷歌
微信
点点网
花瓣网
堆糖
有道云笔记
朋友网
Facebook
Twitter
Linkedin
MSN
多说分享插件

没看到有能设置的地方？

**Comment by tufu9441** [comment]
我从来没有遇到过这种情况啊，这个分享是多说的功能，正确填写了多说的short_name之后才可以使用。是否有能重现你所说问题的url让我看看？

**Comment by Petelin** [comment]
这样啊，我当时随便填的一个，应该是代码没做这方面的检测，我注册之后填进去好了
