### ISSUE TITLE
deploy 后在 vps 上 nginx 转发无主题样式

### ISSUE THREAD

**Issue by renchunxiao** [tufu9441/maupassant-hexo#356]
地址：
https://renchunxiao.com/

在本地 hexo s 调试，是有样式的。

但是通过 hexo clean & hexo g -d 部署后，在 vps clone 下来，通过 nginx 转发后无样式。

F12 看了下资源都加载成功了。

**Comment by tufu9441** [comment]
这怎么着都不应该主题的原因吧，应该是你VPS配置的问题。

**Comment by renchunxiao** [comment]
解决了，VPS 静态资源的 Content-type 没设置对。感谢~
