### ISSUE TITLE
从cdn.bootcss.com加载css有时候很慢

### ISSUE THREAD

**Issue by YiweiNiu** [tufu9441/maupassant-hexo#357]
您好，

感谢您开发了这么 nice 的主题。我发现使用您的主题时，有时候网页加载很慢，检查之后发现主要是在加载 cdn.bootcss.com 的css。我想能不能把这些需要的 css 下载到本地，这样子就不会每次浪费时间去加载别的网站的 css 了。

**Comment by tufu9441** [comment]
当然可以，你完全可以自己把这些css存到本地，然后在引用的地方做出相应修改。
