### ISSUE TITLE
增加algolia

### ISSUE THREAD

**Issue by yanickxia** [tufu9441/maupassant-hexo#360]
提议增加 algolia 支持

**Comment by yannxia** [comment]
@tufu9441   是一个搜索插件， 在 [Next](https://github.com/iissnan/hexo-theme-next) 有集成。
在这里有相关的JS [algolia-search.js](https://github.com/iissnan/hexo-theme-next/blob/master/source/js/src/algolia-search.js)，因为我不太会写，只能提议了。

**Comment by tufu9441** [comment]
看了一下，嫌麻烦弄不动了，看有没有人提PR吧😂

**Comment by yannxia** [comment]
@tufu9441   待我找完工作，我尝试撸一发 :-D

**Comment by tufu9441** [comment]
哈哈，那等你的好消息，加油😂
