### ISSUE TITLE
求助关于“本地搜索指向链接”和”文章目录位置"的两个问题

### ISSUE THREAD

**Issue by Xiaopika** [tufu9441/maupassant-hexo#361]
### 第一个问题
![](https://camo.githubusercontent.com/60f541a58ff6c08e9ba288373c0bbde1d82e4232/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f383361313662366567793166706832316b637633716a3230387930356b3734372e6a7067)

如图，搜索结果的标题 hello world 的 href 链接直接指向博客首页，而不是具体的文章链接。
所有的搜索结果标题链接都指向的是博客首页
<br>

![](https://camo.githubusercontent.com/073bb23ce6bf1d6aa2758ddb1a162f0d542665cb/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f3833613136623665677931667068323863656e62616a3230646b30336833796b2e6a7067)

感觉好像是 HTML 或者 CSS 上写法的问题？
希望大佬能不吝赐教，指点一二，感谢！
<br>

### 第二个问题
![](https://ws1.sinaimg.cn/large/83a16b6egy1fph35bxgmxj20mb0dudge.jpg)
生成目录以后变成这样子，排版不是很美观
<br>

希望能像这样：
![](https://ws1.sinaimg.cn/large/83a16b6egy1fph374qgjbj20lh0apmy6.jpg)
<br>

不知道怎么调整，希望大佬能不吝赐教，指点一二，感谢！

**Comment by tufu9441** [comment]
可能是css的问题。第二个禁用canvas也是这样的效果吗？

**Comment by Xiaopika** [comment]
@tufu9441 我刚刚试了一下，改成 false 以后仍然是这样

**Comment by tufu9441** [comment]
那就检查下载入的css跟最新版的是否完全一致吧。

**Comment by Xiaopika** [comment]
/笑哭 我重新 clone 了该主题，完全替换，没改动任何设置，两个问题仍然未解决，我需要重新装一次 HEXO/NODEJS 试试吗

**Comment by tufu9441** [comment]
嗯，全都重新安装一下试试吧。

**Comment by Xiaopika** [comment]
另外顺便提醒你一下，可以把这个链接撤掉了，因为。。。变成了一个不可描述的网站。

![](https://ws1.sinaimg.cn/large/83a16b6egy1fphahn8auoj20mo0ee74v.jpg)

**Comment by tufu9441** [comment]
#352

**Comment by Xiaopika** [comment]
好的，我挂代理重新试一下

**Comment by Xiaopika** [comment]
根据您说的，同样会报错但使用起来没问题，所以不知道还有可能是什么原因呢？

**Comment by Xiaopika** [comment]
唉，折腾了这么久还是老样子，一个问题都没有解决，崩溃了/笑哭

**Comment by Xiaopika** [comment]
第一个问题解决了！
根据对比你博客生成的Search.xml和我的博客生成的之间的区别，发现了你的xml中链接均为<url></url>形式，而我的是<link ref   />的形式，因此我把 `./node_modules\hexo-generator-search\templates\search.xml`中的<link ref   />全部改成<url></url>形式就完美解决了！
也给后来的人参考！

**Comment by Xiaopika** [comment]
第二个问题也已经解决：
减少标题文字 并 去掉开头第一句的<font>标签，完美解决。

![](https://ws1.sinaimg.cn/large/83a16b6egy1fphcy3dhjwj20rd09waba.jpg)
<br>
<br>
![](https://ws1.sinaimg.cn/large/83a16b6egy1fphczan0drj20nv0bjwf8.jpg)
<br>
<br>
感谢屠大的耐心指导与无私付出，因为我自己的蠢问题占用了您不少时间非常抱歉。

**Comment by Xiaopika** [comment]
说错了，不是<font>标签导致的，是代码块符号「`」引起的，去掉后OK。可能是markdown语法与主题渲染有关的BUG，这个深层原因我就无力探索了。
