### ISSUE TITLE
希望增加一个音乐/视频播放器的模块

### ISSUE THREAD

**Issue by Xiaopika** [tufu9441/maupassant-hexo#362]
比如可以：
http://dplayer.js.org/
https://aplayer.js.org/

由前端大神 Diygod 维护的 APlayer/DPlayer 项目

**Comment by ChoicePhobiaDisorder** [comment]
加可以，但是你想加在哪里呢，特别是自适应

**Comment by Xiaopika** [comment]
/捂脸笑哭 不太清楚啊，不知道好不好实现，就像这种效果：
[DITGOD 的博客](https://diygod.me/best-players-in-hexo/)
（也是 Hexo 程序）

**Comment by tufu9441** [comment]
这个可以根据个人需求自己添加，没考虑过搞这么复杂。我见过有些用户自己用的。

**Comment by ChoicePhobiaDisorder** [comment]
我看了一下，实现通用的比价难，自己用还可以，但是改成一般用户使用比较难

**Comment by tufu9441** [comment]
我的建议也是，某篇文章里需要用到就自己插入html代码，或者仿照已有widget在侧边栏添加一个。

**Comment by Xiaopika** [comment]
明白了，感谢两位大大
