### ISSUE TITLE
反馈一个格式上的小问题

### ISSUE THREAD

**Issue by Xiaopika** [tufu9441/maupassant-hexo#364]
这是在博客首页的日期：是YY-MM-DD的形式
![](https://ws1.sinaimg.cn/large/83a16b6egy1fpkkedcklaj209905n749.jpg)

<br>
进入文章详情后日期格式就变成了：英语月份 DD, YY的形式成了：

![](https://ws1.sinaimg.cn/large/83a16b6egy1fpkkg9v5xgj20bj06o74c.jpg)

<br>

这个问题有fix的价值吗。。格式不统一强迫症看着有点难受，想自己改改却也不知道在哪里改，config.yml里改了没用

**Comment by tufu9441** [comment]
这是我个人审美故意调整成这样的，想改的话去post.pug里面修改 .post-meta= page.date.format('ll')

**Comment by Xiaopika** [comment]
好的，感谢

**Comment by Xiaopika** [comment]
那个。。。屠大。。。能稍微提示一下具体怎么改吗。。。这个语法看不太懂。。。

**Comment by Xiaopika** [comment]
OK了，感谢屠大！
