### ISSUE TITLE
首页，每篇文章的间隔不明显，希望作者能弄下哈

### ISSUE THREAD

**Issue by AriaLyy** [tufu9441/maupassant-hexo#366]
![image](https://user-images.githubusercontent.com/10437293/37835256-af1ab7e4-2eea-11e8-8854-43e277cc8733.png)

**Comment by tufu9441** [comment]
我觉得还好。你如果开头就有小标题的话，建议你在`front-matter`中设置一个description项，这样首页显示比较美观。

**Comment by AriaLyy** [comment]
作者，你好，请问front-matter是在哪个地方设置的？

**Comment by michaelHL** [comment]
@AriaLyy 使用Hexo写作的基本点，参考[Hexo文档](https://hexo.io/docs/front-matter.html)

**Comment by Xiaopika** [comment]
我也觉得首页上博文之间的间隔太小了，可以考虑在layout上增加一个空行或者分割线吗？
![](https://ws1.sinaimg.cn/large/83a16b6egy1fpzkf0w8scj20u01u1qbb.jpg)

**Comment by counter2015** [comment]
+1
在hexo文档中找不到设置`description`的地方
下面这个我设置过了
![](http://ww1.sinaimg.cn/large/005OIjE6ly1fz9gzothpxj30n80czwfj.jpg)

展示效果不太理想
![](http://ww1.sinaimg.cn/large/005OIjE6ly1fz9h1rjl84j30q90hzwfs.jpg)

**Comment by XiaoPika** [comment]
> +1
> 在hexo文档中找不到设置`description`的地方
> 下面这个我设置过了
> 
> 展示效果不太理想
> 


在head-matter上配置description，如下图：

![qq 20190303163329](https://user-images.githubusercontent.com/10910848/53692890-6fd27200-3dd2-11e9-958d-513d19e3c123.png)

@counter2015

**Comment by counter2015** [comment]
@XiaoPika 谢谢，刚弄明白了
