### ISSUE TITLE
博客样式问题

### ISSUE THREAD

**Issue by caojiurui** [tufu9441/maupassant-hexo#368]
第一次玩这个不太熟练，问下我这边的项目启动后好像样式有问题是什么情况？大家出现过吗？而且我看了下服务的css，好像和主题里的css不一样，也是懵逼了啊。
![image](https://user-images.githubusercontent.com/16349022/37898800-5974204e-311c-11e8-824f-ebe79dd0cdd5.png)

**Comment by ChoicePhobiaDisorder** [comment]
这个是需要安装插件才能正常渲染

**Comment by caojiurui** [comment]
请问下是什么插件啊？我试了下hexo默认的主题是ok的。

**Comment by ChoicePhobiaDisorder** [comment]
hexo-renderer-pug
hexo-renderer-sass

**Comment by caojiurui** [comment]
这个在blog目录下执行么？好像不行啊，还是那样
![image](https://user-images.githubusercontent.com/16349022/37899719-e9825686-311e-11e8-99ea-58132e467c7e.png)

**Comment by ChoicePhobiaDisorder** [comment]
你需要渲染，hexo g

**Comment by caojiurui** [comment]
@ChoicePhobiaDisorder hexo g 完毕后再启动 hexo server 还是不行，一脸懵逼的我。真是纳了闷了，为啥执行完毕后的css就变了，和主题里的不一样

**Comment by caojiurui** [comment]
@ChoicePhobiaDisorder 不好意思，找到问题了，是最初的时候没安装sass插件，后面的时候有缓存，需要先 hexo clean 清理下再 hexo s 就ok了，第一天玩这个，不太熟悉，多谢解答啦。
