### ISSUE TITLE
about?

### ISSUE THREAD

**Issue by xiaolong3000** [tufu9441/maupassant-hexo#37]
where is about/  and where is atom.xml?
How to setting?

**Comment by tufu9441** [comment]
Create an `about` folder including an `index.md` in `/source`.
https://github.com/hexojs/hexo-generator-feed

**Comment by linggan100** [comment]
搭车问个问题，文章里放图片我知道怎么弄了，建了个文件夹把图片放进去，路径正确。同样的方法在about页面里不能用，生成文件之后路径不对，请问正确的方法是？
