### ISSUE TITLE
objective-c代码高亮问题

### ISSUE THREAD

**Issue by huluo666** [tufu9441/maupassant-hexo#370]
使用objective-c代码无法高亮，使用objectivec正常，希望像GitHub一样能兼容下"objective-c"与"objectivec"这2种写法，在Typora和sublime插件markdownextend使用的是"objective-c"字段高亮，这样编辑时能看到发布也能
```objective-c
#import <Foundation/Foundation.h>
@interface Person : NSObject
@property (nonatomic,copy)    NSString *userName;
@end
```

**Comment by tufu9441** [comment]
试着搞了一下，没弄出来，很奇怪😂……像同时支持c和cpp就可以，不知道为什么。
