### ISSUE TITLE
想问一下为什么我的谷歌站内搜索搜不到东西？

### ISSUE THREAD

**Issue by thereisnowinter** [tufu9441/maupassant-hexo#372]
我的网站是https://thereisnowinter.github.io/
比如我想搜索**bind**这个关键词，但却什么也搜不到，显示为

> Your search - bind site:https://thereisnowinter.github.io - did not match any documents.

但我明明写了一篇标题包含**bind**的文章，所以想请教一下？
谢谢了。

**Comment by ChoicePhobiaDisorder** [comment]
GitHub是屏蔽搜索，你可以使用静态搜索方法

**Comment by thereisnowinter** [comment]
@ChoicePhobiaDisorder 不好意思，能不能展开解释一下？我没有谷歌到你说的东西。

**Comment by ChoicePhobiaDisorder** [comment]
你使用的是github的服务，也就是使用username.github.io,但是github是禁止搜索爬取信息，所以是搜索不了，但是你可以使用插件，生成静态的文件，这样也可以在博客内搜索，不依赖与谷歌或者百度，是纯本地搜索

**Comment by ChoicePhobiaDisorder** [comment]
如果你想收录你自己的网站，你需要有自己的域名和服务器

**Comment by thereisnowinter** [comment]
@ChoicePhobiaDisorder 感谢回复，如果我不买域名和服务器，只能通过下面这种方式搜索了？

> self_search - 基于jQuery的本地搜索引擎，需要安装hexo-generator-search插件使用。

**Comment by ChoicePhobiaDisorder** [comment]
是的，而且只作用于自己博客的搜索框，博客还是不会被谷歌百度搜索到

**Comment by thereisnowinter** [comment]
@ChoicePhobiaDisorder 非常感觉，现在懂了。
