### ISSUE TITLE
无法使用主题

### ISSUE THREAD

**Issue by luoyhang003** [tufu9441/maupassant-hexo#38]
在 0.0.0.0:4000 页面下显示：

extends base - var current_title = page.title || tag.name || category.name || site.title block title title= config.title + " | " + config.subtitle block content for post in page.posts.toArray() .post h2.post-title include _partial/helpers a(href=url_for(post.path)) +title(post) .post-meta= post.date.format(config.date_format) if theme.duoshuo span.ds-thread-count(data-thread-key=post.path) if theme.disqus span.disqus-comment-count(data-disqus-identifier=post.path) if post.description .post-content != post.description else if post.excerpt .post-content != post.excerpt else if post.content - var br = post.content.indexOf('\n') if br < 0 .post-content != post.content else .post-content != post.content.substring(0, br) p(class="readmore") a(href=url_for(post.path))= __('Readmore') include _partial/paginator if theme.disqus script(id='dsq-count-scr' src='//#{theme.disqus}.disqus.com/count.js' async)

**Comment by tufu9441** [comment]
See #7
