### ISSUE TITLE
语法高亮是hexo的自带的吗，想用hexo自带的highlight.js方案

### ISSUE THREAD

**Issue by zhoumq** [tufu9441/maupassant-hexo#385]
不太满意theme所带的语法高亮显示效果，google了一下，发现新版Hexo theme本身支持代码高亮，其采用的方案是：highlight.js。但是如何去掉themem的代码高亮方案呢。

**Comment by jiacai2050** [comment]
https://github.com/tufu9441/maupassant-hexo/blob/master/source/css/style.scss#L946

除了这里列举的语言外，能支持其他语言代码高亮嘛？

**Comment by jiacai2050** [comment]
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/commit/be5da65436a59e2e6f9d0c9f7d58c015f81a1ed9

这里直接加上了 Clojure 代码高亮，怎么 port 到这边呢？ scss 不是很了解。

**Comment by tufu9441** [comment]
@jiacai2050 加上了Clojure和Lisp的代码高亮。

**Comment by jiacai2050** [comment]
## Before
![image](https://user-images.githubusercontent.com/3848910/57566658-4ea98580-7402-11e9-9211-bb795413b05f.png)

## After
![image](https://user-images.githubusercontent.com/3848910/57566654-3f2a3c80-7402-11e9-80a6-32cafd231d6f.png)

赞，效果好多了。顺便留个链接，便于 clj 同学交流
- https://liujiacai.net/tags/Clojure/
