### ISSUE TITLE
https://api.github.com/xx/xx/xxx/issues 422

### ISSUE THREAD

**Issue by xwdz** [tufu9441/maupassant-hexo#386]
使用gitment评论，配置如下
`
gitment:
  enable: true ## If you want to use Gitment comment system please set the value to true.
  owner: xwdz ## Your GitHub ID, e.g. username
  repo: xwdz.github.io ## The repository to store your comments, make sure you're the repo's owner, e.g. imsun.github.io
  client_id: c62ab72e41cea1fc64ce ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: 2b4319c22eabf970e7f8301c302934e6a641dbf4 ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
`
点击init gitment报错，最后查到报错[`gitment issues`](https://github.com/imsun/gitment/issues/58),需要修改gitment id ，最后找到本地gitment.browser.js 文件修改id，还是无效

**Comment by tufu9441** [comment]
@ChoicePhobiaDisorder

**Comment by ChoicePhobiaDisorder** [comment]
已经明白原因，需要多个id参数

**Comment by ChoicePhobiaDisorder** [comment]
@xwdz 我想是你使用了自己域名原因，但是我无法实验，你可以使用github子域名试试吗？

**Comment by ChoicePhobiaDisorder** [comment]
作者使用`location.href`来获取当前地址，我认为你使用了自己域名导致不成功.

**Comment by xwdz** [comment]
@ChoicePhobiaDisorder  使用github子域名的意思是? 我直接使用github子域名访问? 刚试了下还是报错不能兼容

**Comment by xwdz** [comment]
@ChoicePhobiaDisorder 使用github子域名的意思是? 我直接使用github子域名访问? 刚试了下还是报错, 没有办法兼容自定义域名吗?
