### ISSUE TITLE
访问cdn.bootcss.com加载CSS、JS被拦截返回403

### ISSUE THREAD

**Issue by zhufuhua** [tufu9441/maupassant-hexo#387]
cdn.bootcss.com对请求设置了referer拦截校验，如果使用域名但不在规则内，如个人使用的 *.top *.cc 

是否可以将需要cdn访问的地方增加本地文件，比如cdn加载文件不通时，从本地加载

![1526611168395](https://user-images.githubusercontent.com/11677792/40213614-e852b736-5a88-11e8-96b3-72131049883b.jpg)

**Comment by tufu9441** [comment]
是可以考虑，但似乎实现起来不方便，所以对CDN加载有困难的用户还是自己把静态文件下载到本地然后手动修改一下吧

**Comment by tufu9441** [comment]
https://www.v2ex.com/t/455850
可以考虑切换成其它CDN提供商的了……
