### ISSUE TITLE
行内代码过长导致其左右的文字分散对齐

### ISSUE THREAD

**Issue by zhuoshuai** [tufu9441/maupassant-hexo#388]
在使用 **有序列表** 时 一句过长的行内代码导致代码左右的文字对齐的很分散

**Comment by tufu9441** [comment]
可能是CSS中`text-align`或者`word-break`方面的问题？最近也没有时间细细调试……

**Comment by XiaoPika** [comment]
@tufu9441  +1，这个问题要折磨死我 /笑哭
![Screenshot.png](https://i.loli.net/2018/08/19/5b7975059a5f7.png)

**Comment by tufu9441** [comment]
> @tufu9441 +1，这个问题要折磨死我 /笑哭
> ![Screenshot.png](https://camo.githubusercontent.com/464cd4db93e4c9edc753fa64d701b56a2c697b1e3c5fb0b9e30bd08ab886881e/68747470733a2f2f692e6c6f6c692e6e65742f323031382f30382f31392f356237393735303539613566372e706e67)

所以这个问题后来你解决了吗

**Comment by AkazaRenn** [comment]
> > @tufu9441 +1，这个问题要折磨死我 / 笑哭
> > ![Screenshot.png](https://camo.githubusercontent.com/464cd4db93e4c9edc753fa64d701b56a2c697b1e3c5fb0b9e30bd08ab886881e/68747470733a2f2f692e6c6f6c692e6e65742f323031382f30382f31392f356237393735303539613566372e706e67)
> 
> 所以这个问题后来你解决了吗

給 p 元素加 `text-align: left` 可以解決，但是不知道這樣會怎麽影響向右對齊的語言
