### ISSUE TITLE
这个gitalk得初始化issues怎么用

### ISSUE THREAD

**Issue by dengtongcai** [tufu9441/maupassant-hexo#389]
一直没整明白每个md怎么和isues绑定起来

**Comment by mingjiezhou** [comment]
同问，点击登陆后就跳转到博客首页了，回调错误

**Comment by ChoicePhobiaDisorder** [comment]
如果不行可以用gitment，渲染网页上传后打开博客即可看见评论，但是需要初始化，登陆自己账号后点击初始化即可，初始化后就可以正常使用，如果你的文章比较多，可以选择使用脚本[issues](https://github.com/imsun/gitment/issues/5)

**Comment by ChoicePhobiaDisorder** [comment]
每篇文章都需要初始化
