### ISSUE TITLE
markdown支持显示不对

### ISSUE THREAD

**Issue by imkratos** [tufu9441/maupassant-hexo#39]
楼主，你又改了什么。。新的主题  md的样式支持的不全了。。`这样的不支持了` ```java 代码也换了 ```

**Comment by tufu9441** [comment]
什么也没动啊，我这里测试的没问题啊。

**Comment by imkratos** [comment]
是么，，那我也没改什么啊。怎么我的样式有的对有的不对了。

**Comment by tufu9441** [comment]
哪里不对了，截图看下。

**Comment by tufu9441** [comment]
以你最新的[一篇日志](http://imkratos.github.io/2016/01/07/%E9%98%85%E8%AF%BBActiveMQ%E6%BA%90%E7%A0%81%E6%80%BB%E7%BB%93/)为例，我看到里面代码高亮的内容是正常的啊。

**Comment by imkratos** [comment]
恩，好吧，我感觉可能是md 插件的问题，有些效果没有显示，我自己再去研究看下吧。和github自带的md插件显示的还是有差别的

**Comment by tufu9441** [comment]
请问现在还存在显示的问题么？刚才又更新了一下代码高亮部分的CSS，依然是从[tranquilpeak](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak)搬过来的，跟之前的样式有所不同。

**Comment by imkratos** [comment]
楼主，你知道github用的什么css库么[我的GITHUBmd](https://github.com/imkratos/source-learning/blob/master/java/activemq/activemq.md)，你看这里的很多样式，在咱们这个主题中是没有显示出来的

**Comment by tufu9441** [comment]
我仔细对比了一下，你所说的没有显示的样式就是指“代码分析”这一段中代码的背景吧，如下图：
![qq 20160113160335](https://cloud.githubusercontent.com/assets/6790361/12288416/4836a8fa-ba0f-11e5-9430-3d04c2beb0c1.png)

我把你的文章内容拷贝到本地测试了一下，是因为你写的内容段与段之间没有额外空一行（Markdown语法的分段要求），如果加上必要的空格并删除自然段内行与行之间不必要的空格，显示得完全正常：
![Screen Capture](https://ooo.0o0.ooo/2016/01/13/5696068806b1d.png)

**Comment by imkratos** [comment]
![image](https://cloud.githubusercontent.com/assets/3302461/12288670/278aa442-ba11-11e5-9aba-04e3b072cf5d.png)

![image](https://cloud.githubusercontent.com/assets/3302461/12288677/388c2842-ba11-11e5-9950-6a0c0dac448c.png)


![image](https://cloud.githubusercontent.com/assets/3302461/12288691/5e074d18-ba11-11e5-8656-478b21aa9fcb.png)


![image](https://cloud.githubusercontent.com/assets/3302461/12288683/4feb6462-ba11-11e5-8fc9-e825539f81cd.png)


可能由于GITHUB本身的样式匹配更加灵活？因为我在本地是用ATOM写的，所以在官方那是可以显示正常的。

那我再去调整一下我的代码吧，多谢楼主耐心解答啊。

**Comment by tufu9441** [comment]
嗯，你可以更新一下，现在代码高亮的样式已经和Github最新的保持一致了。

**Comment by tufu9441** [comment]
不过我觉得对内容的识别和渲染应该属于markdown引擎自身的问题，也就是hexo本身的原因，跟主题的CSS应该没什么关系。

**Comment by imkratos** [comment]
我也很奇怪啊，同样的东西，渲染出来的效果不一样。。现在还不太了解hexo这个玩意的机制。

**Comment by tufu9441** [comment]
https://github.com/hexojs/hexo/issues/28

**Comment by tufu9441** [comment]
我又仔细看了一下，还确实跟主题的CSS有关系，我之前没有把代码的样式添加到列表的内容中，因此之前列表中的代码会没有背景。现在更新了，应该没问题了。
