### ISSUE TITLE
Hello, Tufu. May I know how to change the 'back-to-top' rocket icon to 'ukagaka panel'?

### ISSUE THREAD

**Issue by woshiamiaojiang** [tufu9441/maupassant-hexo#392]
Hi, Tufu. I wanna add the 'ukagaka panel' web plugin to my maupassant-hexo blog lately. 
Here is the demo's link of ukagaka panel:
http://morris821028.github.io/mblog-ukagaka/
However, the current problem I encountered is that I hardly locate the file of 'back-to-top' rocket icon. I will appreciate it a lot if you could give me a few hints of maybe how to replace it with the 'ukagaka panel'.

**Comment by tufu9441** [comment]
The rocket icon is in the `style.scss`, in a `data:image` format.
