### ISSUE TITLE
在chrome浏览器中，有的字体图标无法显示，出现跨域访问的问题

### ISSUE THREAD

**Issue by yxtwkk** [tufu9441/maupassant-hexo#395]
![image](https://user-images.githubusercontent.com/24383736/41187273-7c06e316-6bd8-11e8-9f84-71fbb45fbe22.png)
如题，如上图
但是在safari中可以正常显示
![image](https://user-images.githubusercontent.com/24383736/41187276-8b4920d2-6bd8-11e8-8358-147eaed39834.png)

**Comment by tufu9441** [comment]
发现了，这个应该是[bootcdn](http://www.bootcdn.cn)的问题，近期打算更换静态资源的cdn，如果着急的话自己改一个别家的也可以。

**Comment by tufu9441** [comment]
我这边拿Chrome无痕窗口又恢复正常了。

**Comment by yxtwkk** [comment]
哇！神奇！如果要自己换cdn，在哪个文件里修改哪部分呢？（前端小白不懂哇！哭😢），我其实不急的，等tufu更新后在pull一个新版本也行呢

**Comment by tufu9441** [comment]
那既然bootcdn也没有出什么大问题，就先不动了。想改就去找header.pug和其它文件里的css和js资源的引用地址。
