### ISSUE TITLE
timeline - 网站历史时间线，在页面front-matter中设置layout: timeline可显示。

### ISSUE THREAD

**Issue by qiqingfu** [tufu9441/maupassant-hexo#400]
这个在哪里添加呀
页面front-matter 找不到

**Comment by XiaoPika** [comment]
去读 Hexo 官方文档
https://hexo.io/docs/front-matter.html

**Comment by XiaoPika** [comment]
![qq 20180731183039](https://user-images.githubusercontent.com/10910848/43454509-dd063384-94ef-11e8-8a99-757e8344f16c.jpg)

**Comment by qiqingfu** [comment]
十分感谢

**Comment by XiaoPika** [comment]
close plz
