### ISSUE TITLE
最新版的 self_search 在 hexo g 的时候会报错

### ISSUE THREAD

**Issue by yhf2lj** [tufu9441/maupassant-hexo#406]
你好，系统是win10的ubuntu子系统

现象是开启self_search的时候，

ERROR /mnt/d/yhf2lj/themes/maupassant/layout/_partial/after_footer.pug:34
    32|   script(type='text/javascript', src=url_for(theme.js) + '/search.js' + '?v=' + theme.version)
    33|   script.
  > 34|      var search_path = '#{config.search.path}';
    35|      if (search_path.length == 0) {
    36|         search_path = 'search.xml';
    37|      }

Cannot read property 'path' of undefined
TypeError: /mnt/d/yhf2lj/themes/maupassant/layout/_partial/after_footer.pug:34
    32|   script(type='text/javascript', src=url_for(theme.js) + '/search.js' + '?v=' + theme.version)
    33|   script.
  > 34|      var search_path = '#{config.search.path}';
    35|      if (search_path.length == 0) {
    36|         search_path = 'search.xml';
    37|      }

**Comment by unihon** [comment]
检查下配置，我这些天刚弄，可以用

**Comment by unihon** [comment]
这个是路径问题，self_search的默认配置在本地应该是没问题的，如果放github上面就可能用不了。
按插件的配置文档，改别的路径就行了，可以在项目主目录下新建一个目录。
```
search:
  path: your path/search.xml
  field: post #可以默认不理
  content: true  #可以默认不理
```
[self_search插件地址](https://github.com/wzpan/hexo-generator-search)
[demo](https://github.com/unihon/unihon.github.io/tree/master)
