### ISSUE TITLE
多说 分享功能 样式不对

### ISSUE THREAD

**Issue by edagarli** [tufu9441/maupassant-hexo#41]
你说
“刚发现新版本的一个#号变成中文的了”

不知道你修改哪里了。

**Comment by tufu9441** [comment]
之前在base.jade里，现在挪到after_footer.jade里了，早就改了。不过刚才发现还有一个地方不对，即多说js的地址输错了。稍后更新一下。

**Comment by tufu9441** [comment]
你再试一下。

**Comment by edagarli** [comment]
不行

**Comment by tufu9441** [comment]
你确定duoshuo shortname填对了么？主题配置发一下。

**Comment by edagarli** [comment]
fancybox: true ## If you want to use fancybox please set the value to true
duoshuo: edagarli ## Your duoshuo_shortname, e.g. haomwei
disqus:  ## Your disqus_shortname, e.g. haomwei
google_search: false ## Use Google search, true/false
baidu_search: true ## Use Baidu search, true/false
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: 47be17dedd3258963b6518c2ffbd5e1d ## Your Baidu Analytics tracking id, e.g. 8006843039519956000

menu:
  - page: home
    directory: .
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments

**Comment by tufu9441** [comment]
奇怪，我在本地测试完全正常啊，如图。能否重现一个在线的demo，让我看一下网页的代码哪里有问题。

![ScreenCapture at Thu Jan 14 10:26:12 CST 2016.png](https://ooo.0o0.ooo/2016/01/13/569707de989b3.png)

**Comment by edagarli** [comment]
刚才去找了下原因没找到。

你也看看http://blog.edagarli.com

**Comment by tufu9441** [comment]
我看到了，目测是你填的这个shortname没有在多说网站上注册好？你看看#35

**Comment by edagarli** [comment]
我第三方已经注册了
<img width="617" alt="1" src="https://cloud.githubusercontent.com/assets/5710228/12314545/16cec812-baad-11e5-866b-a50672f2a25d.png">

**Comment by tufu9441** [comment]
这个界面截图看一下：
![qq 20160114105550](https://cloud.githubusercontent.com/assets/6790361/12314590/6e114ff0-baad-11e5-8da2-44d406436bde.png)

**Comment by edagarli** [comment]
~~~需要自己参加站点

**Comment by tufu9441** [comment]
对啊，需要添加站点才能设置你的shortname，并不是你注册的用户名。
