### ISSUE TITLE
不蒜子无法使用问题

### ISSUE THREAD

**Issue by haitao-hjc** [tufu9441/maupassant-hexo#424]
@tufu9441 
因为不蒜子域名更改的原因需将主题下`/layout/post.pug`中的的部分代码修改：
将其中的
`script(src='https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js', async)`
改为：
`script(src='https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js', async)`

**Comment by tufu9441** [comment]
改过来了。
