### ISSUE TITLE
是否考虑让「maupassant-hexo」支持「汉字标准格式」，现存「标点出现在行首」等排版问题

### ISSUE THREAD

**Issue by Ryouissei** [tufu9441/maupassant-hexo#428]
可否考虑让 maupassant-hexo支持「[汉字标准格式](https://css.hanzi.co/manual/anzhuang_yu_qiyong)」？

主题现存一些排版问题，比如：逗号等标点符号会出现在行首，中英文之间的间隔稍密等。所以，汉字标准格式是一套印刷品般的汉字排版框架，可以解决这些问题，主题「[NEXT](https://github.com/iissnan/hexo-theme-next)」已经集成此框架。

以下引用自官网：
> 通常，一般網頁需要引用二個文件來啓用「漢字標準格式」——han.min.css（或使用Sass滙入）及han.min.js（或使用JavaScript模組框架），後者（腳本文件）可依網站的需求選用。
> 
> <link rel="stylesheet" href="path/src/css/han.min.css">
> 可依需求選用的腳本文件，
> 
> <script src="path/src/js/han.min.js"></script>

请参考：
[使用“汉字标准格式”更好地排版中文](https://codehut.me/posts/Y3Vyc29yOjc=)
[Han Support - NEXT](https://github.com/geekrainy/hexo-theme-next/commit/812dfd34642c42a3e91833f87abdcad7e0a30762)

**Comment by tufu9441** [comment]
我试验了一下，直接引入脚本会干扰Font Awesome图标的显示，不知如何才能避免这个问题。

**Comment by Ryouissei** [comment]
行首和行尾出现错误的标点符号排版的这个问题解决了。
不需要引用“汉字标准格式”来解决。
参考：https://imweb.io/topic/59fe82991f0e50753869bf8c

只要把` style.scss `的`.post`和`.post.content`里，调整或者增加成下面两个值就可以解决：
```
word-break:normal;
word-wrap:break-word;
```
