### ISSUE TITLE
时间线是如何绘制的？

### ISSUE THREAD

**Issue by ChenZhongPu** [tufu9441/maupassant-hexo#43]
请问，你博客里面的“历史”中的时间线是如何绘制的？谢谢。

**Comment by tufu9441** [comment]
https://gist.github.com/tufu9441/b066b4359fc2bff6fca8

**Comment by pangsir8983** [comment]
这代码不能自动生成吗?

**Comment by gzpgzpgzp** [comment]
请问这个时间线的css在哪里 能参考一下你的吗
