### ISSUE TITLE
mathjax src

### ISSUE THREAD

**Issue by swang251** [tufu9441/maupassant-hexo#431]
有人遇到同样的情况么？在mathjax.pug里面的地址
`src='//lib.baomitu.com/mathjax/2.7.5/config/TeX-MML-AM_CHTML.js'`
无法工作，

更改成
`src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML'`
解析成功。

**Comment by tufu9441** [comment]
那可能确实是引用的CDN有问题了
