### ISSUE TITLE
codeblock滚动条覆盖代码

### ISSUE THREAD

**Issue by shengdie** [tufu9441/maupassant-hexo#436]
您好，我发现codeblock的滚动条正好覆盖最后一行代码，对于多行代码没有太大问题，但对于单行长代码影响很大，如下图
<img width="728" alt="screen shot 2019-01-29 at 2 40 59 pm" src="https://user-images.githubusercontent.com/7031829/51935461-f3640200-23d3-11e9-8b08-6aa625c66ee6.png">
~~重要的是鼠标移开，滚动条不自动消失~~，好像是个bug，有时候是自动消失的，但很多时候不自动消失（鼠标移上去再移下来就不自动消失了），没法复制，codeblock下面的padding很宽，建议移到那。感谢。

**Comment by tufu9441** [comment]
![Xnip2019-04-20_20-26-06](https://user-images.githubusercontent.com/6790361/56457261-8b0d3700-63aa-11e9-95ba-d1d13cd2b575.jpg)
我这里并没有遇到过你所说的问题啊？能发一下你的markdown文件里代码部分是怎么写的么？
