### ISSUE TITLE
如何自定义分享功能？

### ISSUE THREAD

**Issue by ChenZhongPu** [tufu9441/maupassant-hexo#44]
不是采用`多说`那样的，而是类似默认主题landscape那样的分享。

**Comment by v123582** [comment]
@ChenZhongPu @tufu9441 https://github.com/tufu9441/maupassant-hexo/pull/56
我參考 landscape 移植了分享的功能？還需要加上什麼功能嗎？

**Comment by tufu9441** [comment]
已经移植了landscape的分享按钮。
