### ISSUE TITLE
gitment登录时候object ProgressEvent

### ISSUE THREAD

**Issue by itgoyo** [tufu9441/maupassant-hexo#441]
这个本该是gitment那边的问题，但是网上搜索的说是作者原域名到期了，倒是.js  .css 文件使用不了，但是我全局查找了发现.js .css都是我本地的，所以在此发一个求助帖，如果有朋友也遇到了这个问题，希望可以帮我解答一下，谢谢了。

**Comment by tufu9441** [comment]
这个我还真不清楚，我自己也没用过gitment。
