### ISSUE TITLE
链接过长不换行

### ISSUE THREAD

**Issue by ttttmr** [tufu9441/maupassant-hexo#444]
PC显示长链接是超出屏幕，如图

![image](https://user-images.githubusercontent.com/32825326/53956008-73893000-4115-11e9-83ef-3b3d39533475.png)

和这个issue类似 #438

**Comment by hushhw** [comment]
在 `style.scss` 中的 `.post .post-content` 中的 `p标签` 下添加 `word-break: break-word;` 和 `overflow-wrap: break-word;` 。
![image](https://user-images.githubusercontent.com/27054716/54008243-d70c6f80-41a0-11e9-9d19-faaca11d19af.png)

**Comment by ttttmr** [comment]
> 在 `style.scss` 中的 `.post .post-content` 中的 `p标签` 下添加 `word-break: break-word;` 和 `overflow-wrap: break-word;` 。
> ![image](https://user-images.githubusercontent.com/27054716/54008243-d70c6f80-41a0-11e9-9d19-faaca11d19af.png)

感谢，可以了

**Comment by tufu9441** [comment]
好的，我会修复。

**Comment by tufu9441** [comment]
已修复。
