### ISSUE TITLE
移动端代码块适配问题

### ISSUE THREAD

**Issue by mekhi** [tufu9441/maupassant-hexo#45]
在移动端,代码块超出屏幕宽度后,右边的代码看不见了.不能正常显示,建议增加滚动条,实现代码块的屏幕适配.

**Comment by tufu9441** [comment]
Fixed. [#2c4a3b1](https://github.com/tufu9441/maupassant-hexo/commit/2c4a3b13943e6873dcd72c8fffd7d2ee9b6cfa1c)

**Comment by mekhi** [comment]
您好,我刚才试了一下手机上还是没适应,我修改了一下style.scss代码块区域的样式试着提交,可以有滚动条了.您看一下.
