### ISSUE TITLE
要怎么使用gitalk哇

### ISSUE THREAD

**Issue by Lidongde** [tufu9441/maupassant-hexo#452]
有没有伙计知道怎么使用gitalk的评论系统吗？作者的说明不是很具体，网上百度找不到使用这个主题的配套方法！求助

**Comment by Lidongde** [comment]
完整的流程谁知道吗

**Comment by Lidongde** [comment]
我把_config.yml和gitalk设置好之后，在博客页面不会生成评论的issue，gitalk那个安装在windows环境下如何操作？

**Comment by tufu9441** [comment]
建议去https://github.com/gitalk/gitalk 提问。

**Comment by tufu9441** [comment]
#389

**Comment by weearc** [comment]
主题里已经包含了gittalk的使用方法，具体可以参考gittalk的说明，没法生成issue有两种可能：1你的gittalk没配置正确 2你标题超出了字符限制 另：提问前请先百度一下，你的这个问题很多博文都有讲解的。


 
---原始邮件---
发件人: "Lidongde"<notifications@github.com>
发送时间: 2019年4月22日 01:31:41
收件人: "tufu9441/maupassant-hexo"<maupassant-hexo@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tufu9441/maupassant-hexo] 要怎么使用gitalk哇 (#452)



有没有伙计知道怎么使用gitalk的评论系统吗？作者的说明不是很具体，网上百度找不到使用这个主题的配套方法！求助
