### ISSUE TITLE
关于摘要的问题

### ISSUE THREAD

**Issue by eassy** [tufu9441/maupassant-hexo#455]
关于大家都在问的摘要问题，我觉得有一个不算多好的解决办法，就是修改模板文件，添加 description: {{ title }} ，这行至少可以让每篇摘要和 title 相同，效果也可以接受

**Comment by tufu9441** [comment]
具体该如何实现？

**Comment by eassy** [comment]
特别简单。。。修改 scaffolds/post.md 文件  
```
---
title: {{ title }}
date: {{ date }}
tags:
description: {{ title }}
---
```
不知道能不能满足其他人需求
