### ISSUE TITLE
如何修改顶部导航栏的中文字体？

### ISSUE THREAD

**Issue by NonEvent** [tufu9441/maupassant-hexo#459]
其余地方的字体都修改了，唯独顶部导航栏的字体不知怎样修改。
<img width="545" alt="Screen Shot 2019-09-18 at 11 37 34 PM" src="https://user-images.githubusercontent.com/25746215/65163632-d74dc780-da6d-11e9-826c-7211c661e528.png">

**Comment by NonEvent** [comment]
研究了一天，通过修改head.pug和下载FontAwesome字体放到source文件夹里，终于更换了顶部导航栏的字体！

**Comment by wangwanchao** [comment]
虽然关闭了，但我还是想评论一下，我遇到的汉化问题，只需要修改根目录下`_config.yml`
```
minivaline: ## See: https://github.com/MiniValine/MiniValine
  lang: zh-CN
```
