### ISSUE TITLE
关于“从代码块中跨行选择代码会将行号一并选中”的问题

### ISSUE THREAD

**Issue by Creling** [tufu9441/maupassant-hexo#462]
如题，当跨行选择代码时会将行号一并选中，给复制粘贴带来麻烦，这不太符合一般预期：

![图片](https://user-images.githubusercontent.com/43109504/70236794-9d54ad80-17a0-11ea-8d3e-892ccf11a794.png)
---
非常奇怪的是，在作者博客中并不存在这个问题，是因为Maupassant-hexo的版本问题吗？请问作者博客使用的哪个版本呢？

![图片](https://user-images.githubusercontent.com/43109504/70236870-cd9c4c00-17a0-11ea-8888-efcc9db8cab9.png)

**Comment by Creling** [comment]
经过测试，感觉是hexo的问题，已在hexo提交issue如下：
https://github.com/hexojs/hexo/issues/3913

**Comment by weearc** [comment]
这个是我在自己博客尝试的，没有出现上述情况。可能是版本旧的缘故。
![hexo2](https://user-images.githubusercontent.com/19357165/70374660-dff8c000-192f-11ea-8863-d03d0c98ecea.png)
另外根据分析，右侧代码框为整体的一个子元素，按理说是不会复制到行号的。可能是主题相关位置代码变动导致的。
![hexo](https://user-images.githubusercontent.com/19357165/70374652-bb9ce380-192f-11ea-8095-8a3364c19d22.png)

**Comment by Creling** [comment]
这个可能和hexo的版本有关。
我目前在用hexo@4.0，不仅仅是maupassant，哪怕是默认的主题landscope也存在这样的问题。

> 另外根据分析，右侧代码框为整体的一个子元素，按理说是不会复制到行号的。可能是主题相关位置代码

这个可以参照https://github.com/hexojs/hexo/issues/3913的分析，Hexo@4.0中的代码框不是左边一大块右边一大块了，变成一行一行的小块了，所以说没办法避开左边的行号。

**Comment by weearc** [comment]
> 这个可能和hexo的版本有关。
> 我目前在用hexo@4.0，不仅仅是maupassant，哪怕是默认的主题landscope也存在这样的问题。
> 
> > 另外根据分析，右侧代码框为整体的一个子元素，按理说是不会复制到行号的。可能是主题相关位置代码
> 
> 这个可以参照 [hexojs/hexo#3913 (comment)](https://github.com/hexojs/hexo/issues/3913#issuecomment-562834033) 的分析，Hexo@4.0中的代码框不是左边一大块右边一大块了，变成一行一行的小块了，所以说没办法避开左边的行号。

所以可以换回2.0 3.0版本，也是一个解决办法23333

**Comment by Creling** [comment]
我太难了2333

**Comment by tufu9441** [comment]
之前没发现过，最近更新到4.1.1之后确实存在这个问题了，并且代码框每个距离超长的行下面都会多出一个滚动条，十分蛋疼。

**Comment by tufu9441** [comment]
@Creling 我看了你提的Issue https://github.com/hexojs/hexo/issues/3913 ，你在自己修改代码后恢复正常了吗？改的是哪里

**Comment by Creling** [comment]
[gutter ](https://github.com/tufu9441/maupassant-hexo/blob/master/source/css/style.scss#L904)
```
    .gutter {
        background-color: inherit;
        font-family: Menlo, Consolas, monospace;
        border:      none;
        padding:     0;
        margin:      0;
        cursor:      text;
        user-select: none
    }
```
给gutter单独设立样式块，最后加一个` user-select: none`即可

**Comment by tufu9441** [comment]
Fixed.
