### ISSUE TITLE
Valine 无法设置不发送提醒邮件

### ISSUE THREAD

**Issue by zealseeker** [tufu9441/maupassant-hexo#463]
虽然该PR尝试修复这个bug，但恐怕并没有效果 #454 
根据 Valine 的[介绍](https://valine.js.org/quickstart.html#%E9%85%8D%E7%BD%AE) ，verify和 notify都应该填 true 或者 false，即布尔值
```
new Valine({
    el: '#vcomments' ,
    appId: '<APP_ID>',
    appKey: '<APP_KEY>',
    notify:false, 
    verify:false, 
    avatar:'mp', 
    placeholder: 'just go go' 
});
```
但目前代码得到的是`'true'`或者`'false'`
https://github.com/tufu9441/maupassant-hexo/commit/f144ee850628b9c85e9b0fbb9cc912be9ce8a79f#comments
```
var notify = '#{ theme.valine.notify }' ? true : false;
var verify = '#{ theme.valine.verify }' ? true : false;
```
这会导致无论`#{theme.valine.notify}`得到什么，最终都是true

**Comment by tufu9441** [comment]
这方面我不懂，请@xuxiaoyuspallow 来看看吧

**Comment by time-todie** [comment]
问题似乎出在Valine自己身上。Valine已经在新版砍掉了提醒邮件和验证码相关代码。

**Comment by zealseeker** [comment]
已经在这里解决了。
https://github.com/tufu9441/maupassant-hexo/commit/4bbae40a0508b697e6e3d25ee87773fa3559b351
