### ISSUE TITLE
添加新页面后只剩md页面

### ISSUE THREAD

**Issue by jiang-ch** [tufu9441/maupassant-hexo#464]
我看了文档，但是我加了index.md，跳转以后整个页面只有md的内容，没有主题原来的顶栏和侧边栏，想问一下这是为什么

**Comment by jiang-ch** [comment]
如果需要保留侧边栏，是不是需要写一个pug

**Comment by tufu9441** [comment]
不需要写pug，添加页面需要填写好`front-matter`

**Comment by jiang-ch** [comment]
加source加到theme下的source了
