### ISSUE TITLE
引用图片外链时灯箱失效问题

### ISSUE THREAD

**Issue by foreverSFJ** [tufu9441/maupassant-hexo#466]
在图片是引用外链的情况下，点击图片不会是灯箱效果，而是直接跳转到一个新的标签页
例如使用七牛云图片外链时，点击博客中的图片会直接跳转到七牛的图片，而不是灯箱效果。

期待作者大大能帮个忙，优化一下或者指导怎么修改~~~

**Comment by Waynehfut** [comment]
我也有一样的问题

**Comment by YxuanAr** [comment]
一样的问题，不知道怎么解决

**Comment by tufu9441** [comment]
我经过试验没有重现这个现象，应该不是主题的问题，用浏览器检查一下错误信息，有可能是服务器端的安全设置问题。
