### ISSUE TITLE
markdown中>引用样式显示为大号“，怎么改成原来的样式？

### ISSUE THREAD

**Issue by qiyueliuhuo** [tufu9441/maupassant-hexo#481]
原来的样式前面有一个竖框

**Comment by 2inf** [comment]
修改maupassant/source/css/style.scss，用//注释掉blockquote,
.stressed中的`border-left: none;`和blockquote::before,
.stressed-quote::before中的`content: "\201C";`

**Comment by qiyueliuhuo** [comment]
![image](https://user-images.githubusercontent.com/15904121/81251362-ae5a6100-9055-11ea-857e-ed8cd4f201f3.png)
怎么改成github的引用样式，谢谢~
