### ISSUE TITLE
Feature request:统一管理静态文件的路径，方便使用CDN

### ISSUE THREAD

**Issue by cielpy** [tufu9441/maupassant-hexo#49]
现在模版中这样写法的话，使用 CDN 不是太方便，如果托管在 github 把静态文件用上国内的CDN对网页加载速度提升还是很明显的，之前用过 Next 主题，他把静态文件的路径设置放到了_config.yml 中设置，这样如果这个配置参数设置为 CDN 的URL时，可以直接读取 CDN 的静态文件内容

参考 PR https://github.com/iissnan/hexo-theme-next/pull/4

**Comment by tufu9441** [comment]
Nice advice. Maybe you can create a pull request. :)

**Comment by cielpy** [comment]
OK,if this idea is correct,I will try to work on this feature,and will pull request when I completed it.

**Comment by tufu9441** [comment]
Thanks. Looking forward to your good news.

**Comment by cielpy** [comment]
Does this theme has a version number? if enabled CDN,it's better to have a version number,for flush the cache when the static files changed.

**Comment by tufu9441** [comment]
It has no version number currently.

**Comment by cielpy** [comment]
- - I use version number 0.0.0
There is a problem, use syntax js or css like this
`  != css(url_for(theme.css) + '/jquery.fancybox.css'  + '?v=' + theme.version)`

if this url dose not end with extension name "css", at the end, the url will be like this
`http://aa.com/css/jquery.fancybox.css?v=0.2.0.css`

forced end with "css"

**Comment by cielpy** [comment]
Any idea about this weird issue?I'm not very familiar with Jade engine...

**Comment by tufu9441** [comment]
Sorry I have no idea about this too. What about the case without the theme version, is it that necessary?

**Comment by cielpy** [comment]
CDN has cache of these static files,If any file of  these static files changed, and then if you get the version with the old URL, the CDN with give you a cached file,not the newer one, and if you add a parameter `v`, when files changed change the you will try  to get the static files with different URL, because the version has changed, the CDN will pull the file from the origin, and CDN will be flush atomatic.

**Comment by tufu9441** [comment]
I understand your meaning. I tried just now, if I use the following format:
```
link(rel='stylesheet', type='text/css', href=url_for(theme.css) + '/pure-min.css' + '?v=' + theme.version)
```
the html code will be like this:
```
<link rel="stylesheet" type="text/css" href="/css/normalize.css?v=0.2.0">
```
Let me test other static files.

**Comment by tufu9441** [comment]
For js files, you can use this format:
```
script(type='text/javascript', src=url_for(theme.js) + '/codeblock-resizer.js' + '?v=' + theme.version)
```
For CSS files, just use the format in the last comment.

**Comment by cielpy** [comment]
OK, I have finish the code work, it's time you review the code.

**Comment by tufu9441** [comment]
I see, I will review and merge the pull request. Thanks very much for your contribution.

**Comment by cielpy** [comment]
Thanks for your  beautiful theme :)
