### ISSUE TITLE
是否可以在侧栏增加日历云呢？

### ISSUE THREAD

**Issue by Josep-h** [tufu9441/maupassant-hexo#495]
作者您好，您这个移植主题非常地好用，也是我现在的主力主题。但是唯一有一点，想请教一下作者，即如果希望在Sidebar中增加日历应该如何操作？

我找到了使用ejs语言的版本：[链接](http://howiefh.github.io/2016/04/29/hexo-s-calendar-plugin/)。我尝试了好几次将这个版本移植到maupassant上，但是总是没有成功。主要是个人对`.pug`这种语言的写法完全不清楚。并且maupassant的结构和大多数流行的主题，类似Next也有诸多不同。

如果方便的话，可以麻烦作者简单看看这个应该如何处理比较好呢？再次对贡献该主题的原作者和迁移该主题的各位作者表示感激！

**Comment by tufu9441** [comment]
我看了一下，确实挺好看，但个人觉得实用性不强，没有必要整合。

**Comment by Josep-h** [comment]
感谢作者。我后来自己又尝试了一番移植，还是没有成功。但功能交给 Archive 来完成也基本够了。
