### ISSUE TITLE
点击生成的目录，不会跳转？

### ISSUE THREAD

**Issue by younglifestyle** [tufu9441/maupassant-hexo#496]
https://chunlife.top/2020/10/20/Go-Micro%E6%A1%86%E6%9E%B6%E7%9A%84%E4%BD%BF%E7%94%A8

点击后，链接只是加了个#null，并没有识别跳转啥的，这是还需要加入什么其他配置吗

**Comment by tufu9441** [comment]
使用过程中没有遇到过这个问题，标题都是按markdown语法写的，前面加若干个#。

**Comment by younglifestyle** [comment]
问题是出在hexo-toc上，修改node_modules\hexo-toc\lib\filter.js
```js
$title.attr('id', id);
// $title.children('a').remove();
// $title.html( '<span id="' + id + '">' + $title.html() + '</span>' );
// $title.removeAttr('id');
```
