### ISSUE TITLE
求集成utteranc评论

### ISSUE THREAD

**Issue by 828767** [tufu9441/maupassant-hexo#497]
自己搞了个，用 `'#{theme.utteranc.repo}'` 写法居然不能识别，只能硬编码自己用，求集成  [utteranc.es](https://utteranc.es) 到主题。

**Comment by tufu9441** [comment]
可以看一下pug语法，写法没有那么复杂。欢迎提交PR。

**Comment by tufu9441** [comment]
我看了一下，在单行script中`'#{theme.utteranc.repo}'`的写法的确没有识别，还没找到解决方法。所以暂时只能先硬编码自己用了。

**Comment by tufu9441** [comment]
已添加。
