### ISSUE TITLE
你好，我使用你的主题，在本地服务器有问题

### ISSUE THREAD

**Issue by otherid** [tufu9441/maupassant-hexo#5]
页面显示以下代码
extends base - var current_title = page.title || tag.name || category.name || site.title block title title= config.title + " | " + config.subtitle block content for post in page.posts.toArray() .post h2.post-title include _partial/helpers a(href=url_for(post.path)) +title(post) .post-meta= post.date.format(config.date_format) span.ds-thread-count(data-thread-key=post.path) if post.description .post-content= post.description else if page.excerpt .post-content= page.excerpt else if post.content .post-content= strip_html(post.content).replace(/^\s*/, '').replace(/\s*$/, '').substring(0, 300) p(class="readmore") a(href=url_for(post.path))= __('Readmore') include _partial/paginator

**Comment by tufu9441** [comment]
页面的index.md中是否设置了layout:page ？

**Comment by otherid** [comment]
我是用Hexo搭建的，没有index.md这个文件

**Comment by otherid** [comment]
我使用其他主题，没有问题。但是很喜欢这个，除了设置_config.yml文件还需要改动其他地方吗

**Comment by tufu9441** [comment]
我知道是Hexo，你所谓的页面不是page吗？你安两个renderer了没有

On 周四, 10月 29, 2015 at 13:54, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
我是用Hexo搭建的，没有index.md这个文件

—
Reply to this email directly or view it on GitHub
[https://github.com/tufu9441/maupassant-hexo/issues/5#issuecomment-152084408] .[https://github.com/notifications/beacon/AGec2XXXuCOVGPhQYgIT2JO1jjyhnNZyks5pAawogaJpZM4GX52Y.gif]

**Comment by tufu9441** [comment]
仔细看一下README设置，把依赖的插件安好就不会出问题。再有问题就不是主题的问题了，因为不少人都成功安装过，可能是你HEXO环境的原因。

On 周四, 10月 29, 2015 at 13:58, tufu9441/maupassant-hexo
<reply@reply.github.com>
wrote:
我使用其他主题，没有问题。但是很喜欢这个，除了设置_config.yml文件还需要改动其他地方吗

—
Reply to this email directly or view it on GitHub
[https://github.com/tufu9441/maupassant-hexo/issues/5#issuecomment-152085314] .[https://github.com/notifications/beacon/AGec2b0JEiynW7iuMAY0h1XqZVFm9X5Uks5pAazvgaJpZM4GX52Y.gif]

**Comment by webfrontzhifei** [comment]
theme名称改为maupassant-hexo就可以了
