### ISSUE TITLE
上传博文首页显示no-title 

### ISSUE THREAD

**Issue by PAUSEMAD** [tufu9441/maupassant-hexo#507]
位于source/_posts里的markdown 文件名为中文，用hexo d上传后博文首页显示no-title 博文标题在正文显示，自己试了各种方法，实在是找不到解决办法，望解答，感谢。
博文地址：http://pausemad.github.io/

**Comment by tufu9441** [comment]
把md文件完整的内容贴一下看看。

**Comment by PAUSEMAD** [comment]
是把markdown文件里的内容复制到这上来吗
文件名是 表面的抗体(一).md
正文内容如下：
# 表面的抗体(一)

她发给我三张图片，我收到的时候图片还在不停地转着圈圈，就像水池放水时转个不停的右螺旋。图片的性质心里已猜个七七八八，何种方式呈现，才是我好奇的东西。最近手机加载豆瓣的速度变慢了，他伴着我见过了形形色色的人和言语，神经已是无痛无感，迟缓衰老。我给不了他打下如此几个文字的时间，不停的上滑强制退出，点击重启，如此暴力的推扯两三次，终得看见。井里的水已经落了个干净，尺度并不大，为了逃过审查而故意显得遮遮掩掩，身材很像p站里的mini diva，偶然瞥见鼓鼓的衣服上那条英文，我会心一笑。我回了句类似“谢谢”的客气话，然后陷入沉默。对于这样一个尤物，没有更多的想法是自欺欺人的，但往上的回索符合当前略微失落，朦胧的情境。我不是没有任何粗俗化的欲望，只是这种东西于这里不太兼容，身为一个作家或诗人，他应该把这些不兼容的情感去掉，哪怕它真实的存在过几秒，我就暂且在这里当回作家和诗人好了。
我和她的聊天一直维持在一个水平面上，被冷风吹拂的那种，偶然的深浅不一不影响整个谈话。我在试探沙堆底下的岩石层，动作很僵硬，更多时候是她来抛出新的话题，把我正在挖掘的动作打断。我也没什么懊恼，这个岩石层本来就是由她界定，收手作罢。“网络和现实是两个世界“，这句话让我重新意识到我们两个谈话分担的角色，但她并没有按照剧本来走，越过了她那个角色该有的范围。她发给我照片的那一刻，我们两的角色被戏剧般地置换，她成了上位者，三张照片构筑了三点，骑在我身上摇晃起落。我情难自禁的想到将她压在身下的欢愉，将“反差感羞耻感背德感”挺入她的胴体，但我更多时候想象的是她和男友上床时候的Dirty Talk，她的呻吟，她男友的角度，和他们身上的汗液，和《后窗》里加里格兰特一样，拿个“望远镜”，勾勒他人生活的一景。帘子后的色欲，我的嫉妒，已经分不太清了，反正已经有了七宗罪，将混合的情感分的太清楚也就显得没大必要，只需知道勾勒的场景充斥着荷尔蒙，荷尔蒙即欲望。用欲望作画，只需一角，成本相当低廉，成年青年都可，超越了审查这张狭小的桌板，最后溅满一身情欲色彩。
高中地理书第一课就说，沙堆下的岩石层下面还有岩浆，我在岩浆托起的板块上平移，寻找板块交界的缺口，看着火山喷发的乌云，看着他们的挤压和碰撞，想起霓虹国那部《火口的两人》。

**Comment by tufu9441** [comment]
你没有设置front-matter?去看看Hexo文档最开头应该怎么写。

获取 Outlook<https://aka.ms/qtex0l> for iOS
________________________________
发件人: PAUSEMAD <notifications@github.com>
发送时间: Wednesday, March 3, 2021 1:10:25 PM
收件人: tufu9441/maupassant-hexo <maupassant-hexo@noreply.github.com>
抄送: tufu9441 <tufu9441@gmail.com>; Comment <comment@noreply.github.com>
主题: Re: [tufu9441/maupassant-hexo] 上传博文首页显示no-title (#507)


是把markdown文件里的内容复制到这上来吗
文件名是 表面的抗体(一).md
正文内容如下：

表面的抗体(一)

她发给我三张图片，我收到的时候图片还在不停地转着圈圈，就像水池放水时转个不停的右螺旋。图片的性质心里已猜个七七八八，何种方式呈现，才是我好奇的东西。最近手机加载豆瓣的速度变慢了，他伴着我见过了形形色色的人和言语，神经已是无痛无感，迟缓衰老。我给不了他打下如此几个文字的时间，不停的上滑强制退出，点击重启，如此暴力的推扯两三次，终得看见。井里的水已经落了个干净，尺度并不大，为了逃过审查而故意显得遮遮掩掩，身材很像p站里的mini diva，偶然瞥见鼓鼓的衣服上那条英文，我会心一笑。我回了句类似“谢谢”的客气话，然后陷入沉默。对于这样一个尤物，没有更多的想法是自欺欺人的，但往上的回索符合当前略微失落，朦胧的情境。我不是没有任何粗俗化的欲望，只是这种东西于这里不太兼容，身为一个作家或诗人，他应该把这些不兼容的情感去掉，哪怕它真实的存在过几秒，我就暂且在这里当回作家和诗人好了。
我和她的聊天一直维持在一个水平面上，被冷风吹拂的那种，偶然的深浅不一不影响整个谈话。我在试探沙堆底下的岩石层，动作很僵硬，更多时候是她来抛出新的话题，把我正在挖掘的动作打断。我也没什么懊恼，这个岩石层本来就是由她界定，收手作罢。“网络和现实是两个世界“，这句话让我重新意识到我们两个谈话分担的角色，但她并没有按照剧本来走，越过了她那个角色该有的范围。她发给我照片的那一刻，我们两的角色被戏剧般地置换，她成了上位者，三张照片构筑了三点，骑在我身上摇晃起落。我情难自禁的想到将她压在身下的欢愉，将“反差感羞耻感背德感”挺入她的胴体，但我更多时候想象的是她和男友上床时候的Dirty Talk，她的呻吟，她男友的角度，和他们身上的汗液，和《后窗》里加里格兰特一样，拿个“望远镜”，勾勒他人生活的一景。帘子后的色欲，我的嫉妒，已经分不太清了，反正已经有了七宗罪，将混合的情感分的太清楚也就显得没大必要，只需知道勾勒的场景充斥着荷尔蒙，荷尔蒙即欲望。用欲望作画，只需一角，成本相当低廉，成年青年都可，超越了审查这张狭小的桌板，最后溅满一身情欲色彩。
高中地理书第一课就说，沙堆下的岩石层下面还有岩浆，我在岩浆托起的板块上平移，寻找板块交界的缺口，看着火山喷发的乌云，看着他们的挤压和碰撞，想起霓虹国那部《火口的两人》。

―

**Comment by PAUSEMAD** [comment]
问题解决了 感谢
