### ISSUE TITLE
npm install hexo-renderer-sass 失败

### ISSUE THREAD

**Issue by cmal** [tufu9441/maupassant-hexo#51]
npm install hexo-renderer-sass build的时候失败。报的错误都是源代码build的错误，是否node.js版本或者其他什么东西的版本对不上号？我对node.js不熟。望赐教。十分感谢！

**Comment by cmal** [comment]
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/cmal/gits/hexo/themes/maupassant/node_modules/hexo-renderer-sass/node_modules/node-sass/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/cmal/gits/hexo/themes/maupassant/node_modules/hexo-renderer-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/cmal/gits/hexo/themes/maupassant/node_modules/hexo-renderer-sass/node_modules/node-sass
gyp ERR! node -v v4.2.2
gyp ERR! pangyp -v v2.3.3
gyp ERR! not ok

**Comment by tufu9441** [comment]
抱歉我也没遇到过这个问题，貌似这个issue应该提给[hexo-renderer-sass](https://github.com/knksmith57/hexo-renderer-sass)？我的博文评论中也有人遇到过类似的问题：
https://www.haomwei.com/technology/maupassant-hexo.html#comment-2394843344
https://www.haomwei.com/technology/maupassant-hexo.html#comment-2473544472
不知道对你有没有帮助。
