### ISSUE TITLE
启用分享按钮后 Valine 文本编辑区宽度减少

### ISSUE THREAD

**Issue by UM-Li** [tufu9441/maupassant-hexo#511]
文本框的右边界被限制在分享按钮左侧。

`shareto: false`

![Screenshot_20210720_123717](https://user-images.githubusercontent.com/6215580/126370250-969d9917-05d8-457f-8286-f3e36ab0674f.png)

`shareto: true`

![Screenshot_20210720_123637](https://user-images.githubusercontent.com/6215580/126370274-86122507-f2bc-4a3c-bcd7-bf94fc0a953b.png)

**Comment by tufu9441** [comment]
我刚访问了你的网站，发现评论框宽度是正常的呀，请问一下是你自己修改了代码吗？

**Comment by UM-Li** [comment]
你好，我在 `post.pug` 末尾加了一行
```html
if page.comments
      <div style="height: 25px;"></div>
      include _partial/comments.pug
```

**Comment by tufu9441** [comment]
> 你好，我在 `post.pug` 末尾加了一行
> 
> ```
> if page.comments
>       <div style="height: 25px;"></div>
>       include _partial/comments.pug
> ```

 好的，明白了，多谢！不过现在Valine似乎不怎么更新了，所以我选用了Waline。
