### ISSUE TITLE
source/css/style.scss 文件后缀错误

### ISSUE THREAD

**Issue by gotohx** [tufu9441/maupassant-hexo#513]
style.scss  文件后缀错误导致布局失效，改成 style.css 后恢复正常 。

**Comment by tufu9441** [comment]
应该是hexo-renderer-sass插件没有正确安装的原因。

**Comment by gotohx** [comment]
不太理解，这个文件 [https://github.com/tufu9441/maupassant-hexo/blob/master/source/css/style.scss](url) 是需要用插件再生成一次吗？

**Comment by tufu9441** [comment]
应该是说当后缀名是scss的时候，必须安装有hexo-renderer-sass插件，才能够正常渲染。其实两种格式和语法基本是一样的，既然你能通过改后缀名来正常使用的话，也不用管那么多了。

**Comment by gotohx** [comment]
了解了，多谢解惑
