### ISSUE TITLE
Dark模式按钮问题

### ISSUE THREAD

**Issue by Farmer-chong** [tufu9441/maupassant-hexo#516]
开启dark模式后，按钮会被代码块遮挡，如下图:

![image](https://user-images.githubusercontent.com/48387781/158308957-44f19c5c-c4ab-4892-96d3-7095e907b0a8.png)

**Comment by tufu9441** [comment]
Fixed by https://github.com/tufu9441/maupassant-hexo/commit/85997d43cbf23cf032d0e95e40c974acf78299fa
