### ISSUE TITLE
对Markdown的支持不够友好

### ISSUE THREAD

**Issue by thisisx7** [tufu9441/maupassant-hexo#52]
当有序列表和无序列表嵌套使用的时候 存在bug
![image](https://cloud.githubusercontent.com/assets/5620450/12666771/9b98f72a-c67e-11e5-9e4b-6e7ab5ad0275.png)
会出现 这样的布局 

还有建议修改 引用标记的样式……
![image](https://cloud.githubusercontent.com/assets/5620450/12666801/e2a0bc52-c67e-11e5-82de-e3c88b88285b.png)

**Comment by tufu9441** [comment]
你指的bug是什么意思，是行距还是什么？我这里看一切正常：

![screencapture at fri jan 29 13 17 13 cst 2016](https://cloud.githubusercontent.com/assets/6790361/12667840/79d5febe-c68b-11e5-98d9-e46abbab2f94.png)

引用样式是[Cho](https://github.com/pagecho)原版maupassant主题里原创的风格，个人也比较喜欢，暂不考虑修改。

**Comment by thisisx7** [comment]
对，是行距

**Comment by tufu9441** [comment]
你markdown里怎么写的，我是这么写的，显示没问题：
```
1. 测试
 - 测试
 - 测试
 - 测试
2. 测试
3. 测试
```

**Comment by thisisx7** [comment]
![image](https://cloud.githubusercontent.com/assets/5620450/12668051/c9a0759e-c68d-11e5-931a-f3e9fb7998b3.png)
我的是这么写的 在4. 测试 后面并没有空格
显示效果是这样
![image](https://cloud.githubusercontent.com/assets/5620450/12668059/f0a59cbe-c68d-11e5-8ac4-81b21116be9a.png)

**Comment by tufu9441** [comment]
我又试了一下，依然没有重现：
![screencapture at fri jan 29 13 49 35 cst 2016](https://cloud.githubusercontent.com/assets/6790361/12668243/76121340-c68f-11e5-8022-8ccb380036be.png)
能否提供一个在线的demo让我看看。

**Comment by thisisx7** [comment]
http://thisisx7.github.io/2016/01/28/wargame-natas%E7%B3%BB%E5%88%97%E6%80%BB%E7%BB%93/

**Comment by thisisx7** [comment]
问题已经解决，中间更换过 hexo默认的render engine  。
出现问题的时候用的是hexo-renderer-markdown-it
更换回hexo-renderer-marked 得到解决

**Comment by tufu9441** [comment]
看了一下网页源代码，发现你的有序列表的内容被套上了一个`<p>`的标签：
![screencapture at fri jan 29 14 00 32 cst 2016](https://cloud.githubusercontent.com/assets/6790361/12668374/e259e87e-c690-11e5-8454-a53f2ae87828.png)

而我测试的时候则没有这种情况：
![screencapture at fri jan 29 14 01 00 cst 2016](https://cloud.githubusercontent.com/assets/6790361/12668381/eec0de10-c690-11e5-9a88-24b9d2af5b25.png)

由于这个主题的CSS里设定了`<p>`（文章内容）后会有1.234em的距离，也就是自然段之间的间隔，因此你的有序列表后会有额外的空行。所以应该并不是主题的原因，可能是你使用的markdown引擎的原因。

**Comment by thisisx7** [comment]
嗯 确实是这样！ 问题已经解决，十分感谢！
