### ISSUE TITLE
主页自动生成文章摘要时，有可能会导致侧边栏无法加载

### ISSUE THREAD

**Issue by counter2015** [tufu9441/maupassant-hexo#520]
我有一个这样的 markdown 文件
```
# Manjaro 安装配置

title: Manjaro 安装配置
date: 2020-01-21 19:32:30
tags: [Linux, Manjaro] 
categories: [技术]

------




非常感谢这篇[博客](https://printempw.github.io/setting-up-manjaro-linux/)提供的思路，让我在后面的安装过程中少走了不少弯路。

目标安装机器配置：

| -    | -                    |
| ---- | -------------------- |
| 型号 | Lenovo Erazer Y40-70 |
| CPU  | Intel i7-4510U 2G    |
| HDD  | 1T                   |
| 内存 | 4GB                  |
| LAN  | 100M/1000M           |
| OS   | Windows 8.1 PRC      |
```

当它渲染的时候会错误地插入`table`标签，却没有插入对应的闭合标签，导致之后的Html都无法正常渲染.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/13608862/161429080-2c1ac224-e284-43e8-840a-fa7f3134d54c.png">

虽然说可以通过其他方式绕开它，但是这个问题还是挺别扭的

相关代码

https://github.com/tufu9441/maupassant-hexo/blob/0ae2d832741b1c65a42854cd87111819e3606ace/layout/index.pug#L29-L43

**Comment by tufu9441** [comment]
这个确实是个问题，但由于个人能力所限，目前我也不知道能怎么修改一下😂
