### ISSUE TITLE
能否提供自定义CDN选项

### ISSUE THREAD

**Issue by FarmerChillax** [tufu9441/maupassant-hexo#524]
能否让用户自行选择使用的CDN服务，或者提供一个使用本地资源的选项？

**Comment by tufu9441** [comment]
本地资源路径的选项配置文件最后就有，你可以都下载到本地然后手动替换。我觉得目前没有什么好办法可以方便用户一键选择使用的外部CDN服务，主要是太麻烦了懒得改，欢迎PR。
