### ISSUE TITLE
怎么在widgets里新增一个分类？现在默认6个，我自己加了一个貌似不行。

### ISSUE THREAD

**Issue by loody** [tufu9441/maupassant-hexo#53]

**Comment by loody** [comment]
我想加一个类似links的分类

**Comment by tufu9441** [comment]
没有在_widget文件夹里写好并在_config.yml里调用的widget都是无法使用的，如果要自己添加的话请参考_widget里已存在文件的写法并添加。

**Comment by v123582** [comment]
@loody: 先在 layout/_widget/ 開你想要的檔案(.jade)，再到 _config.yml 新增上去。
