### ISSUE TITLE
英文单词在遇到换行时,会被切成两部分, 分别显示在两行

### ISSUE THREAD

**Issue by brianlan** [tufu9441/maupassant-hexo#54]
例如处于一行末尾的单词collaborate, 有可能会被切成colla和borate. colla显示在该行的末尾, borate显示在下一行的开始.

**Comment by tufu9441** [comment]
是的，这是因为在CSS里面`word-break: break-all`的属性决定的，考虑到有的行内代码太长不及时切断会挤得上下文都无法对齐，排列很难看。你如果不希望这样可以把这个属性改成normal或者keep-all。

**Comment by tufu9441** [comment]
现在默认的已经改成`word-break: normal`了。

**Comment by brianlan** [comment]
谢谢你，之前一直都没来得及回复。
            在2016年02月12日 19:18，tufu9441 写道:现在默认的已经改成word-break: normal了。
