### ISSUE TITLE
关于 Fancybox 的两个问题

### ISSUE THREAD

**Issue by UM-Li** [tufu9441/maupassant-hexo#540]
### 1. 图片标题似乎只在启用 Fancybox 时才会显示?

Markdown: `![KDE 支持多种组合键选择](/images/KDE-Compose-Key/settings.png)`

`fancybox: true`

![Screenshot_20230213_125911](https://user-images.githubusercontent.com/6215580/218452376-3f3ffe2d-e6ac-4a15-864a-6df3111e3c39.png)

`fancybox: false`

![Screenshot_20230213_130004](https://user-images.githubusercontent.com/6215580/218452426-ffd5adf9-5099-4916-9ed6-656b5d9c3097.png)

想确认下这是不是我自己的站点设置导致的；如果是普遍现象则希望能在禁用 Fancybox 时也展示标题。

### 2. Waline 表情选择器异常

Fancybox 会处理表情选择器的选项卡，点击图标会弹出灯箱而非切换选项卡，且有异常文字。

![Screenshot_20230213_124014](https://user-images.githubusercontent.com/6215580/218453047-26f64b2b-daba-4d2c-a594-13dff75128c5.png)

**\*** 以上是 Firefox v109.0.1 的测试结果

**Comment by tufu9441** [comment]
1、的确是这样的。
2、我也发现了，暂时不知道怎么解决，所以就先关闭了fancybox。

**Comment by UM-Li** [comment]
研究了下，目前应该处理了问题 2。https://github.com/tufu9441/maupassant-hexo/pull/544#issue-1598415743
但还是搞不懂问题 1 是什么原因 🫠

**Comment by UM-Li** [comment]
拉取 https://github.com/tufu9441/maupassant-hexo/pull/544 后图片标题和 Waline 正常显示不再只能二选一，我的问题实质已解决。
