### ISSUE TITLE
标签（tag）含空格时生成链接有问题

### ISSUE THREAD

**Issue by y2-Whyto** [tufu9441/maupassant-hexo#543]
如图所示：

文章生成的链接：

<img width="463" alt="图片" src="https://user-images.githubusercontent.com/42339192/219908149-00ffebe3-df78-4c32-8ef6-379489dc1b56.png">

实际的标签链接：

<img width="477" alt="图片" src="https://user-images.githubusercontent.com/42339192/219908162-7935f81c-dfb5-43d4-a48a-b34a7952713f.png">

文章生成的链接包含空格，而实际的标签页链接使用`-`代替了空格。会导致404错误。

**Comment by wdssmq** [comment]
下划线也会变成中划线。。
