### ISSUE TITLE
希望能够把代码块的字体改成等宽的

### ISSUE THREAD

**Issue by unnamed42** [tufu9441/maupassant-hexo#55]
在style.scss的756行，原先是
`font-family: Menlo;`
使用你以前的style.scss改成了
`font-family: "Input Mono", "PT Mono", Consolas, Monaco, Menlo, monospace;`
代码还是要用等宽字体好看一点。

**Comment by tufu9441** [comment]
这个是移植Github所渲染的md文件中代码的样式（[示例](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md)），如果你觉得那样好看的话可以自己修改使用。
