### ISSUE TITLE
更新后首页错乱

### ISSUE THREAD

**Issue by hyxxsfwy** [tufu9441/maupassant-hexo#58]
最近一次更新添加了分享功能，但是开启后没有看到变化，反倒是首页导航图标和边栏位置错乱。

**Comment by zwb-ict** [comment]
@hyxxsfwy 我也出现了这个问题，请问你是怎么解决的？

**Comment by tufu9441** [comment]
应该是你自己修改后出问题了吧

**Comment by zwb-ict** [comment]
感谢你的回复，我这边没能检查出是什么原因。估计是我这边的配置不正确。附件是我修改的两个yml文件，方便的话，能帮我看看哪个地方配置的不正确吗？非常感谢。

**Comment by tufu9441** [comment]
哪里有附件？没看到。

**Comment by zwb-ict** [comment]
@tufu9441 邮件重发了，这次有收到附件吗？

**Comment by tufu9441** [comment]
没有。把代码直接贴到这里，另外传一份你自己修改的主题到github上我看看。

**Comment by zwb-ict** [comment]
我的blog地址是http://zwb-ict.github.io/ <http://zwb-ict.github.io/>

我修改了两个文件，分别是Blog根目录下的_config.yml ，另一个是Blog的_config.yml文件，其他文件没有做修改。

Blog 的 yml文件

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ZWB's Up
subtitle: 坚实的基础设施造就稳固的上层建筑
description: ZWB's Up
author: ZWB
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://zwb-ict.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
#plugins:
#- hexo-generator-feed
#- hexo-generator-sitemap
## Themes: https://hexo.io/themes/
theme: maupassant

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/zwb-ict/zwb-ict.github.io
  branch: master

org:
  emacs: '/Applications/Emacs.app/Contents/MacOS/Emacs'

# feed:
#   type: atom
#   path: atom.xml
#   limit: 20
#   hub:
#
# sitemap:
#   path: sitemap.xml

search:
  path: search.xml
  field: post






















主题的yml：

fancybox: true ## If you want to use fancybox please set the value to true.
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: zwb-ict ## Your disqus_shortname, e.g. username
google_search: false ## Use Google search, true/false.
baidu_search: ## Use Baidu search, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
self_search: true ## Use a jQuery-based local search engine, true/false.
google_analytics: UA-58174747-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
shareto: true ## If you want to use the share button please set the value to true.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: history
    directory: history/
    icon: fa-history
  - page: guestbook
    directory: guestbook/
    icon: fa-guestbook
  - page: rss
    directory: atom.xml
    icon: fa-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: 程序员博客墙
    url: http://www.blogwall.us/
  - title: 兰亭风雨的专栏
    url: http://blog.csdn.net/ns_code?viewmode=contents/
  - title: 结构之法 算法之道
    url: http://blog.csdn.net/v_july_v
  - title: Alexandre Mélard Tech Blog
    url: http://blog.melard.fr/
  - title: 笑遍世界
    url: http://smilejay.com/
  - title: EFE
    url: http://efe.baidu.com/
  - title: 陈斌
    url: http://blog.binchen.org/index.html/
  - title: V8 JavaScript Engine
    url: http://v8project.blogspot.sg/

# Static files
js: js
css: css

# Theme version
version: 0.0.1

**Comment by tufu9441** [comment]
你不可能没修改主题，连首页“阅读更多”和文章TOC的样式都变了，或者你重新安装我这最新版的试试。

**Comment by zwb-ict** [comment]
我是用hexo-render-org 将org生成html，莫非和这个包有关？我重新下载你的包试一下。

**Comment by tufu9441** [comment]
我都不知道`hexo-renderer-org`这个东西是干嘛的……这个主题需要的是`hexo-renderer-jade`和`hexo-renderer-sass`。

**Comment by zwb-ict** [comment]
这是我和你的origin/master 分支的对比，你的主题我确实只改了这一个文件，估计是hexo-renderer-org的问题，这个包是将org生成html的，但是见鬼了，不应该添加自己的样式才对。我用md写文章试试。

diff --git a/_config.yml b/_config.yml
index 48eb5a5..237e36b 100644
--- a/_config.yml
+++ b/_config.yml
@@ -1,12 +1,12 @@
 fancybox: true ## If you want to use fancybox please set the value to true.
 duoshuo: ## Your duoshuo_shortname, e.g. username
-disqus: ## Your disqus_shortname, e.g. username
-google_search: true ## Use Google search, true/false.
+disqus: zwb-ict ## Your disqus_shortname, e.g. username
+google_search: false ## Use Google search, true/false.
 baidu_search: ## Use Baidu search, true/false.
 swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
 tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
-self_search: ## Use a jQuery-based local search engine, true/false.
-google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
+self_search: true ## Use a jQuery-based local search engine, true/false.
+google_analytics: UA-58174747-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
 baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
 shareto: true ## If you want to use the share button please set the value to true.
 busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
:...skipping...
diff --git a/_config.yml b/_config.yml
index 48eb5a5..237e36b 100644
--- a/_config.yml
+++ b/_config.yml
@@ -1,12 +1,12 @@
 fancybox: true ## If you want to use fancybox please set the value to true.
 duoshuo: ## Your duoshuo_shortname, e.g. username
-disqus: ## Your disqus_shortname, e.g. username
-google_search: true ## Use Google search, true/false.
+disqus: zwb-ict ## Your disqus_shortname, e.g. username
+google_search: false ## Use Google search, true/false.
 baidu_search: ## Use Baidu search, true/false.
 swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
 tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
-self_search: ## Use a jQuery-based local search engine, true/false.
-google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
+self_search: true ## Use a jQuery-based local search engine, true/false.
+google_analytics: UA-58174747-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
 baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
 shareto: true ## If you want to use the share button please set the value to true.
 busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
@@ -21,6 +21,12 @@ menu:
:...skipping...
diff --git a/_config.yml b/_config.yml
index 48eb5a5..237e36b 100644
--- a/_config.yml
+++ b/_config.yml
@@ -1,12 +1,12 @@
 fancybox: true ## If you want to use fancybox please set the value to true.
 duoshuo: ## Your duoshuo_shortname, e.g. username
-disqus: ## Your disqus_shortname, e.g. username
-google_search: true ## Use Google search, true/false.
+disqus: zwb-ict ## Your disqus_shortname, e.g. username
+google_search: false ## Use Google search, true/false.
 baidu_search: ## Use Baidu search, true/false.
 swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
 tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
-self_search: ## Use a jQuery-based local search engine, true/false.
-google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
+self_search: true ## Use a jQuery-based local search engine, true/false.
+google_analytics: UA-58174747-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
 baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
 shareto: true ## If you want to use the share button please set the value to true.
diff --git a/_config.yml b/_config.yml
index 48eb5a5..237e36b 100644
--- a/_config.yml
+++ b/_config.yml
@@ -1,12 +1,12 @@
 fancybox: true ## If you want to use fancybox please set the value to true.
 duoshuo: ## Your duoshuo_shortname, e.g. username
-disqus: ## Your disqus_shortname, e.g. username
-google_search: true ## Use Google search, true/false.
+disqus: zwb-ict ## Your disqus_shortname, e.g. username
+google_search: false ## Use Google search, true/false.
 baidu_search: ## Use Baidu search, true/false.
 swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
 tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
-self_search: ## Use a jQuery-based local search engine, true/false.
-google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
+self_search: true ## Use a jQuery-based local search engine, true/false.
+google_analytics: UA-58174747-1 ## Your Google Analytics tracking id, e.g. UA-42425684-2
 baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
 shareto: true ## If you want to use the share button please set the value to true.
 busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
@@ -21,6 +21,12 @@ menu:
   - page: about
     directory: about/
     icon: fa-user
+  - page: history
+    directory: history/
+    icon: fa-history
+  - page: guestbook
+    directory: guestbook/
+    icon: fa-guestbook
   - page: rss
     directory: atom.xml
     icon: fa-rss
@@ -34,16 +40,26 @@ widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts
   - links

 links:
-  - title: site-name1
-    url: http://www.example1.com/
-  - title: site-name2
-    url: http://www.example2.com/
-  - title: site-name3
-    url: http://www.example3.com/
+  - title: 程序员博客墙
+    url: http://www.blogwall.us/
+  - title: 兰亭风雨的专栏
+    url: http://blog.csdn.net/ns_code?viewmode=contents/
+  - title: 结构之法 算法之道
+    url: http://blog.csdn.net/v_july_v
+  - title: Alexandre Mélard Tech Blog
+    url: http://blog.melard.fr/
+  - title: 笑遍世界
+    url: http://smilejay.com/
+  - title: EFE
+    url: http://efe.baidu.com/
+  - title: 陈斌
+    url: http://blog.binchen.org/index.html/
+  - title: V8 JavaScript Engine
+    url: http://v8project.blogspot.sg/

 # Static files
 js: js
 css: css

 # Theme version
-version: 0.0.0
+version: 0.0.1

**Comment by tufu9441** [comment]
应该就是你用了`hexo-renderer-org`的原因，并不是一个通用的生成方式。

**Comment by zwb-ict** [comment]
这是Blog下的package.json文件，有需要删除的吗？

    "hexo-deployer-git": "latest",
    "hexo-generator-archive": "latest",
    "hexo-generator-category": "latest",
    "hexo-generator-index": "latest",
    "hexo-generator-search": "latest",
    "hexo-generator-tag": "latest",
    "hexo-renderer-ejs": "latest",
    "hexo-renderer-jade": "latest",
    "hexo-renderer-marked": "latest",
    "hexo-renderer-sass": "latest",
    "hexo-renderer-stylus": "latest",
    "hexo-server": "latest"

**Comment by tufu9441** [comment]
没有
