### ISSUE TITLE
关于分类和标签页面的改进

### ISSUE THREAD

**Issue by tufu9441** [tufu9441/maupassant-hexo#59]
@v123582 现在在某个分类或者标签页面时，导航栏中没有任何一项处于current状态，例如https://www.haomwei.com/categories/technology/ 页面显示效果如下：
![qq 20160218100305](https://cloud.githubusercontent.com/assets/6790361/13131604/9fa3a33e-d627-11e5-96d1-c345b2979c49.png)

但是我希望处在某个分类或者标签页面时，导航栏中的“归档”一项能处于current状态，就像位于真正的归档页面时一样，例如：
![qq 20160218101341](https://cloud.githubusercontent.com/assets/6790361/13131707/4febefc6-d628-11e5-970e-16ceba12a8a8.png)

我觉得应该是修改`layout/_partial/helpers.jade`里的一些代码，但是试了好久也没有研究出来，不知你能否有空时帮我看看是否有可能实现呢？谢谢！

**Comment by SinalVee** [comment]
在`layout/_partial/helpers.jade`中`if`后边添加以下代码可实现，但是有bug。
因为`layout/base.jade`第44行45行是循环`theme.menu`传入`a_with_current`，而`theme.menu`是能在_config.yml中修改的，所以不能保证`归档`一定是`archives/`。
```
  else if (href == 'archives/' && is_tag())
    a.current(href=url)
      i(class='fa' + ' ' + id)= ' ' + content
  else if (href == 'archives/' && is_category())
    a.current(href=url)
      i(class='fa' + ' ' + id)= ' ' + content
```

**Comment by tufu9441** [comment]
非常感谢你的帮助！我明白你说的BUG，不过至少当`归档`页面的路径是`archives/`的时候是有效的，也算是暂时解决了吧～ 😊

**Comment by SinalVee** [comment]
也感谢你的主题，我的github主页换成这个了，大赞！
可惜disqus不知道为啥没成功显示，再去研究一番……

**Comment by tufu9441** [comment]
我看了一下你的网页源代码，也许是你hexo配置文件里站点的URL设置的有问题？在//前面加上https试试。

**Comment by SinalVee** [comment]
感谢！加上https正常显示了╮(╯▽╰)╭
