### ISSUE TITLE
分割线穿透了目录

### ISSUE THREAD

**Issue by unnamed42** [tufu9441/maupassant-hexo#62]
理想的情况应该是像[这个帖子](http://unnamed42.github.io/2015-12-04-%E4%BD%8D%E8%BF%90%E7%AE%97%E6%8A%80%E5%B7%A7.html)里的前两条分割线一样
但是由二级标题自动生成的分割线就会穿透目录
总之，`******` 的分割线没有问题，`## Title`自动加入的分割线就会有问题

**Comment by tufu9441** [comment]
Fixed by commit [f264a5e](https://github.com/tufu9441/maupassant-hexo/commit/f264a5e1c567d86d69c2d7c53622048d1d4f7251).
