### ISSUE TITLE
关于添加文章目录和文章分类、订阅

### ISSUE THREAD

**Issue by linggan100** [tufu9441/maupassant-hexo#65]
我看到你文章里有写很多问题的解决方案，帮忙解决了不少问题，先表示感谢。 然后，你提到的front-matter没有找到在哪里哦，所以目录和分类没法弄好，另外，订阅功能是怎么弄，需要安装什么吗？有空解答下，谢啦

**Comment by tufu9441** [comment]
https://hexo.io/zh-cn/docs/front-matter.html

**Comment by linggan100** [comment]
订阅的问题没有回答我啊，是不能订阅了吗，我看你博客上面也不能订阅，点击出来的是代码

**Comment by tufu9441** [comment]
订阅不就是给出一个RSS地址么？然后放到阅读器里就行了啊。

On 周三, 2月 24, 2016 at 21:09, ideazhao <notifications@github.com> wrote:
订阅的问题没有回答我啊，是不能订阅了吗，我看你博客上面也不能订阅，点击出来的是代码

—
Reply to this email directly or view it on GitHub
[https://github.com/tufu9441/maupassant-hexo/issues/65#issuecomment-188249385] .[https://github.com/notifications/beacon/AGec2euUrmF7KC9Ui801zGuLha4Cx2mFks5pnaMDgaJpZM4HhRM9.gif]

**Comment by linggan100** [comment]
@tufu9441 我看到现在的情况是不显示文章数量的，包括总数，分类文章数，是我没弄对还是没有做进去？有空解答下，谢谢

**Comment by tufu9441** [comment]
没有显示数量的功能。

**Comment by linggan100** [comment]
@tufu9441 好吧，这是目前觉得唯一美中不足的，可以的话以后尽量加上吧~
