### ISSUE TITLE
安装之后博客主页打不开

### ISSUE THREAD

**Issue by dingtwo** [tufu9441/maupassant-hexo#66]
安装之后页面打开出现如下文本

> extends base - var current_title = page.title || tag.name || category.name || site.title block title title= config.title + ' | ' + config.subtitle block content for post in page.posts.toArray() .post h2.post-title include _partial/helpers a(href=url_for(post.path)) +title(post) .post-meta= post.date.format(config.date_format) if theme.duoshuo a.ds-thread-count(data-thread-key=post.path, href=url_for(post.path) + '#comments') if theme.disqus a.disqus-comment-count(data-disqus-identifier=post.path, href=url_for(post.path) + '#disqus_thread') if post.description .post-content != post.description else if post.excerpt .post-content != post.excerpt else if post.content - var br = post.content.indexOf('\n') if br < 0 .post-content != post.content else .post-content != post.content.substring(0, br) p(class='readmore') a(href=url_for(post.path))= __('Readmore') include _partial/paginator if theme.disqus script(id='dsq-count-scr' src='//#{theme.disqus}.disqus.com/count.js' async)

请问是我缺少什么设置吗?

**Comment by tufu9441** [comment]
hexo-renderer-jade没有安好。

On 周三, 2月 24, 2016 at 19:18, dingtwo <notifications@github.com> wrote:
安装之后页面打开出现如下文本

extends base - var current_title = page.title || tag.name || category.name ||
site.title block title title= config.title + ' | ' + config.subtitle block
content for post in page.posts.toArray() .post h2.post-title include partial/helpers a(href=url_for(post.path)) +title(post) .post-meta=
post.date.format(config.date_format) if theme.duoshuo
a.ds-thread-count(data-thread-key=post.path, href=url_for(post.path) +
'#comments') if theme.disqus
a.disqus-comment-count(data-disqus-identifier=post.path, href=url_for(post.path)
+ '#disqus_thread') if post.description .post-content != post.description else
if post.excerpt .post-content != post.excerpt else if post.content - var br =
post.content.indexOf('\n') if br < 0 .post-content != post.content else
.post-content != post.content.substring(0, br) p(class='readmore')
a(href=url_for(post.path))= _ ('Readmore') include _partial/paginator if theme.disqus
script(id='dsq-count-scr' src='//#{theme.disqus}.disqus.com/count.js' async)

请问是我缺少什么设置吗?

**Comment by dingtwo** [comment]
ok弄好了,thanks!

**Comment by est7** [comment]
请问一下什么原因?我也出现了相同问题

**Comment by tufu9441** [comment]
上面已经解释了。
