### ISSUE TITLE
markdown使用时不能支持表格

### ISSUE THREAD

**Issue by qinf** [tufu9441/maupassant-hexo#69]
如题，当使用markdown语法生成表格时，格式全部丢失。望有时间解决，谢谢！

**Comment by tufu9441** [comment]
你所说的问题并不存在，当markdown内容如下时：
```markdown
header 1 | header 2
---|---
row 1 col 1 | row 1 col 2
row 2 col 1 | row 2 col 2
```
生成的表格样式如下：
![screencapture at sun feb 28 14 49 47 cst 2016](https://cloud.githubusercontent.com/assets/6790361/13377909/bf9fe53e-de2a-11e5-9556-0887550af365.png)

**Comment by qinf** [comment]
原始的markdown文件：
![image](https://cloud.githubusercontent.com/assets/1277293/13392963/49fe2918-df19-11e5-981b-57c75192b1af.png)
运行
`hexo g`
`hexo s`
浏览器查看结果：
![image](https://cloud.githubusercontent.com/assets/1277293/13392976/747e8340-df19-11e5-88e0-35d4d0388608.png)
难道是写的markdown格式或者配置有问题？

**Comment by tufu9441** [comment]
markdown格式的问题吧，你用的markdown引擎是默认的hero-renderer-marked吗？

**Comment by qinf** [comment]
我安装 maupassant install中做的：
```
npm install hexo-renderer-sass --save
npm install hexo-renderer-jade --save
```

**Comment by tufu9441** [comment]
跟这两个没关系，我说的是markdown引擎用的是否是默认的hexo-renderer-marked。或者你提供一个在线的demo，我看一下。

**Comment by qinf** [comment]
这个可以吗？http://qinf.github.io/ 暂时不是用的这个主题！

**Comment by tufu9441** [comment]
😓不是用这个主题我怎么看问题出在哪……
