### ISSUE TITLE
Theme didn't work...

### ISSUE THREAD

**Issue by xring** [tufu9441/maupassant-hexo#7]
My environment is:

```
hexo: 3.1.1
os: Linux 3.13.0-32-generic linux x64
http_parser: 2.5.0
node: 5.0.0
v8: 4.6.85.28
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2d
```

when I try to use `hexo g` and `hexo s` then visit **localhost:4000** I got this:

> extends base - var current_title = page.title || tag.name || category.name || site.title block title title= config.title + " | " + config.subtitle block content for post in page.posts.toArray() .post h2.post-title include _partial/helpers a(href=url_for(post.path)) +title(post) .post-meta= post.date.format(config.date_format) if theme.duoshuo span.ds-thread-count(data-thread-key=post.path) if theme.disqus span.disqus-comment-count(data-disqus-identifier=post.path) if post.description .post-content != post.description else if page.excerpt .post-content != post.excerpt else if post.content - var br = post.content.indexOf('\n') if br < 0 .post-content != post.content else .post-content != post.content.substring(0, br) p(class="readmore") a(href=url_for(post.path))= __('Readmore') include _partial/paginator if theme.disqus script(id='dsq-count-scr' src='//#{theme.disqus}.disqus.com/count.js' async)

Can you help me fix this? thx!

**Comment by tufu9441** [comment]
Have you installed hexo-renderer-jade and hexo-renderer-sass？

Best regards,
Haoming Wei

2015-11-04 18:50 GMT+08:00 xring <notifications@github.com>:

**Comment by xring** [comment]
yes, I've install them already.

**Comment by tufu9441** [comment]
Sorry I am not familiar with Linux OS. Maybe you can try this primary version: https://github.com/icylogic/maupassant-hexo and then tell me whether you will encounter the same problem.

**Comment by v123582** [comment]
@xring it looks like jade render failed. Can you use `npm list hexo-renderer-jade` to check its version?

**Comment by xring** [comment]
@tufu9441 @v123582 thanks a lot~ I'll try it.

**Comment by tufu9441** [comment]
@xring Can you use it normally now? I will close the issue if so.

**Comment by tufu9441** [comment]
@greezi encountered this problem and solved successfully, maybe you can ask him for some help.

**Comment by jiacai2050** [comment]
Jade is replaced with Pug, so install `hexo-renderer-pug` to fix this.
