### ISSUE TITLE
不显示文章目录

### ISSUE THREAD

**Issue by loshine** [tufu9441/maupassant-hexo#72]
您好哦，我的博客从 Jekkyl 迁移过来，与您的博客相比少了文章目录功能

不知道是我自己格式问题还是设置错误，还请帮忙看看哦

我的博客地址是: [饭窝](http://loshine.me)

我的博客源码: [github](https://github.com/loshine/loshine.github.io), hexo-source 分支

**Comment by tufu9441** [comment]
主题的说明文档里写了，在`front-matter`里填上`toc: true`。

**Comment by loshine** [comment]
谢谢

**Comment by pinkomeo** [comment]
为什么我的加了
`toc: true`还是不行。。。。
