### ISSUE TITLE
关于在_config.yml文件中取消友情链接配置无效的问题

### ISSUE THREAD

**Issue by weiwosuoai** [tufu9441/maupassant-hexo#74]
你好，首先需要感谢你贡献的这个主题，我非常喜欢。。:-D

问题是，我在_config.yml文件中注释了友情链接的配置，但是在hexo generate后，预览界面上依旧还有友情链接的侧边栏，貌似并没有什么作用,请问是哪里出现问题了吗？

**Comment by tufu9441** [comment]
在_config.yml中widgets下删掉- links这一项

**Comment by weiwosuoai** [comment]
- links 也删除了
`widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments`

另外，就是最近评论这一栏也没出来，不知是咋回事。。。

**Comment by weiwosuoai** [comment]
- links这一项也删除了

widgets:
  - search
  - category
  - tag
  - recent_posts
  - recent_comments

另外就是，最近评论这一栏也没出来，不知咋回事...

**Comment by tufu9441** [comment]
你没有设置多说或者disqus评论系统的short_name，当然不会显示最近评论。我又测试了一下，链接小工具的添加和删除都是正常的。你重新生成之前hexo clean了么？

**Comment by weiwosuoai** [comment]
哦哦，原来是没有设置评论系统，就没有。
clean了哦，generate了过后，友情链接依旧还在那里...，会不会跟hexo版本关系啊

**Comment by tufu9441** [comment]
那你重新`hexo init`一个文件夹试试，我用的是Hexo 3.2.0

**Comment by weiwosuoai** [comment]
额，我的也是3.2.0

**Comment by weiwosuoai** [comment]
重新 init 了一个，还是一样...,好气啊

**Comment by weiwosuoai** [comment]
问题解决了，我配置的是根目录下的_config.yml，应该修改主题目录下的_config.yml，被自己坑了...

**Comment by enzeM** [comment]
@weiwosuoai 我犯了跟你同样的错误，这帖子真帮大忙了。
