### ISSUE TITLE
文章中使用引用，显示有问题

### ISSUE THREAD

**Issue by weiwosuoai** [tufu9441/maupassant-hexo#76]
文章中使用引用，显示有问题...

**Comment by tufu9441** [comment]
什么问题，贴图。

**Comment by weiwosuoai** [comment]
使用引用 后变成这样了：
![j 02yj 5t 3 iq 7mg ar9](https://cloud.githubusercontent.com/assets/10162383/13697360/e212e504-e7a7-11e5-8586-f3ca57fb8c84.png)

**Comment by tufu9441** [comment]
这个红框是你自己加的吗？还有字体颜色本来就是红色？

**Comment by weiwosuoai** [comment]
红框和红色的字是我自己加的，前面为啥变成引号了

**Comment by weiwosuoai** [comment]
md是这样的：
![a5 he pht3mi61v b0ql9mg](https://cloud.githubusercontent.com/assets/10162383/13697427/681666f8-e7a8-11e5-977b-c3cff205fca8.png)

**Comment by tufu9441** [comment]
我晕，这就是引用的样式好么……😓 #16

**Comment by weiwosuoai** [comment]
我想要的样式是这样的：
![w vy9x cvkxh624 8 4ug](https://cloud.githubusercontent.com/assets/10162383/13697454/8f9767ae-e7a8-11e5-81e7-90160e2e1ad8.png)

**Comment by weiwosuoai** [comment]
能改吗

**Comment by tufu9441** [comment]
那你自己改CSS吧。

**Comment by weiwosuoai** [comment]
好吧，我还以为显示有问题

**Comment by chendi20082009** [comment]
> 个人也觉得这种引用方式比较好
