### ISSUE TITLE
我又发现一个问题

### ISSUE THREAD

**Issue by ykqmain** [tufu9441/maupassant-hexo#79]
友链和文章内的链接，点击之后，会在新窗口中打开 `about:blank` 这个页面，然后，自动跳转到 指定链接，
仔细观察就能发现，几乎所有的文章内的链接都是这样的，请问这是什么原因？ ＝ ＝  
强迫症表示不能忍，望修复

**Comment by ykqmain** [comment]
@tufu9441 我有90%确定，出现这个问题是因为 disqus 的原因，我换了一个主题，使用disqus仍然有这个问题，禁用disqus之后打开链接正常

**Comment by v123582** [comment]
@ykqmain 不懂這樣有什麼問題？...你覺得想要修成什麼樣？
