### ISSUE TITLE
theme似乎不支持Markdown里的表格语法

### ISSUE THREAD

**Issue by ArtinHuang** [tufu9441/maupassant-hexo#8]
比如说这种
```
| ABCD | EFGH | IJKL |
|:-----|:-----|:-----|
| a    | b    | c    |
| d    | e    | f    |
| g    | h    | i    |
```

| ABCD | EFGH | IJKL |
|:---- |:----| :----|
| a    | b    | c    |
| d    | e    |  f   |
| g    | h    |   i  |

**Comment by tufu9441** [comment]
这个我还真没研究过啊，是跟theme有关的吗？能否提供几个支持表格的theme我看看参考一下。

**Comment by ArtinHuang** [comment]
[Hexo主题列表](https://hexo.io/themes/)

**Comment by v123582** [comment]
應該要改一下 css ， 從 html 來看是有表格存在的

**Comment by ArtinHuang** [comment]
@v123582 可以考虑Pull一个requests？

**Comment by v123582** [comment]
@ArtinHuang 我修正 PR 了，請 @tufu9441 幫忙確認有沒有問題：）

**Comment by tufu9441** [comment]
@v123582 现在可以了，非常感谢
