### ISSUE TITLE
请问如何实现标签中文，但url是英文

### ISSUE THREAD

**Issue by kingmo888** [tufu9441/maupassant-hexo#83]
虚拟主机对中文url支持比较差，只有ftpsync插件上传才可以（显示乱码），ftp上传（正常中文，但无法访问）。（万网）
但是我本机的电脑ftpsync插件不能用了 - -！提示tcp错误。只好尝试改英文url

**Comment by tufu9441** [comment]
这跟主题有关系么？

On 周四, 3月 24, 2016 at 21:29, kingmo888 <notifications@github.com> wrote:
虚拟主机对中文url支持比较差，只有ftpsync插件上传才可以（显示乱码），ftp上传（正常中文，但无法访问）。（万网）
但是我本机的电脑ftpsync插件不能用了 - -！提示tcp错误。只好尝试改英文url
