### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by Link-Zhang** [tufu9441/maupassant-hexo#84]
Hi， I need you help. I  installed hexo-renderer-sass and hexo-renderer-jade. But when I used the theme,
show that:
ERROR Process failed: layout/archive.jade
TypeError: Cannot read property 'compile' of undefined
ERROR Process failed: layout/index.jade
TypeError: Cannot read property 'compile' of undefined
....

How can I fix it?

**Comment by tufu9441** [comment]
Try to re-install Hexo and necessary plugins in another folder.

**Comment by tufu9441** [comment]
Update Hexo to the latest version 3.2.2 and the problem may be resolved.
