### ISSUE TITLE
分类问题

### ISSUE THREAD

**Issue by fangzheng0518** [tufu9441/maupassant-hexo#85]
分类可否加上每个分类下共有多少文章？
例如：java(5)  hexo(20)

**Comment by tufu9441** [comment]
自己把`maupassant-hexo/layout/_widget/category.jade`第四行的false改成true即可。

**Comment by fangzheng0518** [comment]
我改过，但是不是我想要的效果
改了之后是java1，我想加个括号java(1)这种的话怎么改？
...............没了解过jade






在 2016-03-28 13:14:37，"tufu9441" <notifications@github.com> 写道：


自己把maupassant-hexo/layout/_widget/category.jade第四行的false改成true即可。

**Comment by v123582** [comment]
@fangzheng0518 如果你想要改變 default helper 的樣式的話，要自己進去 npm_modules/hexo 裡面改

**Comment by fangzheng0518** [comment]
好的，明白了。三克油






在 2016-03-29 11:01:57，"WeiYuan" <notifications@github.com> 写道：


@fangzheng0518 如果你想要改變 default helper 的樣式的話，要自己進去 npm_modules/hexo 裡面改

**Comment by pinkomeo** [comment]
楼主解决了么？能否告知如何修改
