### ISSUE TITLE
如何设置sitemap

### ISSUE THREAD

**Issue by duanzhiying** [tufu9441/maupassant-hexo#88]
想请教下，使用该主题，如何配置并显示sitemap，参考网上的方式都没成功，是主题的原因还是？
感谢解惑！

**Comment by tufu9441** [comment]
跟主题没关系。

On 周五, 4月 1, 2016 at 10:31, duanzhiying <notifications@github.com> wrote:
想请教下，使用该主题，如何配置并显示sitemap，参考网上的方式都没成功，是主题的原因还是？
感谢解惑！
