### ISSUE TITLE
how to change the default language setting

### ISSUE THREAD

**Issue by mousepotato** [tufu9441/maupassant-hexo#89]
I installed the theme, the default language setting is Zh-TW? How to change it to Zh-CN

**Comment by aimer1124** [comment]
@mousepotato `zh-CN` is Simplified  Chinese,'zh-TW' is Traditional Chinese.

Config the root folder about '_config.yml' 
`language: zh-CN `

**Comment by tufu9441** [comment]
@aimer1124 Thanks for reply!
