### ISSUE TITLE
关于本地搜索

### ISSUE THREAD

**Issue by sectun** [tufu9441/maupassant-hexo#91]
看到isuue #68 想试试本地搜索，
打开配置文件关掉google，baidu，self_search 设成true，
报错，
然后参照http://hahack.com/codes/local-search-engine-for-hexo/ 安装插件：
npm install --save hexo-generator-search
倒是不报错了，
但是网站输入框没反应，
不知道什么问题？

**Comment by tufu9441** [comment]
是否在`_config.yml`中进行了设置？

![qq 20160414133803](https://cloud.githubusercontent.com/assets/6790361/14518015/28840a78-0246-11e6-8832-c9d75af565b5.png)

**Comment by sectun** [comment]
这样倒是可以了，但是似乎只有live search功能，不能回车新页面打开搜索框吗？

**Comment by tufu9441** [comment]
作者说了，这是一个live search engine。
![qq 20160414135155](https://cloud.githubusercontent.com/assets/6790361/14518204/11b97aec-0248-11e6-8c0d-7725af8ead73.png)
