### ISSUE TITLE
layout:page didn't work?

### ISSUE THREAD

**Issue by Troland** [tufu9441/maupassant-hexo#92]
Hi, i encountered a problem that i have followed the scripts at #37 but i found layout:page seemed not work, any help is apperiated, thanks

**Comment by tufu9441** [comment]
Don't dismiss the space in `layout: page`.

**Comment by Troland** [comment]
Thanks, i just misunsdood the meaning, i just misplace the folder then i run the command `hexo new page "about"` and everything works.
