### ISSUE TITLE
主页分页不显示侧边栏与底部内容，有些文章不截断成“摘要”

### ISSUE THREAD

**Issue by zealseeker** [tufu9441/maupassant-hexo#96]
请见  http://www.zealseeker.com/page/2/
只有主页的文章内容，没有侧边栏和底部内容

（所有文章都是import进来的，所以虽然是md文件，但很多都是html）
另外尽管有些文章是截断内容的（也就是首页中只显示一段，但有几篇文章全部显示了。

**Comment by tufu9441** [comment]
也许就是你import进来的文章内容的问题，尝试手动编辑成正常的markdown格式。

**Comment by zealseeker** [comment]
@tufu9441 是的，我看到貌似是<script>的问题，md文件中有个<script src>却没有</script>也没用/>·· 这应该属于hexo的问题~
