### ISSUE TITLE
disqus设置了但是没效果

### ISSUE THREAD

**Issue by ghuiii** [tufu9441/maupassant-hexo#97]
是不是没有支持disqus,看了一下源码也没有disqus相关的设置

**Comment by tufu9441** [comment]
有

On 周四, 4月 28, 2016 at 11:00, ghui <notifications@github.com> wrote:
是不是没有支持disqus,看了一下源码也没有disqus相关的设置

**Comment by ghuiii** [comment]
哦哦,是我搞错了,我clone的是另外一个人维护的这个主题,close吧
