### ISSUE TITLE
能否建立多级分类？

### ISSUE THREAD

**Issue by dupengair** [tufu9441/maupassant-hexo#99]
能否在一个分类下面建立子类，显示成缩进效果？试了好久，建立的分类总是平级的

**Comment by tufu9441** [comment]
Hexo本身是支持多级分类目录的，参见https://github.com/hexojs/hexo/issues/848

不过要想正常显示出来，应该还需要修改主题CSS，找到一篇资料：https://segmentfault.com/a/1190000004359502 有兴趣的话可以尝试。
